### ISSUE TITLE
phone number not saved <apiurl>/Document

### ISSUE THREAD

**Issue by aschneiderMainSpring** [NCRCounterpointAPI/APIGuide#10]
The following, as an example, is being sent to <api>/Document but the PHONE_1 field is not being populated in the database.  Is the data the issue?
{
  "PS_DOC_HDR": {
    "STR_ID": "4025",
    "STA_ID": "1",
    "DRW_ID": "1",
    "TKT_TYP": "T",
    "DOC_TYP": "O",
    "USR_ID": "APIUSER",
    "TAX_COD": "LOCAL",
    "NORM_TAX_COD": "LOCAL",
    "SHIP_VIA_COD": "3",
    "CUST_NO": "CN4025-000059",
    "BILL_TO_CONTACT": {
      "FST_NAM": "Brett",
      "LST_NAM": "Greenough",
      "ADRS_1": "507 S 16th St",
      "ADRS_2": "",
      "CITY": "Fort Calhoun",
      "ZIP_COD": "68023",
      "STATE": "NE",
      **"PHONE_1": "(402) 658-1205",**
      "NAM_TYP": "B",
      "EMAIL_ADRS_1": "bgreenough@completenutrition.com",
      "NAM": "Brett Greenough"
    },
    "PS_DOC_HDR_EC": {
      "EC_ORD_NO": "CN-20170301-479568",
      "EC_IMP_DT": "2017-03-01T17:06:30.844Z",
      "EC_IMP_HAD_SPECL_MSGS": "N",
      "NXT_EC_SEQ_NO_OFFSET": 1
    },
    "SHIP_TO_CONTACT": {
      "FST_NAM": "Brett",
      "LST_NAM": "Greenough",
      "ADRS_1": "507 S 16th St",
      "ADRS_2": "",
      "CITY": "Fort Calhoun",
      "ZIP_COD": "68023",
      "STATE": "NE",
      "PHONE_1": "(402) 658-1205",
      "NAM_TYP": "P",
      "EMAIL_ADRS_1": "bgreenough@completenutrition.com",
      "NAM": "Brett Greenough"
    },
    "PS_DOC_NOTE": [
      {
        "NOTE_ID": "CustomerIPAddress",
        "NOTE": "74.126.55.250"
      },
      {
        "NOTE_ID": "HomeStoreID",
        "NOTE": ""
      }
    ],
    "PS_DOC_LIN": [
      {
        "LIN_TYP": "O",
        "ITEM_NO": "3080002",
        "PRC": "24.99",
        "USR_ENTD_PRC": "Y",
        "QTY_SOLD": "1"
      }
    ],
    "PS_DOC_HDR_MISC_CHRG": [
      {
        "TOT_TYP": "O",
        "MISC_CHRG_NO": "1",
        "MISC_TYP": "A",
        "MISC_AMT": "0",
        "MISC_AMT_SHIPPED": "75"
      }
    ],
    "PS_DOC_PMT": [
      {
        "AMT": "105.48",
        "PAY_COD": "CREDIT",
        "FINAL_PMT": "N",
        "PS_DOC_PMT_PROMPT": [
          {
            "PROMPT_SEQ_NO": "1",
            "PROMPT_TXT": "60019027054",
            "PROMPT_VAL": "transactionId"
          },
          {
            "PROMPT_SEQ_NO": "2",
            "PROMPT_TXT": "ED4GQR",
            "PROMPT_VAL": "authCode"
          }
        ]
      }
    ],
    "PS_DOC_TAX": [
      {
        "AUTH_COD": "LOCAL",
        "RUL_COD": "TAX",
        "TAX_DOC_PART": "O",
        "TAX_AMT": "5.49",
        "TOT_TXBL_AMT": "99.99"
      }
    ],
    "PS_TAX": {
      "ORD_NORM_TAX_AMT": "5.49",
      "ORD_TAX_AMT": "5.49"
    },
    "PS_DOC_HDR_TOT": {
      "TOT_TYP": "O",
      "INITIAL_MIN_DUE": "0.00",
      "TAX_AMT_SHIPPED": "75",
      "LINS": "1",
      "SUB_TOT": "99.99",
      "TAX_AMT": "5.49",
      "NORM_TAX_AMT": "5.49",
      "TOT_TND": "105.48",
      "TOT_CHNG": "0.00",
      "TOT": "105.48",
      "AMT_DUE": "0.00",
      "TOT_HDR_DISCNTBL_AMT": "99.99"
    }
  }
}

**Comment by MikeRitchie** [comment]
Could you please reproduce, then send the latest logfile from your logfiles directory (C:\Program Files (x86)\NCR\Counterpoint API\Logfiles) to mike.ritchie@ncr.com?

I'm able to successfully do a document /POST with a BILL_TO_CONTACT and I'm seeing the PHONE_1 field properly populate. If you can reduce the JSON to the smallest amount of data that still illustrates the issue that will help with debugging as well.

I'd also recommend checking to see if there are any custom triggers or constraints on PS_DOC_CONTACT that could be impacting the operation.

**Comment by MikeRitchie** [comment]
Per a separate email thread this is resolved. POST /Document only sets the billing/shipping address & phone for the order in question, it will not update the customer record (AR_CUST). To update the phone number for a customer record, a call to PATCH /Customer/{CustNo}/Address should be used.
