### ISSUE TITLE
Could not update the card data on NCR Secure Pay

### ISSUE THREAD

**Issue by bryang5** [NCRCounterpointAPI/APIGuide#105]
Im looking for the tokenization utility

Thanks
-Bryan

**Comment by MikeRitchie** [comment]
The tokenization utility is part of the API, and can be accessesd as an API call or via a UI in the API Admin console. Information here: https://github.com/NCRCounterpointAPI/APIGuide/blob/master/InstallationAndConfiguration/TokenizationUtility.md

Note there is currently an issue with the tokneniziation as too many cards can cause an error in the tokenization call. The next release will address this issue, a target date for that release will be coming soon.
