### ISSUE TITLE
401 Unauthorized when valid APIKey header is present

### ISSUE THREAD

**Issue by rickmacgillis** [NCRCounterpointAPI/APIGuide#109]
I implemented an SDK to transact with the client's installation of the NCR API software. The API sever has a properly requested and installed XML API key file and in the admin interface it shows up properly. It was issued just a few days ago, so it's perfectly valid.

When the SDK goes to talk to the API server through the Guzzle 6.X client, it sends the "APIKey" header with the valid API key string. (I've debugged it to make sure it's actually sending the header and that there wasn't an issue anywhere in my software.)

The API server responds claiming the following:
`Error: ERROR_INVALID_APIKEY: No APIKey provided. This request requires a valid, not expired APIKey value to be passed in via an "APIKey" header value.`

Here's the dump for the Guzzle options I'm sending through as documented in the [Guzzle docs](http://docs.guzzlephp.org/en/stable/).

```
array(3) {
["base_uri"]=> string(27) "https://[REDACTED]:52000"
["headers"]=> array(2) {
  ["APIKey"]=> string(40) "[REDACTED]"
  ["Accept"]=> string(16) "application/json"
}
["verify"]=> bool(false)
}
```

The `verify:false` is a temporary solution until the client installs their HTTPS certificate later. They haven't gotten that far just yet.

**Comment by MikeRitchie** [comment]
Could you provide an example of the request from Postman so we can see the request? Also, can you post or send your API logfile after a restart of the API? There is logging at startup of the service that will show the API Key files as they are identified and validated.

**Comment by Ho0m3s** [comment]
@MikeRitchie Thank you for answering the question. I am dealing with similar issue.

Here some of the info you asked . 

When i restart the window service for the NCR Counterpoint API, i do not get any log that show the API key.  Where do i properly restart the API server to see these logs, beacause i must be doing something wrong?

In postman, i  switched off the SSL verify as the client does not have a valid cert yet.

The Request form postman:
GET: https://<<redacted IP address>>:52000/ItemCategories?APIKey=<<redacted api key>>&Accept=application/json

The request results: 

{
    "ErrorCode": "ERROR_INVALID_APIKEY",
    "Message": "No APIKey provided. This request requires a valid, not expired APIKey value to be passed in via an \"APIKey\" header value."
}

Thanks in advance for any help you can provide.

**Comment by MikeRitchie** [comment]
This looks like a separate issue than the original poster, just the same error, correct? In your case Ho0m3s, it looks like you're passing the API key as a URL parameter rather than a header. The API key needs to be a header.

**Comment by Ho0m3s** [comment]
@MikeRitchie You are 100% correct. Similar error because i was passing the wrong info in the postman app. Sorry. In my application i am also using Guzzle though. 

Anyways, Now that i am passing it as header and not part of url i get this error which is different but the same one reported #112  (in which i commented on as well). As reference, all my API endpoints have been enabled for that user APIKey. 
{
    "ResponseStatus": {
        "ErrorCode": "NullReferenceException",
        "Message": "An error occurred while trying to access an object of type: UserRoles, Object value is null,    at CPAPI.Common.RepositoryCompanyBase.GetCacheKeyName(Object[] cacheKeyId)",
        "StackTrace": "   at CPAPI.Common.RepositoryCompanyBase.GetCacheKeyName(Object[] cacheKeyId)\r\n   at CPAPI.Common.KeyValueDataRepository.GetValueByName[T](String key)\r\n   at CPAPI.Common.UserRoleBusiness.CheckPermissions(String userId, String path, String verb)\r\n   at CPAPI.Common.RoleAttribute.Execute(IRequest req, IResponse res, Object requestDto)\r\n   at ServiceStack.RequestFilterAttribute.RequestFilter(IRequest req, IResponse res, Object requestDto)\r\n   at ServiceStack.ServiceStackHost.ApplyRequestFiltersSingle(IRequest req, IResponse res, Object requestDto)\r\n   at ServiceStack.ServiceStackHost.ApplyRequestFilters(IRequest req, IResponse res, Object requestDto)\r\n   at ServiceStack.Host.RestHandler.ProcessRequestAsync(IRequest httpReq, IResponse httpRes, String operationName)"
    }
}

**Comment by rickmacgillis** [comment]
I'm closing this ticket as it seems to be old news now.
