### ISSUE TITLE
Using Postman to test AddCustomerRequest and getting "ERROR_UNKNOWN"

### ISSUE THREAD

**Issue by EtherMan01** [NCRCounterpointAPI/APIGuide#11]
Here is the Header :
Authorization:Basic UGFydHlkZXBvdC5zeXNhZG1pbjozNTE2Q1dJ
APIKey:J7zFswDgwMO54tq4C6j0UGorjWCkNycIx2ixMB7N
Accept:application/json
Content-Type:application/json

Here is the Body:
{
  "AR_CUST": {
    "NAM": "Superman",
    "FST_NAM": "Clark",
    "LST_NAM": "Kent",
    "STR_ID": "100",
    "AR_CUST_NOTE": [
      {
        "Note_ID": "ADDED_85",
        "NOTE_TXT": "Be careful, Clark Kent is Superman."
      }
    ],
    "AR_SHIP_ADRS": [
      {
        "SHIP_ADRS_ID": "ADDRESS_1",
        "NAM": "HOME",
        "SHIP_NAM_TYP": "B"
      },
      {
        "SHIP_ADRS_ID": "ADDRESS_2",
        "NAM": "WORK",
        "SHIP_NAM_TYP": "B"
      }
    ]
  }
}

**Comment by MikeRitchie** [comment]
Could you email me your log file, and the Message included with the ERROR_UNKNOWN response? I suspect this may be something like a bad STR_ID or other data reference issue.

**Comment by EtherMan01** [comment]
Here is what the API Server is returning:

{
  "ErrorCode": "ERROR_UNKNOWN",
  "Message": "An error occurred during AddCustomer: Object reference not set to an instance of an object.,    at System.Object.GetType()\r\n   at ServiceStack.OrmLite.OrmLiteReadCommandExtensions.SetFilter[T](IDbCommand dbCmd, String name, Object value)\r\n   at ServiceStack.OrmLite.OrmLiteReadCommandExtensions.SingleById[T](IDbCommand dbCmd, Object value)\r\n   at ServiceStack.OrmLite.OrmLiteExecFilter.Exec[T](IDbConnection dbConn, Func`2 filter)\r\n   at CPAPI.Repositories_85.CustomerRepository_85.CPAPI.Repositories_85.ICustomerRepository.GetCustomerById(String custNo)\r\n   at CPAPI.Business_85.CustomerBusiness_85.AddCustomer(AR_CUST_POST customerEdit, String workgroupId)"
}
--------------------------------------------
On Wed, 3/15/17, MikeRitchie <notifications@github.com> wrote:

 Subject: Re: [NCRCounterpointAPI/APIGuide] Using Postman to test AddCustomerRequest and getting "ERROR_UNKNOWN" (#11)
 To: "NCRCounterpointAPI/APIGuide" <APIGuide@noreply.github.com>
 Cc: "EtherMan01" <paqman777@yahoo.com>, "Author" <author@noreply.github.com>
 Date: Wednesday, March 15, 2017, 5:36 PM
 
 Could you email me your log file,
 and the Message included with the ERROR_UNKNOWN response? I
 suspect this may be something like a bad STR_ID or other
 data reference issue.
 
 —
 You are receiving this because you authored the thread.
 Reply to this email directly, view
 it on GitHub, or mute
 the thread.

**Comment by MikeRitchie** [comment]
It looks like the error is occurring in one of two places:
* Figuring out the CUST_NO to assign to the customer
* Looking up the TEMPLATE_CUSTOMER to fill in defaults. The template customer is a customer record that is used to provide all default values not included in your JSON. 

A workgroup id is needed for either of these. The SY_WRKGRP table in Counterpoint has a NXT_CUST_NO field that contains the next CUST_NO value assigned to new customers. Here's how the API figures out the workgroup:

1. A "Workgroup" value is passed in the JSON body of the POST /Customer call:
{
"Workgroup" : "3",
"AR_CUST": {
"NAM": "Arttest3 Arttest4",
"ZIP_CODE": "22334",
"LST_NAM": "Arttest4",
"ADRS_1": "Novosibirsk",
"CUST_TYP": "C",
"PROF_DAT_3": "2017-02-01T00:00:00.0000000",
"CNTRY": "US",
"PROF_DAT_2": "1982-12-03T00:00:00.0000000",
"FST_NAM": "Arttest3",
"PHONE_1": "89998887766",
"STATE": "Guam",
"CITY": "Defaultcity",
"STR_ID": "AG1",
"SLS_REP": "AG"
}
}
2. If no "Workgroup" value is provided, then the API will get the Counterpoint user from the Authorization header, and determine that user's workgroup (from SY_USR.WRKGRP_ID)

Also make sure the given workgroup (whether explicitly in the JSON or via the authorized user, has a valid value in the SY_WRKGRP.TMPLT_CUST_NO. If the TMPLT_CUST_NO value is missing or invalid, that could cause your problem.

**Comment by EtherMan01** [comment]
The Workgroup ID for sysadmin is "HOMEOFFICE".
The 'NXT_CUST_NO' field is 'HO-1000001'.
The 'TMPLT_CUST_NO' field is 'NULL'?
could that be the problem?

--------------------------------------------
On Thu, 3/16/17, MikeRitchie <notifications@github.com> wrote:

 Subject: Re: [NCRCounterpointAPI/APIGuide] Using Postman to test AddCustomerRequest and getting "ERROR_UNKNOWN" (#11)
 To: "NCRCounterpointAPI/APIGuide" <APIGuide@noreply.github.com>
 Cc: "EtherMan01" <paqman777@yahoo.com>, "Author" <author@noreply.github.com>
 Date: Thursday, March 16, 2017, 8:32 AM
 
 It looks like the error is
 occurring in one of two places:
 
 Figuring out the CUST_NO to assign to the customer
 Looking up the TEMPLATE_CUSTOMER to fill in defaults.
 The template customer is a customer record that is used to
 provide all default values not included in your JSON.
 
 A workgroup id is needed for either of these. The
 SY_WRKGRP table in Counterpoint has a NXT_CUST_NO field that
 contains the next CUST_NO value assigned to new customers.
 Here's how the API figures out the workgroup:
 
 A "Workgroup" value is passed in the JSON body
 of the POST /Customer call:
 
 {
 
 "Workgroup" : "3",
 
 "AR_CUST": {
 
 "NAM": "Arttest3 Arttest4",
 
 "ZIP_CODE": "22334",
 
 "LST_NAM": "Arttest4",
 
 "ADRS_1": "Novosibirsk",
 
 "CUST_TYP": "C",
 
 "PROF_DAT_3":
 "2017-02-01T00:00:00.0000000",
 
 "CNTRY": "US",
 
 "PROF_DAT_2":
 "1982-12-03T00:00:00.0000000",
 
 "FST_NAM": "Arttest3",
 
 "PHONE_1": "89998887766",
 
 "STATE": "Guam",
 
 "CITY": "Defaultcity",
 
 "STR_ID": "AG1",
 
 "SLS_REP": "AG"
 
 }
 
 }
 If no "Workgroup" value is provided, then the
 API will get the Counterpoint user from the Authorization
 header, and determine that user's workgroup (from
 SY_USR.WRKGRP_ID)
 
 Also make sure the given workgroup (whether explicitly in
 the JSON or via the authorized user, has a valid value in
 the SY_WRKGRP.TMPLT_CUST_NO. If the TMPLT_CUST_NO value is
 missing or invalid, that could cause your problem.
 
 —
 You are receiving this because you authored the thread.
 Reply to this email directly, view
 it on GitHub, or mute
 the thread.

**Comment by MikeRitchie** [comment]
That could be it. The API is looking for the TEMPLT_CUST_NO to provide values for any fields not included in the JSON you posted. Putting a valid CUST_NO into that field should get you past the issue. We have a task created to handle a NULL TEMPLT_CUST_NO better in the next release.

**Comment by EtherMan01** [comment]
Still getting same error.
Here is the log.
--------------------------------------------
On Thu, 3/16/17, MikeRitchie <notifications@github.com> wrote:

 Subject: Re: [NCRCounterpointAPI/APIGuide] Using Postman to test AddCustomerRequest and getting "ERROR_UNKNOWN" (#11)
 To: "NCRCounterpointAPI/APIGuide" <APIGuide@noreply.github.com>
 Cc: "EtherMan01" <paqman777@yahoo.com>, "Author" <author@noreply.github.com>
 Date: Thursday, March 16, 2017, 9:38 AM
 
 That could be it. The API is
 looking for the TEMPLT_CUST_NO to provide values for any
 fields not included in the JSON you posted. Putting a valid
 CUST_NO into that field should get you past the issue. We
 have a task created to handle a NULL TEMPLT_CUST_NO better
 in the next release.
 
 —
 You are receiving this because you authored the thread.
 Reply to this email directly, view
 it on GitHub, or mute
 the thread.

**Comment by MikeRitchie** [comment]
I'm not seeing the log, can you resend?

Also, see the last post on this similar issue: https://github.com/NCRCounterpointAPI/APIGuide/issues/3
Could you try unchecking the Auto number checkbox as mentioned?

**Comment by MikeRitchie** [comment]
And one other thought....Workgroup information is cached, if you haven't you may try cycling the API server or including the ServerCache:no-cache header to force a reload of Workgroup information.

**Comment by EtherMan01** [comment]
After setting the Auto field to 'N' I'm getting this now. Log file is attached?

{
  "ErrorCode": "ERROR_UNKNOWN",
  "Message": "An error occurred during AddCustomer: The INSERT statement conflicted with the FOREIGN KEY constraint \"FK_AR_CUST_PS_STR\". The conflict occurred in database \"partydepot\", table \"dbo.PS_STR\", column 'STR_ID'.\r\nThe statement has been terminated.,    at System.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)\r\n   at System.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose)\r\n   at System.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady)\r\n   at System.Data.SqlClient.SqlCommand.FinishExecuteReader(SqlDataReader ds, RunBehavior runBehavior, String resetOptionsString)\r\n   at System.Data.SqlClient.SqlCommand.RunExecuteReaderTds(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, Boolean async, Int32 timeout, Task& task, Boolean asyncWrite, SqlDataReader ds, Boolean describeParameterEncryptionRequest)\r\n   at System.Data.SqlClient.SqlCommand.RunExecuteReader(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, String method, TaskCompletionSource`1 completion, Int32 timeout, Task& task, Boolean asyncWrite)\r\n   at System.Data.SqlClient.SqlCommand.InternalExecuteNonQuery(TaskCompletionSource`1 completion, String methodName, Boolean sendToPipe, Int32 timeout, Boolean asyncWrite)\r\n   at System.Data.SqlClient.SqlCommand.ExecuteNonQuery()\r\n   at ServiceStack.OrmLite.OrmLiteWriteCommandExtensions.Insert[T](IDbCommand dbCmd, T obj, Boolean selectIdentity)\r\n   at ServiceStack.OrmLite.OrmLiteExecFilter.Exec[T](IDbConnection dbConn, Func`2 filter)\r\n   at CPAPI.Repositories_85.CustomerRepository_85.CPAPI.Repositories_85.ICustomerRepository.AddCustomer(AR_CUST customer)\r\n   at CPAPI.Business_85.CustomerBusiness_85.AddCustomer(AR_CUST_POST customerEdit, String workgroupId)"
}
--------------------------------------------
On Thu, 3/16/17, MikeRitchie <notifications@github.com> wrote:

 Subject: Re: [NCRCounterpointAPI/APIGuide] Using Postman to test AddCustomerRequest and getting "ERROR_UNKNOWN" (#11)
 To: "NCRCounterpointAPI/APIGuide" <APIGuide@noreply.github.com>
 Cc: "EtherMan01" <paqman777@yahoo.com>, "Author" <author@noreply.github.com>
 Date: Thursday, March 16, 2017, 10:19 AM
 
 And one other
 thought....Workgroup information is cached, if you
 haven't you may try cycling the API server or including
 the ServerCache:no-cache header to force a reload of
 Workgroup information.
 
 —
 You are receiving this because you authored the thread.
 Reply to this email directly, view
 it on GitHub, or mute
 the thread.

**Comment by EtherMan01** [comment]
I removed the STD_ID field and is working now.
--------------------------------------------
On Thu, 3/16/17, MikeRitchie <notifications@github.com> wrote:

 Subject: Re: [NCRCounterpointAPI/APIGuide] Using Postman to test AddCustomerRequest and getting "ERROR_UNKNOWN" (#11)
 To: "NCRCounterpointAPI/APIGuide" <APIGuide@noreply.github.com>
 Cc: "EtherMan01" <paqman777@yahoo.com>, "Author" <author@noreply.github.com>
 Date: Thursday, March 16, 2017, 10:19 AM
 
 And one other
 thought....Workgroup information is cached, if you
 haven't you may try cycling the API server or including
 the ServerCache:no-cache header to force a reload of
 Workgroup information.
 
 —
 You are receiving this because you authored the thread.
 Reply to this email directly, view
 it on GitHub, or mute
 the thread.

**Comment by MikeRitchie** [comment]
Closing, with internal task to make POST /Customer more resilient to these sorts of errors, as well as reporting clearer errors to the user when data is missing/invalid
