### ISSUE TITLE
API not retrieving recent changes in CounterPoint database

### ISSUE THREAD

**Issue by arubadigital** [NCRCounterpointAPI/APIGuide#113]
Whenever a change is made to any of the columns of an item in the item table, the CounterPoint API  is not reflecting the change right away.  For example, if an item's description is changed and we use the CounterPoint API to retrieve the information for that item, the value in the DESCR column is the old value.   After some time has passed (up to a day), the API will eventually retrieve the new value for the DESCR column.  What could be causing of this delay?

**Comment by mbantug** [comment]
Item data is cached for 24 hours in the api.  You can clear the cache by passing in this header with your request:

"ServerCache": "no-cache"
