### ISSUE TITLE
Tax records created but not showing in UI

### ISSUE THREAD

**Issue by aaijtm** [NCRCounterpointAPI/APIGuide#116]
Doing a post document based on the samples found here, I am getting an order showing in my UI with correct shipping and subtotal information but the sales tax is not showing as expected. DB ver.33.06   Here is the post

{"PS_DOC_HDR": {"STR_ID": "7","STA_ID": "7-1","DRW_ID": "7-1","TKT_TYP": "T","DOC_TYP": "O","USR_ID": "---","TAX_COD": "MAGENTO", "NORM_TAX_COD": "SHIP O/S",  "SHIP_VIA_COD": "UPS_03","TKT_NO": "M0043","CUST_NO": "7-100000",
"BILL_TO_CONTACT": {"NAM":"John Doe", "FST_NAM": "No","LST_NAM": "Charge","ADRS_1": "1234 Test St","CITY": "Huntsville","ZIP_COD": "35801","STATE": "AL","PHONE_1": "","NAM_TYP": "P"},
"SHIP_TO_CONTACT": {"NAM":"John Doe", "FST_NAM": "No","LST_NAM": "Charge","ADRS_1": "1234 Test St.","CITY": "Loganville","ZIP_COD": "30052","STATE": "GA","PHONE_1": "7704485400","NAM_TYP": "P"},
"PS_DOC_NOTE": [{"NOTE_ID": "Mkt","NOTE": "--.com"},{"NOTE_ID": "MktOrderID","NOTE": "0043-12"},{"NOTE_ID": "ShipMethod","NOTE": "7"}],
"PS_DOC_LIN": [{"LIN_TYP": "O","ITEM_NO": "M-104939","PRC": "129.95","QTY_SOLD": "1.0", "HAS_PRC_OVRD" : "Y", "PRC_OVRD_REAS" : "ONLINE"} ],
"PS_DOC_HDR_MISC_CHRG": [{"TOT_TYP": "O","MISC_CHRG_NO": "1","MISC_TYP": "A","MISC_AMT": "10.00"}],
"PS_DOC_TAX": [{"AUTH_COD": "online", "RUL_COD": "online", "HAS_TAX_OVRD":"A",  "TAX_OVRD_REAS" : "online","TAX_DOC_PART": "O",
        "LIN_AMT": "129.95",
        "TXBL_LIN_AMT": "129.95",
        "TXBL_QTY": "1.00",
        "TAX_AMT": "8.40",
        "TOT_TXBL_AMT": "129.95"
        }]

"PS_DOC_PMT": [{"AMT": "148.35","PAY_COD": "AUTHORIZE","DESC": "Web Order","CURNCY_COD": "HOME",
"PS_DOC_PMT_APPLY": {"APPL_TYP":"O","AMT": "148.35","HOME_CURNCY_AMT": "148.35"}}],

}}

Thanks for your help.

**Comment by MikeRitchie** [comment]
It's possible it's related to the JSON above being malformed. There is a missing comma after the PS_DOC_TAX record (before the PS_DOC_PMT record), and an extra comma at the end of the PS_DOC_PMT_APPY record (after the 148.35 HOME_CURNCY_AMT). 

Unfortunately, JSON parsers typically ignore any data after a syntax error like this, so the PS_DOC_PMT and PS_DOC_PMT_APPLY records are probably getting fully left out of the DB. Below is a cleaned up version of the JSON above:
```
{
  "PS_DOC_HDR": {
    "STR_ID": "7",
    "STA_ID": "7-1",
    "DRW_ID": "7-1",
    "TKT_TYP": "T",
    "DOC_TYP": "O",
    "USR_ID": "---",
    "TAX_COD": "MAGENTO",
    "NORM_TAX_COD": "SHIP O/S",
    "SHIP_VIA_COD": "UPS_03",
    "TKT_NO": "M0043",
    "CUST_NO": "7-100000",
    "BILL_TO_CONTACT": {
      "NAM": "John Doe",
      "FST_NAM": "No",
      "LST_NAM": "Charge",
      "ADRS_1": "1234 Test St",
      "CITY": "Huntsville",
      "ZIP_COD": "35801",
      "STATE": "AL",
      "PHONE_1": "",
      "NAM_TYP": "P"
    },
    "SHIP_TO_CONTACT": {
      "NAM": "John Doe",
      "FST_NAM": "No",
      "LST_NAM": "Charge",
      "ADRS_1": "1234 Test St.",
      "CITY": "Loganville",
      "ZIP_COD": "30052",
      "STATE": "GA",
      "PHONE_1": "7704485400",
      "NAM_TYP": "P"
    },
    "PS_DOC_NOTE": [
      {
        "NOTE_ID": "Mkt",
        "NOTE": "--.com"
      },
      {
        "NOTE_ID": "MktOrderID",
        "NOTE": "0043-12"
      },
      {
        "NOTE_ID": "ShipMethod",
        "NOTE": "7"
      }
    ],
    "PS_DOC_LIN": [
      {
        "LIN_TYP": "O",
        "ITEM_NO": "M-104939",
        "PRC": "129.95",
        "QTY_SOLD": "1.0",
        "HAS_PRC_OVRD": "Y",
        "PRC_OVRD_REAS": "ONLINE"
      }
    ],
    "PS_DOC_HDR_MISC_CHRG": [
      {
        "TOT_TYP": "O",
        "MISC_CHRG_NO": "1",
        "MISC_TYP": "A",
        "MISC_AMT": "10.00"
      }
    ],
    "PS_DOC_TAX": [
      {
        "AUTH_COD": "online",
        "RUL_COD": "online",
        "HAS_TAX_OVRD": "A",
        "TAX_OVRD_REAS": "online",
        "TAX_DOC_PART": "O",
        "LIN_AMT": "129.95",
        "TXBL_LIN_AMT": "129.95",
        "TXBL_QTY": "1.00",
        "TAX_AMT": "8.40",
        "TOT_TXBL_AMT": "129.95"
      }
    ],
    "PS_DOC_PMT": [
      {
        "AMT": "148.35",
        "PAY_COD": "AUTHORIZE",
        "DESC": "Web Order",
        "CURNCY_COD": "HOME",
        "PS_DOC_PMT_APPLY": {
          "APPL_TYP": "O",
          "AMT": "148.35",
          "HOME_CURNCY_AMT": "148.35"
        }
      }
    ]
  }
}
```

**Comment by aaijtm** [comment]
Thanks for your reply.  Those items were corrected and have not resolved the issue.  This has been continued on issue #119
