### ISSUE TITLE
GET /Inventory/EC Endpoint returning no data

### ISSUE THREAD

**Issue by osain86** [NCRCounterpointAPI/APIGuide#12]
When performing a GET call to the /Inventory/EC endpoint, API returns 404 with the following JSON object:

{"ErrorCode":"ERROR_RECORD_NOT_FOUND", "Message":"Inventory records do not exist"}

**Comment by MikeRitchie** [comment]
This could happen if no eCommerce Categories were defined. This call will return inventory information for all items that are in Categories defined as "eCommerce categories".

Please check setup>eCommerce>Categories in Counterpoint, or the EC_CATEG_ITEMS table, to verify there are categories defined for eCommerce. You'll also want to ensure that items in those categories are stocked (have inventory records) for the eCommerce stocking location (EC_CTL.STK_LOC_ID in the database defines the stocking location for eCommerce items).

**Comment by osain86** [comment]
Thanks!
