### ISSUE TITLE
/requestlogs endpoint

### ISSUE THREAD

**Issue by jbbehar** [NCRCounterpointAPI/APIGuide#122]
When viewing the requestlogs endpoint, all data sent in to the API, including card data is being displayed.

Granted, this is an SSL secured site and firewall protected to only allow access from specific IP addresses but credentials were not requested and contents of every POST are contained therein.

I'm fairly certain this is not PCI compliant.

**Comment by MikeRitchie** [comment]
This will be addressed in an upcoming 2.1 release coming very soon. Date will be shared as soon as it is available.
