### ISSUE TITLE
SSL Error when POSTing a customer record that includes cardholder data

### ISSUE THREAD

**Issue by RG-Relentless** [NCRCounterpointAPI/APIGuide#124]
Whenever I'm trying to POST a customer record that includes cardholder information, I get the following error:

` "ErrorCode": "ERROR_UNKNOWN",
    "Message": "An error occurred during AddCustomer: Store 1: SSL Exception: Unable to read data from the transport connection: An existing connection was forcibly closed by the remote host.,    at NCR.CP.CPAPI.Base.Business.StoreBusinessExtensions.KF2NqulibR(PS_STR  )\r\n   at NCR.CP.CPAPI.Base.Business.StoreBusinessExtensions.SecurePayProcessor(PS_STR store)\r\n   at NCR.CP.CPAPI.Base.Business.CustomerExtensions.TokenizeCardOnFile(AR_CUST_CARDS card, String customerName, PS_STR store, String cardToken)\r\n   at NCR.CP.CPAPI.Base.Business.CustomerExtensions.AddCardsOnFile(AR_CUST customer, PS_STR store)\r\n   at NCR.CP.CPAPI.Base.Business.CustomerBusiness.CPAPI.Common.ICustomerBusiness.AddCustomer(AR_CUST_POST customerEdit, String workgroupId)"`

This is similar to the error that one would get in Counterpoint if TLS 1.2 was not enabled on a workstation, but I've confirmed that TLS 1.2 -is- enabled on the computer that is hosting the API, as well as the computer where the API call is being made from. I've also been able to successfully run credit cards through Secure Pay on both of these machines inside Ticket Entry without issue.

Below is the body of the POST request used that leads to the error above; I've masked out personally identifiable information as well as cardholder data, but rest assured that in reality, the data used is from a real, working credit card:

{
    "AR_CUST": {
        "NAM": "John Doe",
        "NAM_UPR": "JOHN DOE",
        "FST_NAM": "John",
        "FST_NAM_UPR": "JOHN",
        "LST_NAM": "Doe",
        "LST_NAM_UPR": "DOE",
        "CUST_TYP": "A",
        "ADRS_1": "1234 Main Street",
        "CITY": "Maintown",
        "STATE": "FL",
        "ZIP_COD": "33001",
        "CNTRY": "US",
        "PHONE_1": "(555) 123-4567",
        "CONTCT_1": "John Dow",
        "EMAIL_ADRS_1": "johndoe@gmail.com",
        "PROMPT_NAM_ADRS": "S",
        "SLS_REP": "TED",
        "CATEG_COD": "C",
        "SHIP_VIA_COD": "UPS",
        "SHIP_ZONE_COD": "R",
        "STR_ID": "1",
        "TAX_COD": "FL",
        "TERMS_COD": "10",
        "ALLOW_AR_CHRG": "N",
        "ALLOW_TKTS": "Y",
        "NO_CR_LIM": "Y",
        "NO_MAX_CHK_AMT": "Y",
        "UNPSTD_BAL": 0,
        "BAL_METH": "O",
        "AR_ACCT_NO": "1100",
        "BAL": 0,
        "ORD_BAL": 0,
        "NO_OF_ORDS": 0,
        "USE_ORD_SHIP_TO": "S",
        "ALLOW_ORDS": "Y",
        "LST_AGE_DAT": "2018-07-06T00:00:00.0000000",
        "LST_AGE_BAL": 0,
        "LST_AGE_BAL_1": 0,
        "LST_AGE_BAL_2": 0,
        "LST_AGE_BAL_3": 0,
        "LST_AGE_BAL_4": 0,
        "LST_AGE_BAL_5": 0,
        "LST_AGE_BAL_2_5": 0,
        "LST_AGE_BAL_3_5": 0,
        "LST_AGE_BAL_4_5": 0,
        "LST_AGE_BAL_OPN": 0,
        "LST_AGE_FUTR_DOCS": "N",
        "LST_AGE_METH": "I",
        "LST_AGE_AS_OF_DAT": "2018-07-06T00:00:00.0000000",
        "LST_AGE_MAX_PRD_1": 30,
        "LST_AGE_MAX_PRD_2": 60,
        "LST_AGE_MAX_PRD_3": 90,
        "LST_AGE_MAX_PRD_4": 120,
        "LST_AGE_NO_OF_PRDS": 5,
        "LST_AGE_EVENT_NO": "E-148391",
        "LST_AGE_NO_CUTOFF": "Y",
        "LST_AGE_PAST_CUTOFF": 0,
        "LST_AGE_NON_STD": "N",
        "LST_STMNT_METH": "!",
        "FST_SAL_DAT": "2015-08-19T00:00:00.0000000",
        "LST_SAL_DAT": "2018-05-21T00:00:00.0000000",
        "LST_SAL_AMT": 0.01,
        "PROF_COD_1": "ACTIVE",
        "PROF_COD_3": "N",
        "PROF_COD_4": "N",
        "PROF_COD_5": "N",
        "LST_MAINT_DT": "2015-08-18T17:31:58.0000000",
        "LST_MAINT_USR_ID": "JANE",
        "LST_LCK_DT": "2017-08-31T09:46:13.6370000",
        "WRK_STMNT_ACTIV": "N",
        "LWY_BAL": 0,
        "NO_OF_LWYS": 0,
        "USE_LWY_SHIP_TO": "S",
        "ALLOW_LWYS": "Y",
        "IS_ECOMM_CUST": "N",
        "DISC_PCT": 0,
        "ECOMM_NXT_PUB_UPDT": "N",
        "ECOMM_NXT_PUB_FULL": "Y",
        "ECOMM_LST_PUB_TYP": "!",
        "ECOMM_CREATED_CUST": "N",
        "ECOMM_LST_IMP_TYP": "!",
        "PROMPT_FOR_CUSTOM_FLDS": "N",
        "LOY_PTS_BAL": 0,
        "TOT_LOY_PTS_EARND": 0,
        "TOT_LOY_PTS_RDM": 0,
        "TOT_LOY_PTS_ADJ": 0,
        "REQ_PO_NO": "N",
        "RS_UTC_DT": "2018-07-06T18:31:48.2170000",
        "CUST_NAM_TYP": "P",
        "CUST_FST_LST_NAM": "Doe, John",
        "EMAIL_STATEMENT": "N",
        "RS_STAT": 1,
        "INCLUDE_IN_MARKETING_MAILOUTS": "N",
        "MARKETING_MAILOUT_OPT_IN_DAT": "2015-08-18T00:00:00.0000000",
        "RPT_EMAIL": "1",
        "AR_CUST_NOTE": [],
        "AR_SHIP_ADRS": [
            {
                "SHIP_ADRS_ID": "1",
                "SHIP_NAM_TYP": "P",
                "NAM": "John Doe",
                "NAM_UPR": "JOHN DOE",
                "FST_NAM": "John",
                "FST_NAM_UPR": "JOHN",
                "LST_NAM": "Doe",
                "LST_NAM_UPR": "DOE",
                "ADRS_1": "1234 Main Street",
                "CITY": "Maintown",
                "STATE": "FL",
                "ZIP_COD": "33001",
                "PHONE_1": "(555) 123-4567"
            }
        ],
        "AR_CUST_CARDS": [
			{
				"CARD_NO":***,
				"CARD_NAM":"John Doe",
				"CARD_EXP_DAT":"02-2021",
				"DEFAULT_CARD":"N",
				"PAY_COD":"VISA",
				"CARD_DESCR":***
			}
		],
    }
}

**Comment by MikeRitchie** [comment]
This will be addressed in an upcoming 2.1 release coming very soon. Date will be shared as soon as it is available.
