### ISSUE TITLE
re-open - Error When Adding a New Customer Using the POST /Customer Endpoint (Issue#60)

### ISSUE THREAD

**Issue by Bflatt** [NCRCounterpointAPI/APIGuide#131]
This is with API 2.1.243.0  and  8.4.6.19  

this is similar to the previous response but we have never had to include the workgroup as it is picked up from the store id in the put text.    It is only 8.5.2.0 or older where we have this problem. 

****  when I include sls_rep and cust_nam_typ it works 

where do we put the workgroup to let it use the template customer as with 8.5.2.1 or better?  

Bill

{
    "ErrorCode": "ERROR_UNKNOWN",
    "Message": "An error occurred during AddCustomer: No CUST_NO or valid workgroupID was supplied. If you need to auto-assign a CUST_NO, a valid \"Workgroup\" must be  passed in order to lookup the proper auto-assign numbering.\r\nParameter name: Workgroup,    at NCR.CP.CPAPI.Base.Business.CustomerBusiness.CPAPI.Common.ICustomerBusiness.AddCustomer(AR_CUST_POST customerEdit, String workgroupId)"

{
  "AR_CUST": {
    "NAM": "Superman",
    "FST_NAM": "Clark",
    "LST_NAM": "Kent",
    "STR_ID": "02",
    "AR_CUST_NOTE": [
      {
        "Note_ID": "ADDED_85",
        "NOTE_TXT": "Be careful, Clark Kent is Superman."
      }
    ],
    "AR_SHIP_ADRS": [
      {
        "SHIP_ADRS_ID": "ADDRESS_1",
        "NAM": "HOME",
        "SHIP_NAM_TYP": "B"
      },
      {
        "SHIP_ADRS_ID": "ADDRESS_2",
        "NAM": "WORK",
        "SHIP_NAM_TYP": "B"
      }
    ]
  }
}

**Comment by Bflatt** [comment]
I have tested an 8.5.2.1+ data set on the old API and the post cust above works without the Workgroup, cust_no, and SLS_rep.  With 2.1.243.0 we must include the extra fields as indicated below. So, this is a change the post format?  Could we get an updated format of where to put the "workgroup" in the post customer?  We would rather let Counterpoint create the customer numbers. 

 {
  "AR_CUST": {
  	"cust_no":"WEB-100003",
    "NAM": "Superman",
    "FST_NAM": "Clark",
    "LST_NAM": "Kent2",
    "STR_ID": "02",
    "SLS_REP":"MGR",
    "cust_nam_typ":"P",
    
    "AR_CUST_NOTE": [
      {
        "Note_ID": "ADDED_85",
        "NOTE_TXT": "Be careful, Clark Kent is Superman."
      }
    ],
    "AR_SHIP_ADRS": [
      {
        "SHIP_ADRS_ID": "ADDRESS_1",
        "NAM": "HOME",
        "SHIP_NAM_TYP": "B"
      },
      {
        "SHIP_ADRS_ID": "ADDRESS_2",
        "NAM": "WORK",
        "SHIP_NAM_TYP": "B"
      }
    ]
  }
}

**Comment by mbantug** [comment]
You should be able to include workgroup in the body of the request like this.  It will take that value first, and if that is not provided, it will fall back to the authenticated user's WRKGRP_ID.

The detail is on the Request Body section of this page (it was left out of the example): https://github.com/NCRCounterpointAPI/APIGuide/blob/master/Endpoints/POST_Customer.md

{
**"Workgroup": "1",**
"AR_CUST": {
"NAM": "Superman",
"FST_NAM": "Clark",
"LST_NAM": "Kent",
"STR_ID": "02",
"AR_CUST_NOTE": [
{
"Note_ID": "ADDED_85",
"NOTE_TXT": "Be careful, Clark Kent is Superman."
}
],
"AR_SHIP_ADRS": [
{
"SHIP_ADRS_ID": "ADDRESS_1",
"NAM": "HOME",
"SHIP_NAM_TYP": "B"
},
{
"SHIP_ADRS_ID": "ADDRESS_2",
"NAM": "WORK",
"SHIP_NAM_TYP": "B"
}
]
}
}

**Comment by Bflatt** [comment]
Thanks,  that did it.

Regards,

Bill
