### ISSUE TITLE
Errors with tickets using POST_Document

### ISSUE THREAD

**Issue by osain86** [NCRCounterpointAPI/APIGuide#14]
When we send an order to the API using the POST_Document endpoint, there's nothing coming out on the Drawer Summary Report for the drawer specified above neither on the Merchandise or the Non-Merchandise columns. Normally, since we are marking all lines as Special Order line types, there should be a Order Deposit Received line type under the Non-Merchandise column on that report that added to the Tax line (which is not showing either) should match the total Cash received.  On the Tender column, the cash received is displayed but it says the drawer is Over in balance.

```
{
    "PS_DOC_HDR":{
        "STR_ID":"WEBSITE",
        "STA_ID":"WEB-ST1",
        "DRW_ID":"WEB-DWR1",
        "TKT_TYP":"T",
        "DOC_TYP":"O",
        "USR_ID":"APIUSER",
        "TAX_COD":"WEB",
        "NORM_TAX_COD":"WEB",
        "PS_DOC_NOTE":[
            {
                "NOTE_ID":"NOTE_ID3",
                "NOTE":"So sorry we missed it. Love, customers"
            },
            {
                "NOTE_ID":"NOTE_ID4",
                "NOTE":"Product: CHRISTOFLE-38185 QTY: 11 Registry: J & G"
            }
        ],
        "BILL_TO_CONTACT":{
            "FST_NAM":"Ole",
            "LST_NAM":"Hl",
            "ADRS_1":"3603 Lane",
            "ADRS_2":"",
            "CITY":"Houston",
            "ZIP_COD":"77117",
            "STATE":"TX",
            "PHONE_1":"713-123-1234",
            "NAM_TYP":"P"
        },
        "SHIP_TO_CONTACT":{
            "FST_NAM":"J",
            "LST_NAM":"W",
            "ADRS_1":"9514 Drive",
            "ADRS_2":"",
            "CITY":"Houston",
            "ZIP_COD":"77104",
            "STATE":"TX",
            "PHONE_1":"713-123-1234",
            "NAM_TYP":"P"
        },
        "PS_DOC_LIN":[
            {
                "LIN_TYP":"P",
                "ITEM_NO":"CHRISTOFLE-38185",
                "PRC":"597",
                "USR_ENTD_PRC":"N",
                "QTY_SOLD":"1"
            },
            {
                "LIN_TYP":"P",
                "ITEM_NO":"EVENTS-SHIPPING",
                "PRC":"0",
                "USR_ENTD_PRC":"Y",
                "QTY_SOLD":1
            }
        ],
        "PS_DOC_PMT":[
            {
                "AMT":646.25,
                "PAY_COD":"WEB",
                "FINAL_PMT":"Y"
            }
        ],
        "PS_DOC_TAX":[
            {
                "AUTH_COD":"TX",
                "RUL_COD":"TAX",
                "TAX_DOC_PART":"O",
                "TAX_AMT":"49.25",
                "TOT_TXBL_AMT":"597"
            }
        ]
    }
}
```

**Comment by MikeRitchie** [comment]
Hello, we're still looking at this but had a question: 

What pay code type is "WEB" in Counterpoint? Typically, the FINAL_PMT flag is used to identify a credit card payment to charge any outstanding balance at a later time when the order is shipped. In that case, the AMT would be the amount (if any) to charge on the card for the deposit, as there is no AMT needed for the FINAL_PMT (since it will charge whatever the outstanding balace is). In your example above, it appears you are passing the full amount in with the payment, in which case there's no outstanding balance, and thus FINAL_PMT should be omitted (or set to "N").

If the desire is to immediately apply full payment to the WEB paycode, then I would omit FINAL_PMT, if the desire is to charge the balance of the order to the WEB paycode later, when the order ships, I would omit the AMT field.

**Comment by osain86** [comment]
"WEB" is a pay code of type CASH we are using to track sales from the website to an specific account other than the regular cash account we use for in-store sales. Since we want to apply full payment to the WEB paycode, we omitted the FINAL_PMT attribute on our Json call but we still can't see any balances on the Non-Merchandise column from the Drawer Summary Report for the website drawer.

**Comment by MikeRitchie** [comment]
FYI We're still looking at this. Do you have other calls that are showing up in the report? If so, some trial & error on the calls may help pin down a data element that is triggering the issue.

**Comment by osain86** [comment]
I was taking a deeper look inside the database structure because when I printed a Ticket History report for the drawer where we place all the transactions coming from the website, I realized that the column where is displayed the information about the activity in a ticket with order/special order lines is also empty ($0.00)

So I went into the table PS_ORD_HIST there's not a single entry reflecting the orders from any of the documents we submitted through the API. Any ideas what could be causing this?

**Comment by MikeRitchie** [comment]
For a Cash type paycode, the FINAL_PMT field should be "N". Final payment is used to save a credit card that will be charged at a later time when the order is released. Try changing that field and I expect everything will work as desired.

**Comment by MikeRitchie** [comment]
Closing per the comment above, if the information above doesn't resolve the issue, please reopen.
