### ISSUE TITLE
What is best practice to return a document(ticket or order)

### ISSUE THREAD

**Issue by hendrik-kim** [NCRCounterpointAPI/APIGuide#149]
I'm currently developing WooCommerce API & CounterPoint API integration program.

I've already known just deleting document is not recommended in CouterPoint system. 
Then, What is best practice to return a document(ticket or order) with CounterPoint API?

The first thought that came to my mind is make another ticket with same previous order but negative(-) amount of previous ticket.

Any other good way to make return/cancel function?

**Comment by GMHIGGINS** [comment]
hendrik-kim were you ever able to come up with a way to cancel or return a ticket?

**Comment by FroggyYT** [comment]
> I'm currently developing WooCommerce API & CounterPoint API integration program.
> 
> I've already known just deleting document is not recommended in CouterPoint system. Then, What is best practice to return a document(ticket or order) with CounterPoint API?
> 
> The first thought that came to my mind is make another ticket with same previous order but negative(-) amount of previous ticket.
> 
> Any other good way to make return/cancel function?

Could you possibly share how you were able to accomplish this?
