### ISSUE TITLE
Question: Posting Document returns ERROR_CUST_OVER_CR_LIMIT

### ISSUE THREAD

**Issue by joakim-emagine** [NCRCounterpointAPI/APIGuide#151]
Anyone else experience this issue, when using the API to create an Order?

```js
{
    "Documents": [
        {
            "DOC_ID": 0,
            "PaymentResponses": [
                {
                    "PMT_SEQ_NO": 0,
                    "Response": "ERROR_CUST_OVER_CR_LIMIT"
                }
            ]
        }
    ],
    "ErrorCode": "ERROR_AR_PAYMENT_FAILED",
    "Message": "One or more A/R payments have errors. See PaymentResponses for more details"
}
```

**Comment by GMHIGGINS** [comment]
The first thing to check is the credit limit of the customer for whom you are trying to create a document.

**Comment by joakim-emagine** [comment]
It’s for an new e-commerce order, initiated from a website. Would I need to create a new Customer via the api, then post the document?

**Comment by joakim-emagine** [comment]
Got this working by including a valid "CUST_NO". I think the documentation should be updated to show this.
