### ISSUE TITLE
Getting NullReferenceException when calling customers Api

### ISSUE THREAD

**Issue by frnkthtnk101** [NCRCounterpointAPI/APIGuide#159]
Im getting a 500 Internal Server Error with this response. First time using this system.

`{
  "ResponseStatus": {
    "ErrorCode": "NullReferenceException",
    "Message": "An error occurred while trying to access an object of type: UserRoles, Object value is null,    at NCR.CP.CPAPI.SDK.RepositoryCompanyBase.GetCacheKeyName(Object[] cacheKeyId)",
    "StackTrace": "   at NCR.CP.CPAPI.SDK.RepositoryCompanyBase.GetCacheKeyName(Object[] cacheKeyId)\r\n   at CPAPI.Common.KeyValueDataRepository.GetValueByName[T](String key)\r\n   at CPAPI.Common.UserRoleBusiness.CheckPermissions(String userId, String path, String verb)\r\n   at CPAPI.Common.RoleAttribute.Execute(IRequest req, IResponse res, Object requestDto)\r\n   at ServiceStack.RequestFilterAttribute.RequestFilter(IRequest req, IResponse res, Object requestDto)\r\n   at ServiceStack.ServiceStackHost.ApplyRequestFiltersSingle(IRequest req, IResponse res, Object requestDto)\r\n   at ServiceStack.ServiceStackHost.ApplyRequestFilters(IRequest req, IResponse res, Object requestDto)\r\n   at ServiceStack.Host.RestHandler.ProcessRequestAsync(IRequest httpReq, IResponse httpRes, String operationName)"
  }
}`

**Comment by GMHIGGINS** [comment]
Have you gone into the API Admin console to set up a Role and then assigned a valid UserID to it?

**Comment by frnkthtnk101** [comment]
Yes, we have a user called Z and is assigned a role

**Comment by frnkthtnk101** [comment]
I figured it out, The Customers.md file does not mention that the header APIKey is required.
