### ISSUE TITLE
Error Posting Document

### ISSUE THREAD

**Issue by mintile** [NCRCounterpointAPI/APIGuide#16]
I am testing with the DEMOGOLF DB and using the sample JSON below:
When I Send the POST I get an error stating that PS_DOC_PMT_RCPT.TRANS_TYP can't be null. 
(Full error below)

{
"PS_DOC_HDR": {
"STR_ID": "MAIN",
"STA_ID": "1",
"DRW_ID": "1",
"TKT_TYP": "T",
"DOC_TYP": "O",
"USR_ID": "MGR",
"PS_DOC_NOTE": [
{
"NOTE_ID": "TEST",
"NOTE": "This is a note!"
}
],
"PS_DOC_LIN": [
{
"LIN_TYP": "O",
"ITEM_NO": "ADM-SCD",
"PRC":"200",
"USR_ENTD_PRC":"Y",
"QTY_SOLD": "1.0"
}
],
"PS_DOC_PMT": [
{
"PAY_COD": "VISA",
"FINAL_PMT": "Y",
"PS_DOC_PMT_CR_CARD": {
"CR_CARD_NO": "4111111111111111",
"CR_CARD_NAM": "JOHN DOE",
"AVS_ZIP_COD": "12345",
"CR_CARD_EXP_DAT": "12/2018"
}
}
],
"PS_DOC_TAX": [
{
"AUTH_COD": "MEMPHIS",
"RUL_COD": "TAX",
"TAX_DOC_PART": "O",
"LIN_AMT": "200",
"TXBL_LIN_AMT": "200",
"TXBL_QTY": "1.00",
"TAX_AMT": "4.00",
"TOT_TXBL_AMT": "200"
},
{
"AUTH_COD": "SHELBY",
"RUL_COD": "TAX",
"TAX_DOC_PART": "O",
"LIN_AMT": "200",
"TXBL_LIN_AMT": "200",
"TXBL_QTY": "1.00",
"TAX_AMT": "6.00",
"TOT_TXBL_AMT": "200"
},
{
"AUTH_COD": "TN",
"RUL_COD": "TAX",
"TAX_DOC_PART": "O",
"LIN_AMT": "200",
"TXBL_LIN_AMT": "200",
"TXBL_QTY": "1.00",
"TAX_AMT": "6.00",
"TOT_TXBL_AMT": "200"
}
]
}
}

Results (Error):

{
  "Documents": [],
  "ErrorCode": "ERROR_UNKNOWN",
  "Message": "An error occurred during AddDocument POST: Cannot insert the value NULL into column 'TRANS_TYP', table 'DEMOGOLF85.dbo.PS_DOC_PMT_RCPT'; column does not allow nulls. INSERT fails.\r\nThe statement has been terminated.,    at System.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)\r\n   at System.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose)\r\n   at System.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady)\r\n   at System.Data.SqlClient.SqlCommand.FinishExecuteReader(SqlDataReader ds, RunBehavior runBehavior, String resetOptionsString, Boolean isInternal, Boolean forDescribeParameterEncryption)\r\n   at System.Data.SqlClient.SqlCommand.RunExecuteReaderTds(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, Boolean async, Int32 timeout, Task& task, Boolean asyncWrite, Boolean inRetry, SqlDataReader ds, Boolean describeParameterEncryptionRequest)\r\n   at System.Data.SqlClient.SqlCommand.RunExecuteReader(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, String method, TaskCompletionSource`1 completion, Int32 timeout, Task& task, Boolean& usedCache, Boolean asyncWrite, Boolean inRetry)\r\n   at System.Data.SqlClient.SqlCommand.InternalExecuteNonQuery(TaskCompletionSource`1 completion, String methodName, Boolean sendToPipe, Int32 timeout, Boolean& usedCache, Boolean asyncWrite, Boolean inRetry)\r\n   at System.Data.SqlClient.SqlCommand.ExecuteNonQuery()\r\n   at ServiceStack.OrmLite.OrmLiteWriteCommandExtensions.Insert[T](IDbCommand dbCmd, T obj, Boolean selectIdentity)\r\n   at ServiceStack.OrmLite.OrmLiteExecFilter.Exec[T](IDbConnection dbConn, Func`2 filter)\r\n   at CPAPI.Repositories_85.DocumentRepository_85.CPAPI.Repositories_85.IDocumentRepository.AddDocument(PS_DOC_HDR document)\r\n   at CPAPI.Business_85.DocumentBusiness_85.PrepareAndSaveOrder(PS_DOC_HDR document, PS_TAX tax, DocumentKey OrderKey, DocumentKey TicketKey, Boolean MultipleDocs)\r\n   at CPAPI.Business_85.DocumentBusiness_85.SplitMixedDocumentAndSave(PS_DOC_HDR document, PS_TAX tax, IM_CTL itemControl)\r\n   at CPAPI.Business_85.DocumentBusiness_85.SaveMixedDocument(PS_DOC_HDR document, PS_TAX tax)\r\n   at CPAPI.Business_85.DocumentBusiness_85.AddDocument(PS_DOC_HDR_POST documentPost, PS_TAX_VIEW taxView, String workgroup)"
}

**Comment by MikeRitchie** [comment]
The PS_DOC_PMT_RCPT table is filled out with the result of the payment. In this case, it looks like we should just be tokenizing the card for later final payment. If you add an AMT to the payment, that is less than the total (just a dollar), Does the transaction work?

Also, can you verify your MAIN store has a valid, working Secure Pay configuration? I believe you'd get a different error if not, but worth checking.

**Comment by mintile** [comment]
This is just a test environment so the SecurePay is not configured. I was trying to add Final Payments for credit cards. If I change the payment to a cash paycode or remove the payment remove the payment all together it works. Is there any way to test or simulate final payments for credit cards without using a real SecurePay setup? I'm going to want to test my app and don't really want to keep hitting the SecurePay servers. Although, if that's the only way to do it and it's OK to test against SecurePay I will do that.

**Comment by MikeRitchie** [comment]
As a partner I believe you're able to get a loopback Secure Pay account that you can use. In that setup you'd hit the real secure pay server, but as a loopback account it wouldn't go to an end processor. The error is likely due to the inability for the API to tokenize the credit card.

**Comment by mintile** [comment]
OK. That works. I think our tech department has a loopback account.
