### ISSUE TITLE
API calls failing.

### ISSUE THREAD

**Issue by cyrusbaratt** [NCRCounterpointAPI/APIGuide#17]
Hello:

I am getting the following errors when using this Web site:

https://xyz:52000/login?redirect=https%3a%2f%2fcyruslaptop%3a52000%2fcustomer%2f1001

Handler for Request not found (404):

  Request.HttpMethod: GET
  Request.PathInfo: /login
  Request.QueryString: redirect=https%3a%2f%2fxyz%3a52000%2fcustomer%2f1001
  Request.RawUrl: /login?redirect=https%3a%2f%2fxyz%3a52000%2fcustomer%2f1001

Or 

From postman software:

Could not get any response
There was an error connecting to https://xyz:52000/Customer/1001.

Could you please provide any guidance?  API and CounterPoint are on different computers per your guidelines in the past.

Thank you and regards

Cyrus Baratt

**Comment by MikeRitchie** [comment]
This typically means the request you are sending isn't making it to the API server. This could be for a few reasons:
* The API server isn't running or has encountered some type of issue: In this case go into the windows services console (services.msc) and ensure the "NCR Counterpoint API" service is running. If it is running, try restarting it.
* There could be an issue with the certificate, or a port conflict: Make sure no other application or service is listnening on the port, and you may also want to check that the SSL certificate is properly bound to port 52000. See this page for information on checking the SSL bindings: https://github.com/NCRCounterpointAPI/APIGuide/blob/master/InstallationAndConfiguration/Installing.md
This MSDN page is referenced, which has good information on how to check bindings:
https://msdn.microsoft.com/en-us/library/ms733791(v=vs.110).aspx

Alternatively, you could try hosting the API on another port by editing the CPAPIConsole.exe.config file to change the port number (then restart the service). Be sure you have a valid SSL certificate bound to the new port as well.

**Comment by MikeRitchie** [comment]
Also, did this site ever work? If so, any notable changes (reboot, software installs, config changes, etc.) between when it worked and when it broke?

**Comment by MikeRitchie** [comment]
Could you please provide a status update on this issue per the previous post?

**Comment by cyrusbaratt** [comment]
Hello,

Checking this site and other sites to find the solution for my access issues:

https://servicestack.net

Regards

Cyrus Baratt
972-991-8162 Ext. 104
[TIS-Email-Logo]
[NCR-CP-Logo]
15851 Dallas Parkway,
Suite 600
Addison, TX 75001

**Comment by MikeRitchie** [comment]
Re-reading through this, have you checked to ensure this isn't the same as this issue?
https://github.com/NCRCounterpointAPI/APIGuide/issues/2
If this is a new API install on a machine without Counterpoint, and you are getting a 404 on the login page this is likely it.

**Comment by cyrusbaratt** [comment]
Apologies Mike,

I have been busy with other things.  I could use some help with using all these different interfaces.


·         I am learning to use “CURL”.

·         Postman is not working still with unknown connection message.

Could you please let me know if there is a hand-on class Web course?

Regards,

Cyrus Baratt
972-991-8162 Ext. 104
[TIS-Email-Logo]
[NCR-CP-Logo]
15851 Dallas Parkway,
Suite 600
Addison, TX 75001

**Comment by MikeRitchie** [comment]
As a free service, there is no training NCR provides on cURL or other high level Rest API development.  We do follow industry standard Rest API conventions so there are numerous other online resources related to Rest API's that should be directly applicable to the Counterpoint API.
