### ISSUE TITLE
Loyalty related glossary question

### ISSUE THREAD

**Issue by Nepherhotep** [NCRCounterpointAPI/APIGuide#18]
Hey, there are plenty of fields related to loyalty in Customer structure https://github.com/NCRCounterpointAPI/APIGuide/blob/master/Endpoints/GET_Customers.md, despite the names in most cases are quite descriptive, I'm not 100% sure what they exactly mean. I really appreciate if you can describe their meanings, the fields listed below:

>   "LOY_PGM_COD": "LOYAL-1",
>       "LOY_PTS_BAL": 19701,
>       "TOT_LOY_PTS_EARND": 9862,
>       "TOT_LOY_PTS_RDM": 162,
>       "TOT_LOY_PTS_ADJ": 10001,
>       "LST_LOY_PTS_EARN": 315,
>       "LST_LOY_EARN_TKT_NO": "102370",
>       "LST_LOY_RDM_TKT_DAT": "2016-07-13T00:00:00.0000000",
>       "LST_LOY_RDM_TKT_TIM": "1899-12-30T10:41:00.0000000",
>        "LST_LOY_PTS_RDM": 162,
>       "LST_LOY_RDM_TKT_NO": "102249",
>       "LST_LOY_ADJ_DAT": "2016-07-13T00:00:00.0000000",
>       "LST_LOY_PTS_ADJ": 1,
>       "LOY_CARD_NO": "321-455-1836",
>       "LST_LOY_EARN_TKT_DAT": "2016-10-17T00:00:00.0000000", 
>       "LST_LOY_EARN_TKT_TIM": "1899-12-30T09:55:18.0000000",  
>       "LST_LOY_EARN_TKT_DT": "2016-10-17T09:55:18.0000000",
>       "LST_LOY_RDM_TKT_DT": "2016-07-13T10:41:00.0000000",

Thanks in advance,
Alexey

**Comment by MikeRitchie** [comment]
Hello,
Below i've included information from the column description report within Counterpoint, for the entire AR_CUST table. It's not as descriptive as I'd like, but it does give some more detail. You can access this from Counterpoint for any table via System>Utilities>Column Description Report.

Hopefully this gives you enough information to move forward, if there are any in particular you need more detail on please let us know.

---
Column name                    Display label                  
------------------------------ ------------------------------ 

CUST_NO                        Customer #                     
NAM                            Name                           
NAM_UPR                        Name (upper)                   
FST_NAM                        First name                     
FST_NAM_UPR                    First name (upper)             
LST_NAM                        Last name                      
LST_NAM_UPR                    Last name (upper)              
SALUTATION                     Salutation                     
CUST_TYP                       Customer type                  
ADRS_1                         Address 1                      
ADRS_2                         Address 2                      
ADRS_3                         Address 3                      
CITY                           City                           
STATE                          State                          
ZIP_COD                        Zip code                       
CNTRY                          Country                        
PHONE_1                        Phone 1                        
PHONE_2                        Phone 2                        
FAX_1                          Fax 1                          
FAX_2                          Fax 2                          
CONTCT_1                       Contact 1                      
CONTCT_2                       Contact 2                      
EMAIL_ADRS_1                   Email 1                        
EMAIL_ADRS_2                   Email 2                        
URL_1                          URL 1                          
URL_2                          URL 2                          
PROMPT_NAM_ADRS                Prompt for address             
SLS_REP                        Sales rep                      
CATEG_COD                      Category                       
SHIP_VIA_COD                   Ship-via code                  
SHIP_ZONE_COD                  Shipping zone                  
STR_ID                         Store                          
STMNT_COD                      Statement code                 
TAX_COD                        Tax code                       
TERMS_COD                      Terms code                     
COMMNT                         Comment                        
TAX_EXEMPT_NO                  Tax exempt number              
TAX_EXEMPT_DAT                 Tax exemption date             
ALLOW_AR_CHRG                  Allow A/R charges              
ALLOW_TKTS                     Allow tickets                  
NO_CR_LIM                      Unlimited                      
CR_LIM                         Credit limit                   
CR_RATE                        Credit rating                  
NO_MAX_CHK_AMT                 Unlimited checks               
MAX_CHK_AMT                    Max check amt                  
UNPSTD_BAL                     Unposted bal                   
BAL_METH                       Balance method                 
AR_ACCT_NO                     A/R account                    
BAL                            Balance                        
ORD_BAL                        Order balance                  
NO_OF_ORDS                     Number of orders               
USE_ORD_SHIP_TO                Prompt for order ship-to       
ALLOW_ORDS                     Allow orders                   
LST_AGE_DAT                    Last aged on                   
LST_AGE_BAL                    Last aging balance             
LST_AGE_BAL_1                  Last aging balance 1           
LST_AGE_BAL_2                  Last aging balance 2           
LST_AGE_BAL_3                  Last aging balance 3           
LST_AGE_BAL_4                  Last aging balance 4           
LST_AGE_BAL_5                  Last aging balance 5           
LST_AGE_BAL_2_5                Sum of last aging balances 2 t 
LST_AGE_BAL_3_5                Sum of last aging balances 3 t 
LST_AGE_BAL_4_5                Sum of last aging balances 4 & 
LST_AGE_BAL_OPN                Open                           
LST_AGE_FUTR_DOCS              Future docs                    
LST_AGE_METH                   Aged by                        
LST_AGE_AS_OF_DAT              Last age as of date            
LST_AGE_CUTOFF_DAT             Last age cutoff date           
LST_AGE_MAX_PRD_1              Max age for period 1           
LST_AGE_MAX_PRD_2              Max age for period 2           
LST_AGE_MAX_PRD_3              Max age for period 3           
LST_AGE_MAX_PRD_4              Max age for period 4           
LST_AGE_NO_OF_PRDS             Last aging number of periods   
LST_AGE_EVENT_NO               Last aging event number        
LST_AGE_NO_CUTOFF              Last age no cutoff             
LST_AGE_PAST_CUTOFF            Past cutoff                    
LST_AGE_NON_STD                Last aging non-standard        
LST_STMNT_DAT                  Printed on                     
LST_STMNT_BAL                  Last stmnt balance             
LST_STMNT_BAL_1                Last stmnt balance 1           
LST_STMNT_BAL_2                Last stmnt balance 2           
LST_STMNT_BAL_3                Last stmnt balance 3           
LST_STMNT_BAL_4                Last stmnt balance 4           
LST_STMNT_BAL_5                Last stmnt balance 5           
LST_STMNT_BAL_2_5              Sum of last stmnt balances 2 t 
LST_STMNT_BAL_3_5              Sum of last stmnt balances 3 t 
LST_STMNT_BAL_4_5              Sum of last stmnt balances 4 & 
LST_STMNT_BAL_OPN              Last stmnt balance open        
LST_STMNT_METH                 Aged by                        
LST_STMNT_BEG_DAT              Last statement period beginnin 
LST_STMNT_END_DAT              Last statement period ending d 
LST_STMNT_MAX_PRD_1            Max age for period 1           
LST_STMNT_MAX_PRD_2            Max age for period 2           
LST_STMNT_MAX_PRD_3            Max age for period 3           
LST_STMNT_MAX_PRD_4            Max age for period 4           
LST_STMNT_NO_OF_PRDS           Last statement number of aging 
LST_STMNT_PAST_CTOFF           Last stmnt balance past cutoff 
FST_SAL_DAT                    First sale date                
LST_SAL_DAT                    Last sale date                 
LST_SAL_AMT                    Last sale amt                  
LST_PMT_DAT                    Last pmt date                  
LST_PMT_AMT                    Last pmt amt                   
PROF_ALPHA_1                   Alpha profile 1                
PROF_ALPHA_2                   Alpha profile 2                
PROF_ALPHA_3                   Alpha profile 3                
PROF_ALPHA_4                   Alpha profile 4                
PROF_ALPHA_5                   Alpha profile 5                
PROF_COD_1                     Code profile 1                 
PROF_COD_2                     Code profile 2                 
PROF_COD_3                     Code profile 3                 
PROF_COD_4                     Code profile 4                 
PROF_COD_5                     Code profile 5                 
PROF_DAT_1                     Date profile 1                 
PROF_DAT_2                     Date profile 2                 
PROF_DAT_3                     Date profile 3                 
PROF_DAT_4                     Date profile 4                 
PROF_DAT_5                     Date profile 5                 
PROF_NO_1                      Numeric profile 1              
PROF_NO_2                      Numeric profile 2              
PROF_NO_3                      Numeric profile 3              
PROF_NO_4                      Numeric profile 4              
PROF_NO_5                      Numeric profile 5              
LST_MAINT_DT                   Last maintained                
LST_MAINT_USR_ID               Last maintained by             
LST_LCK_DT                     Last lock                      
ROW_TS                         Row timestamp                  
WRK_STMNT_ACTIV                Apply-to# activity in period   
LWY_BAL                        Layaway balance                
NO_OF_LWYS                     Number of layaways             
USE_LWY_SHIP_TO                Prompt for layaway ship-to     
ALLOW_LWYS                     Allow layaways                 
IS_ECOMM_CUST                  Ecommerce customer             
ECOMM_CUST_NO                  CPOL customer #                
ECOMM_AFFIL_COD                Affiliate                      
DISC_PCT                       Discount %                     
ECOMM_INIT_PWD                 Initial password               
ECOMM_NXT_PUB_UPDT             Needs balance update           
ECOMM_NXT_PUB_FULL             Needs full update              
ECOMM_LST_PUB_DT               Last published                 
ECOMM_LST_PUB_TYP              Last publishing mode           
ECOMM_LST_IMP_DT               Last imported                  
ECOMM_CREATED_CUST             Created by import              
ECOMM_LST_ORD_NO               Last online order              
ECOMM_LST_ORD_DT               Order date                     
ECOMM_LST_IMP_TYP              Import type                    
ECOMM_LST_IMP_EVENT_NO         Event number                   
PROMPT_FOR_CUSTOM_FLDS         Prompt for custom fields       
LOY_PGM_COD                    Loyalty program                
LOY_PTS_BAL                    Loyalty points balance         
TOT_LOY_PTS_EARND              Total loyalty points earned    
TOT_LOY_PTS_RDM                Total loyalty points redeemed  
TOT_LOY_PTS_ADJ                Total points adjusted          
LST_LOY_EARN_TKT_DAT           Last earning date              
LST_LOY_EARN_TKT_TIM           Last earning time              
LST_LOY_PTS_EARN               Last points earned             
LST_LOY_EARN_TKT_NO            Last earning ticket number     
LST_LOY_RDM_TKT_DAT            Last redemption date           
LST_LOY_RDM_TKT_TIM            Last redemption time           
LST_LOY_PTS_RDM                Last points redeemed           
LST_LOY_RDM_TKT_NO             Last redemption ticket no      
LST_LOY_ADJ_DAT                Last points adjustment         
LST_LOY_PTS_ADJ                Last points adjustment qty     
LST_LOY_ADJ_DOC_NO             Last points adjustment doc #   
LOY_CARD_NO                    Loyalty card #                 
FCH_COD                        Fin charge code                
LST_FCH_DAT                    Last fin chrg date             
LST_FCH_AMT                    Last fin chrg amt              
LST_FCH_PAST_DUE_AMT           Last finance charge past due a 
LST_FCH_DOC_NO                 Last finance charge doc #      
REQ_PO_NO                      Require PO number              
RS_UTC_DT                      DataSync datetime              
CUST_NAM_TYP                   Name type                      
CUST_FST_LST_NAM               Last, First Name               
LST_LOY_EARN_TKT_DT            Last earning date/time         
LST_LOY_RDM_TKT_DT             Last redemption date/time      
PS_HDR_CUST_FLD_FRM_ID         Ticket custom prompts          
EMAIL_STATEMENT                Send statement as e-mail       
RS_STAT                        DataSync replication status    
INCLUDE_IN_MARKETING_MAILOUTS  Opt-out from marketing emails  
MARKETING_MAILOUT_OPT_IN_DAT   As of                          
RPT_EMAIL                      Reports/receipts e-mail        
MBL_PHONE_1                    Mobile phone 1                 
MBL_PHONE_2                    Mobile phone 2

**Comment by Nepherhotep** [comment]
That's helpful, thanks
