### ISSUE TITLE
Item/Inventory glossary questions

### ISSUE THREAD

**Issue by Nepherhotep** [NCRCounterpointAPI/APIGuide#19]
Hey @MikeRitchie could you please provide description of inventory and item structures similarly to provided previously customer structure?

Item:

> {
>   "IM_INV": {
>     "ITEM_NO": "ADM-SCD",
>     "LOC_ID": "EAST",
>     "MIN_QTY": 0,
>     "MAX_QTY": 0,
>     "QTY_COMMIT": -1,
>     "QTY_ON_HND": 3,
>     "QTY_ON_PO": 0,
>     "QTY_ON_BO": 0,
>     "QTY_ON_XFER_OUT": 0,
>     "QTY_ON_XFER_IN": 0,
>     "LST_COST": 0,
>     "COST_OF_SLS_PCT": 0,
>     "GL_VAL": 811.79,
>     "LST_LCK_DT": "2008-07-30T07:48:32.7500000",
>     "QTY_ON_ORD": 0,
>     "QTY_ON_LWY": 0,
>     "QTY_ON_SO": 0,
>     "RS_UTC_DT": "2012-07-16T16:53:42.0100000",
>     "NET_QTY": 4,
>     "QTY_AVAIL": 4,
>     "STK_STAT_PER_QTY_ON_HND": "?",
>     "STK_STAT_PER_QTY_AVAIL": "?",
>     "STK_STAT_PER_NET_QTY": "?",
>     "RS_STAT": 0,
>     "DROPSHIP_QTY_ON_CUST_ORD": 0,
>     "DROPSHIP_QTY_ON_PO": 0,
>     "IM_INV_CELL": []
>   },
>   "ErrorCode": "SUCCESS"
> }

Inventory:

> {
>   "IM_ITEM": {
>     "ITEM_NO": "ADM-SCD",
>     "DESCR": "Adams SC Driver, RH",
>     "DESCR_UPR": "ADAMS SC DRIVER, RH",
>     "LONG_DESCR": "Adams SC Driver, RH",
>     "LONG_DESCR_UPR": "ADAMS SC DRIVER, RH",
>     "SHORT_DESCR": "Adams SC Driver",
>     "ADDL_DESCR_1": "Adams exclusive Spin Control Technology",
>     "ADDL_DESCR_2": "Uses a proprietary stainless steel casting process",
>     "ADDL_DESCR_3": "Keeps ball on target and produces greater distance",
>     "ITEM_TYP": "I",
>     "CATEG_COD": "GOLF",
>     "SUBCAT_COD": "CLUBS",
>     "ACCT_COD": "1",
>     "ATTR_COD_1": "RIGHTHAND",
>     "ATTR_COD_2": "STSTEEL",
>     "TRK_METH": "N",
>     "STAT": "A",
>     "STAT_DAT": "2000-02-02T00:00:00.0000000",
>     "IS_TXBL": "Y",
>     "QTY_DECS": 0,
>     "PRC_DECS": 2,
>     "STK_UNIT": "EACH",
>     "ITEM_VEND_NO": "ADAMS",
>     "IS_WEIGHED": "N",
>     "PREF_UNIT": "0",
>     "PROMPT_FOR_PRC": "N",
>     "PROMPT_FOR_COST": "N",
>     "PROMPT_FOR_DESCR": "N",
>     "WARR_UNIT_1": "D",
>     "WARR_UNIT_2": "D",
>     "SER_NO_REQ_FOR_SAL": "N",
>     "GRID_ENT_1": 1,
>     "GRID_ENT_2": 2,
>     "GRID_ENT_3": 3,
>     "PRC_1": 399.99,
>     "BARCOD": "1",
>     "IS_ECOMM_ITEM": "Y",
>     "ECOMM_LST_PUB_STAT": "I",
>     "ECOMM_TXBL_1": "N",
>     "ECOMM_TXBL_2": "N",
>     "ECOMM_TXBL_3": "N",
>     "ECOMM_NEW": "N",
>     "ECOMM_ON_SPECL": "C",
>     "ECOMM_CHRG_FRT": "N",
>     "LST_MAINT_DT": "2012-07-16T14:56:16.0000000",
>     "LST_MAINT_USR_ID": "MGR",
>     "LST_LCK_DT": "2000-07-27T20:10:35.0000000",
>     "DFLT_COST_OF_SLS_PCT": 0,
>     "REG_PRC": 399.99,
>     "LST_COST": 159.996,
>     "LST_RECV_DAT": "2007-10-27T00:00:00.0000000",
>     "IS_FOOD_STMP_ITEM": "N",
>     "PROMPT_FOR_UNIT": "N",
>     "PROMPT_FOR_CUSTOM_FLDS": "N",
>     "MIX_MATCH_COD": "CLUBDEAL",
>     "IS_ADM_TKT": "N",
>     "RS_UTC_DT": "2012-07-16T18:56:16.5300000",
>     "IS_BOM_PAR": "N",
>     "IS_KIT_PAR": "N",
>     "CATEG_SUBCAT": "GOLF/CLUBS",
>     "DIM_COUNT": 0,
>     "PREF_UNIT_DENOM": 1,
>     "PREF_UNIT_NAM": "EACH",
>     "PREF_UNIT_NUMER": 1,
>     "PREF_UNIT_PRC_1": 399.99,
>     "PREF_UNIT_REG_PRC": 399.99,
>     "ITEM_IS_MISC": "N",
>     "BARCOD_3_OF_9": "*1*",
>     "IS_DISCNTBL": "Y",
>     "ECOMM_DISC_ON_SAL": "Y",
>     "ECOMM_ITEM_IS_DISCNTBL": "Y",
>     "RS_STAT": 0,
>     "IM_ITEM_NOTE": [],
>     "EC_ITEM_DESCR": {
>       "ITEM_NO": "ADM-SCD",
>       "HTML_DESCR": "<B>Adams</B> exclusive <B>Spin Control Technology</B>.\r\nUses a proprietary stainless steel casting process.\r\nKeeps ball on target and produces greater distance.\r\n\r\n",
>       "LST_MAINT_DT": "2002-09-24T19:11:45.0000000",
>       "LST_MAINT_USR_ID": "Z"
>     }    
>   },
>   "ErrorCode": "SUCCESS"
> }
> 

Thanks.

**Comment by MikeRitchie** [comment]
Below is information for IM_INV & IM_ITEM:


Table [IM_INV] (description "Inventory")

This table contains inventory records.  Inventory records indicate which items 
are stocked (available for sale) from each location.

Column name                    Display label                  
------------------------------ ------------------------------ 

ITEM_NO                        Item number                    
LOC_ID                         Location                       
BIN_1                          Bin-1                          
BIN_2                          Bin-2                          
BIN_3                          Bin-3                          
BIN_4                          Bin-4                          
MIN_QTY                        Min qty                        
MAX_QTY                        Max qty                        
QTY_COMMIT                     Qty committed                  
QTY_ON_HND                     Qty on hand                    
QTY_ON_PO                      Qty on PO's                    
QTY_ON_BO                      Qty on BO                      
QTY_ON_XFER_OUT                Qty on transfer out            
QTY_ON_XFER_IN                 Qty on transfer in             
LST_AVG_COST                   Last avg cost                  
LST_COST                       Last cost                      
STD_COST                       Standard cost                  
COST_OF_SLS_PCT                Cost of sales percent          
FST_RECV_DAT                   First recv date                
LST_RECV_DAT                   Last recv date                 
FST_SAL_DAT                    First sale date                
LST_SAL_DAT                    Last sale date                 
LST_CNT_DAT                    Last count date                
LST_ORD_DAT                    Last PO date                   
NXT_EXPECTD_DAT                Next expected date             
NXT_EXPECTD_PO                 Next expected PO               
GL_VAL                         G/L value                      
LST_MAINT_DT                   Last maintained                
LST_MAINT_USR_ID               Last maintained by             
LST_LCK_DT                     Last lock                      
ROW_TS                         Row timestamp                  
QTY_ON_ORD                     Qty on order                   
QTY_ON_LWY                     Qty on layaway                 
QTY_ON_SO                      Qty on SO                      
RS_UTC_DT                      DataSync datetime              
AVG_COST                       Average cost                   
NET_QTY                        Net quantity                   
QTY_AVAIL                      Qty available                  
STK_STAT_PER_QTY_ON_HND        Stock status per qty on hnd    
STK_STAT_PER_QTY_AVAIL         Stock status per qty avail     
STK_STAT_PER_NET_QTY           Stock status per net qty       
REORD_PNT                      Reorder point                  
EOQ                            EOQ                            
SFTY_STK                       Safety stock                   
SRVC_LEVL                      Service level (future)         
ANNL_HLD_COST                  Annual holding cost amount     
ANNL_HLD_COST_PERC             Annual holding cost percentage 
ORD_COST_PER_ORDER             Ordering cost per order        
EOQ_CALC_ON                    EOQ calculated on              
RS_STAT                        DataSync replication status    
DROPSHIP_QTY_ON_CUST_ORD       Qty on drop-ship cust orders   
DROPSHIP_QTY_ON_PO             Qty on drop-ship PO            
================================================================================

Table [IM_ITEM] (description "Item")

This table contains items - goods and services you have for sale.

Column name                    Display label                  
------------------------------ ------------------------------ 

ITEM_NO                        Item number                    
DESCR                          Description                    
DESCR_UPR                      Description (upper)            
LONG_DESCR                     Long description               
LONG_DESCR_UPR                 Long description (upper)       
SHORT_DESCR                    Short description              
ADDL_DESCR_1                   Additional description 1       
ADDL_DESCR_2                   Additional description 2       
ADDL_DESCR_3                   Additional description 3       
ITEM_TYP                       Item type                      
CATEG_COD                      Category                       
SUBCAT_COD                     Sub-category                   
ACCT_COD                       Account code                   
LBL_COD                        Label code                     
ATTR_COD_1                     Item attribute 1               
ATTR_COD_2                     Item attribute 2               
ATTR_COD_3                     Item attribute 3               
ATTR_COD_4                     Item attribute 4               
ATTR_COD_5                     Item attribute 5               
ATTR_COD_6                     Item attribute 6               
TRK_METH                       Tracking method                
STAT                           Status                         
STAT_DAT                       Status date                    
IS_TXBL                        Taxable                        
QTY_DECS                       Qty decimals                   
PRC_DECS                       Price decimals                 
STK_UNIT                       Stocking unit                  
ITEM_VEND_NO                   Primary vendor                 
WEIGHT                         Weight                         
TARE_COD                       Tare weight code               
CUBE                           Cube                           
IS_WEIGHED                     Weighed                        
ALT_1_UNIT                     Alt-1 unit                     
ALT_1_NUMER                    Alt-1 multiply by              
ALT_1_DENOM                    Alt-1 divide by                
ALT_1_WEIGHT                   Alt-1 weight                   
ALT_1_CUBE                     Alt-1 cube                     
ALT_1_PRC_1                    Alt-1 price-1                  
ALT_2_UNIT                     Alt-2 unit                     
ALT_2_NUMER                    Alt-2 multiply by              
ALT_2_DENOM                    Alt-2 divide by                
ALT_2_WEIGHT                   Alt-2 weight                   
ALT_2_CUBE                     Alt-2 cube                     
ALT_2_PRC_1                    Alt-2 price-1                  
ALT_3_UNIT                     Alt-3 unit                     
ALT_3_NUMER                    Alt-3 multiply by              
ALT_3_DENOM                    Alt-3 divide by                
ALT_3_WEIGHT                   Alt-3 weight                   
ALT_3_CUBE                     Alt-3 cube                     
ALT_3_PRC_1                    Alt-3 price-1                  
ALT_4_UNIT                     Alt-4 unit                     
ALT_4_NUMER                    Alt-4 multiply by              
ALT_4_DENOM                    Alt-4 divide by                
ALT_4_WEIGHT                   Alt-4 weight                   
ALT_4_CUBE                     Alt-4 cube                     
ALT_4_PRC_1                    Alt-4 price-1                  
ALT_5_UNIT                     Alt-5 unit                     
ALT_5_NUMER                    Alt-5 multiply by              
ALT_5_DENOM                    Alt-5 divide by                
ALT_5_WEIGHT                   Alt-5 weight                   
ALT_5_CUBE                     Alt-5 cube                     
ALT_5_PRC_1                    Alt-5 price-1                  
PREF_UNIT                      Preferred unit                 
PROMPT_FOR_PRC                 Prompt for price               
PROMPT_FOR_COST                Prompt for cost                
PROMPT_FOR_DESCR               Prompt for description         
WARR_PRD_1                     Warranty period 1              
WARR_UNIT_1                    Unit (Disp)                    
WARR_PRD_2                     Warranty period 2              
WARR_UNIT_2                    Unit                           
SER_NO_REQ_FOR_SAL             Required when selling/returnin 
SER_PROMPT_COD_1               Serial prompt 1 code           
SER_PROMPT_COD_2               Serial prompt 2 code           
SER_PROMPT_COD_3               Serial prompt 3 code           
PROF_ALPHA_1                   Alpha profile 1                
PROF_ALPHA_2                   Alpha profile 2                
PROF_ALPHA_3                   Alpha profile 3                
PROF_ALPHA_4                   Alpha profile 4                
PROF_ALPHA_5                   Alpha profile 5                
PROF_COD_1                     Code profile 1                 
PROF_COD_2                     Code profile 2                 
PROF_COD_3                     Code profile 3                 
PROF_COD_4                     Code profile 4                 
PROF_COD_5                     Code profile 5                 
PROF_DAT_1                     Date profile 1                 
PROF_DAT_2                     Date profile 2                 
PROF_DAT_3                     Date profile 3                 
PROF_DAT_4                     Date profile 4                 
PROF_DAT_5                     Date profile 5                 
PROF_NO_1                      Numeric profile 1              
PROF_NO_2                      Numeric profile 2              
PROF_NO_3                      Numeric profile 3              
PROF_NO_4                      Numeric profile 4              
PROF_NO_5                      Numeric profile 5              
GRID_DIM_1_TAG                 Grid dimension &1 tag          
GRID_DIM_2_TAG                 Grid dimension &2 tag          
GRID_DIM_3_TAG                 Grid dimension &3 tag          
GRID_DIM_1_TAG_UPR             Grid dimension &1 tag          
GRID_DIM_2_TAG_UPR             Grid dimension &2 tag          
GRID_DIM_3_TAG_UPR             Grid dimension &3 tag          
GRID_ENT_1                     Grid dimension 1 entry order   
GRID_ENT_2                     Grid dimension 2 entry order   
GRID_ENT_3                     Grid dimension 3 entry order   
CELL_BARCOD_PRE                Cell barcode prefix            
NXT_CELL_BARCOD_NO             Next cell barcode #            
PRC_1                          Price-1                        
BARCOD                         Barcode                        
PS_PROMPT_COD_1                Prompt code 1                  
PS_PROMPT_COD_2                Prompt code 2                  
PS_PROMPT_COD_3                Prompt code 3                  
IS_ECOMM_ITEM                  Ecommerce item                 
ECOMM_LST_PUB_DT               Date                           
ECOMM_LST_PUB_STAT             Status                         
ECOMM_ON_SPECL_UNTIL           Until                          
ECOMM_IMG_FILE                 Image file                     
ECOMM_TXBL_1                   Charge tax-1                   
ECOMM_TXBL_2                   Charge tax-2                   
ECOMM_TXBL_3                   Charge tax-3                   
URL                            URL                            
ECOMM_NEW                      New                            
ECOMM_NEW_UNTIL                Until                          
ECOMM_ON_SPECL                 On special                     
ECOMM_CHRG_FRT                 Charge freight                 
ECOMM_FRT_AMT                  Freight amount                 
VEND_ITEM_NO                   Vendor's item #                
LST_MAINT_DT                   Last maintained                
LST_MAINT_USR_ID               Last maintained by             
LST_LCK_DT                     Last lock                      
ROW_TS                         Row timestamp                  
TAX_CATEG_COD                  Tax category                   
DFLT_COST_OF_SLS_PCT           COS%                           
REG_PRC                        Regular price                  
ALT_1_REG_PRC                  Alt-1 regular price            
ALT_2_REG_PRC                  Alt-2 regular price            
ALT_3_REG_PRC                  Alt-3 regular price            
ALT_4_REG_PRC                  Alt-4 regular price            
ALT_5_REG_PRC                  Alt-5 regular price            
LST_COST                       Last cost                      
LST_RECV_DAT                   Last received date             
IS_FOOD_STMP_ITEM              Food stamp item                
PROMPT_FOR_UNIT                Prompt for unit                
PROMPT_FOR_CUSTOM_FLDS         Prompt for custom fields       
MIX_MATCH_COD                  Mix-and-Match code             
IS_ADM_TKT                     Admission ticket               
RS_UTC_DT                      DataSync datetime              
IS_BOM_PAR                     Bill of materials parent       
IS_KIT_PAR                     Kit parent                     
CATEG_SUBCAT                   Categ/Subcat                   
DIM_COD                        Dimension code                 
DIM_COD_LABEL                  Dimension code label           
DIM_COUNT                      Dimension code count           
PREF_UNIT_CUBE                 Preferred unit cube            
PREF_UNIT_DENOM                Preferred unit divide by       
PREF_UNIT_NAM                  Preferred unit                 
PREF_UNIT_NUMER                Preferred unit multiply by     
PREF_UNIT_PRC_1                Preferred unit price-1         
PREF_UNIT_REG_PRC              Preferred unit regular price   
PREF_UNIT_WEIGHT               Preferred unit weight          
ITEM_IS_MISC                   Item is miscellaneous          
COPY_FROM_ITEM_NO              Copy from item number          
BARCOD_3_OF_9                  Barcode 3 0f 9                 
IS_DISCNTBL                    Discountable                   
ECOMM_DISC_ON_SAL              Discount on-sale items         
PS_LIN_CUST_FLD_FRM_ID         Line custom prompts            
ECOMM_LST_CHNG_UTC_DT          Last CPOL-relevant change (fut 
ECOMM_NXT_PUB_TYP              Next publishing mode (future)  
ECOMM_ITEM_IS_DISCNTBL         Discountable                   
RS_STAT                        DataSync replication status    
ECOMM_PUB_STAT                 Ecommerce publishing status (f

**Comment by Nepherhotep** [comment]
Thanks @MikeRitchie 

Can you please confirm the given table description was completely pasted here, as it ends with "ECOMM_PUB_STAT Ecommerce publishing **status (f**"

**Comment by MikeRitchie** [comment]
Good catch. I re-ran the report and double checked and that is indeed all the information, so it must be cut off in the data dictionary. If you have a Counterpoint system you can run these reports yourself by going to System > Utilities > Column Description report. I'll have to see why the metadata is messed up for the ECOMM_PUB_STAT, but if you need more specifics on it let us know.

**Comment by Nepherhotep** [comment]
> System > Utilities > Column Description

That's huge, thanks for reference!

Regards,
Alexey
