### ISSUE TITLE
After installation I'm getting 404 on login page?

### ISSUE THREAD

**Issue by EtherMan01** [NCRCounterpointAPI/APIGuide#2]
I've added the following path to my antivirus exception "C:\Program Files (x86)\NCR\Counterpoint API"
and can access the url : 'https://johnp-cwi:52000/metadata' and see the operations listed so I am getting
responses from the service.  Is there something I am missing?

**Comment by MikeRitchie** [comment]
Is this the url you are using to access the login page? https://johnp-cwi:52000/app/index.htm#/login
If that URL isn't working, but the /metadata link you posted is, I'd first try restarting the service. If it persists, please send a fresh log from the \logfiles folder that covers the service restart followed by an attempt to access the login page.

**Comment by EtherMan01** [comment]
--------------------------------------------
Still not working?  I re-ran the installer and selected repair.
Still not working?  I have attached the log file.



On Thu, 2/2/17, MikeRitchie <notifications@github.com> wrote:

 Subject: Re: [NCRCounterpointAPI/APIGuide] After installation I'm getting 404 on login page? (#2)
 To: "NCRCounterpointAPI/APIGuide" <APIGuide@noreply.github.com>
 Cc: "EtherMan01" <paqman777@yahoo.com>, "Author" <author@noreply.github.com>
 Date: Thursday, February 2, 2017, 4:34 PM
 
 Is this the url you are using to
 access the login page? https://johnp-cwi:52000/app/index.htm#/login
 
 If that URL isn't working, but the /metadata link you
 posted is, I'd first try restarting the service. If it
 persists, please send a fresh log from the \logfiles
 folder that covers the service restart followed by an
 attempt to access the login page.
 
 —
 You are receiving this because you authored the thread.
 Reply to this email directly, view
 it on GitHub, or mute
 the thread.

**Comment by MikeRitchie** [comment]
I'm not seeing the logfile. Can you re-attach or email to mike.ritchie@ncr.com

**Comment by MikeRitchie** [comment]
We're looking into this, focused on this error in your log right now:

2017-02-03T08:10:55.56980 ERROR 1 AppSelfServerHost Error in ConfigureHost: Value cannot be null.
Parameter name: Waithandle array may not be empty.

My best guess at the moment is this may be related to a process where a new API install automatically looks to see if Counterpoint is installed on the machine and configures information from companies.ini. That process may be failing. If you have a Counterpoint install referenced in your registry could you remove it? It would be located at:

HKEY_LOCAL_MACHINE\Software\Synchronics\CounterPoint\8.0\ (32 bit)
or
HKEY_LOCAL_MACHINE\SOFTWARE\Wow6432Node\Synchronics\CounterPoint\8.0 (64 bit)

There will be an "InstallPath" key at that location that you can rename, then restart the API, retest the login, and resend a log.

**Comment by EtherMan01** [comment]
I do not have Counterpoint installed and neither of those registry entries exist.
--------------------------------------------
On Fri, 2/3/17, MikeRitchie <notifications@github.com> wrote:

 Subject: Re: [NCRCounterpointAPI/APIGuide] After installation I'm getting 404 on login page? (#2)
 To: "NCRCounterpointAPI/APIGuide" <APIGuide@noreply.github.com>
 Cc: "EtherMan01" <paqman777@yahoo.com>, "Author" <author@noreply.github.com>
 Date: Friday, February 3, 2017, 12:34 PM
 
 We're looking into this,
 focused on this error in your log right now:
 2017-02-03T08:10:55.56980 ERROR 1 AppSelfServerHost Error
 in ConfigureHost: Value cannot be null.
 
 Parameter name: Waithandle array may not be empty.
 My best guess at the moment is this may be related to a
 process where a new API install automatically looks to see
 if Counterpoint is installed on the machine and configures
 information from companies.ini. That process may be failing.
 If you have a Counterpoint install referenced in your
 registry could you remove it? It would be located at:
 HKEY_LOCAL_MACHINE\Software\Synchronics\CounterPoint\8.0\
 (32 bit)
 
 or
 
 HKEY_LOCAL_MACHINE\SOFTWARE\Wow6432Node\Synchronics\CounterPoint\8.0
 (64 bit)
 There will be an "InstallPath" key at that
 location that you can rename, then restart the API, retest
 the login, and resend a log.
 
 —
 You are receiving this because you authored the thread.
 Reply to this email directly, view
 it on GitHub, or mute
 the thread.

**Comment by mbantug** [comment]
Please try this.

- Copy the file from the attached zip and replace the file in "C:\Program Files (x86)\NCR\Counterpoint API\App_Data".
- Restart the NCR Counterpoint API service
- Try logging in to the admin console again
- If successful, it should ask you to change your password.
- After changing password and logging in, go to Configuration -> Companies
- You should see a company called QATESTGOLFFRESH853 in the list on this screen.
- Select it, click Edit, then delete it.
- Now, click Add to add your company to the list.  Do not restart the service until you add something or you will return to the same error as before.

[sysadmin.zip](https://github.com/NCRCounterpointAPI/APIGuide/files/751396/sysadmin.zip)

**Comment by EtherMan01** [comment]
This attachment is a link not the acutal file?
--------------------------------------------
On Fri, 2/3/17, Mark <notifications@github.com> wrote:

 Subject: Re: [NCRCounterpointAPI/APIGuide] After installation I'm getting 404 on login page? (#2)
 To: "NCRCounterpointAPI/APIGuide" <APIGuide@noreply.github.com>
 Cc: "EtherMan01" <paqman777@yahoo.com>, "Author" <author@noreply.github.com>
 Date: Friday, February 3, 2017, 2:44 PM
 
 Please try this.
 
 Copy the file from the attached zip and replace the file
 in "C:\Program Files (x86)\NCR\Counterpoint
 API\App_Data".
 Restart the NCR Counterpoint API service
 Try logging in to the admin console again
 If successful, it should ask you to change your
 password.
 After changing password and logging in, go to
 Configuration -> Companies
 You should see a company called QATESTGOLFFRESH853 in
 the list on this screen.
 Select it, click Edit, then delete it.
 Now, click Add to add your company to the list.  Do not
 restart the service until you add something or you will
 return to the same error as before.
 
 sysadmin.zip
 
 —
 You are receiving this because you authored the thread.
 Reply to this email directly, view
 it on GitHub, or mute
 the thread.

**Comment by mbantug** [comment]
Clicking the link "sysadmin.zip" should download the file.

**Comment by EtherMan01** [comment]
OK...I was able to get the file.
--------------------------------------------
On Fri, 2/3/17, Mark <notifications@github.com> wrote:

 Subject: Re: [NCRCounterpointAPI/APIGuide] After installation I'm getting 404 on login page? (#2)
 To: "NCRCounterpointAPI/APIGuide" <APIGuide@noreply.github.com>
 Cc: "EtherMan01" <paqman777@yahoo.com>, "Author" <author@noreply.github.com>
 Date: Friday, February 3, 2017, 2:44 PM
 
 Please try this.
 
 Copy the file from the attached zip and replace the file
 in "C:\Program Files (x86)\NCR\Counterpoint
 API\App_Data".
 Restart the NCR Counterpoint API service
 Try logging in to the admin console again
 If successful, it should ask you to change your
 password.
 After changing password and logging in, go to
 Configuration -> Companies
 You should see a company called QATESTGOLFFRESH853 in
 the list on this screen.
 Select it, click Edit, then delete it.
 Now, click Add to add your company to the list.  Do not
 restart the service until you add something or you will
 return to the same error as before.
 
 sysadmin.zip
 
 —
 You are receiving this because you authored the thread.
 Reply to this email directly, view
 it on GitHub, or mute
 the thread.

**Comment by EtherMan01** [comment]
OK...that worked.  Do I need valid enteries initially?
Or can I edit the company data after the fact?
--------------------------------------------
On Fri, 2/3/17, Mark <notifications@github.com> wrote:

 Subject: Re: [NCRCounterpointAPI/APIGuide] After installation I'm getting 404 on login page? (#2)
 To: "NCRCounterpointAPI/APIGuide" <APIGuide@noreply.github.com>
 Cc: "EtherMan01" <paqman777@yahoo.com>, "Author" <author@noreply.github.com>
 Date: Friday, February 3, 2017, 2:44 PM
 
 Please try this.
 
 Copy the file from the attached zip and replace the file
 in "C:\Program Files (x86)\NCR\Counterpoint
 API\App_Data".
 Restart the NCR Counterpoint API service
 Try logging in to the admin console again
 If successful, it should ask you to change your
 password.
 After changing password and logging in, go to
 Configuration -> Companies
 You should see a company called QATESTGOLFFRESH853 in
 the list on this screen.
 Select it, click Edit, then delete it.
 Now, click Add to add your company to the list.  Do not
 restart the service until you add something or you will
 return to the same error as before.
 
 sysadmin.zip
 
 —
 You are receiving this because you authored the thread.
 Reply to this email directly, view
 it on GitHub, or mute
 the thread.

**Comment by mbantug** [comment]
You can edit the information later, just make sure you have an entry there for now.  The error was occurring when the API had no companies at startup in the list which usually gets populated by the process Mike described above.

**Comment by EtherMan01** [comment]
all good I am connected to our CP demo server.
--------------------------------------------
On Fri, 2/3/17, Mark <notifications@github.com> wrote:

 Subject: Re: [NCRCounterpointAPI/APIGuide] After installation I'm getting 404 on login page? (#2)
 To: "NCRCounterpointAPI/APIGuide" <APIGuide@noreply.github.com>
 Cc: "EtherMan01" <paqman777@yahoo.com>, "Author" <author@noreply.github.com>
 Date: Friday, February 3, 2017, 3:14 PM
 
 You can edit the information
 later, just make sure you have an entry there for now.  The
 error was occurring when the API had no companies at startup
 in the list which usually gets populated by the process Mike
 described above.
 
 —
 You are receiving this because you authored the thread.
 Reply to this email directly, view
 it on GitHub, or mute
 the thread.

**Comment by mintile** [comment]
I had the same 404 issue and installed the sysadmin.sqlite from the zip file and I now get a login screen. I’m not sure if it is a generic file or not. I’m guessing its not because it’s dated today but at least we’re further along.

**Comment by mintile** [comment]
I should have read further up before I posted. So, I was able to login. I added a few of my test companies and then deleted the QATESTGOLFFRESH853 company. I guess its time to start testing.....

**Comment by MikeRitchie** [comment]
Closing this issue as the above workaround solves the issue. Future API release will fix this case to ensure the API works properly when installed on a machine without Counterpoint.
