### ISSUE TITLE
Error on some endpoints

### ISSUE THREAD

**Issue by BrianRoyal** [NCRCounterpointAPI/APIGuide#22]
I'm getting an error when I try to connect to some endpoints.
Example:
https://mypublicIP:52000/Items
https://mypublicIP:52000/Customers
https://mypublicIP:52000/EC
https://mypublicIP:52000/Inventory/EC
https://mypublicIP:52000/ItemCategories

Error:
Array
(
    [ResponseStatus] => Array
        (
            [ErrorCode] => Exception
            [Message] => Error trying to resolve Service 'CPAPI.Common.IUserRoleBusiness' or one of its autowired dependencies (see inner exception for details).
            [StackTrace] =>    at Funq.Container.ResolveImpl[TService,TArg](String name, Boolean throwIfMissing, TArg arg)
   at CPAPI.Common.RoleAttribute.Execute(IRequest req, IResponse res, Object requestDto)
   at ServiceStack.RequestFilterAttribute.RequestFilter(IRequest req, IResponse res, Object requestDto)
   at ServiceStack.ServiceStackHost.ApplyRequestFiltersSingle(IRequest req, IResponse res, Object requestDto)
   at ServiceStack.ServiceStackHost.ApplyRequestFilters(IRequest req, IResponse res, Object requestDto)
   at ServiceStack.Host.RestHandler.ProcessRequestAsync(IRequest httpReq, IResponse httpRes, String operationName)
        )

)

For some endpoints it works fine.  Examples of non-erroring endpoints:
https://mypublicIP:52000/AdminUsers
https://mypublicIP:52000/APIKeys
https://mypublicIP:52000/SystemInfo

My test code is attached (apicall.txt) 
[apicall.txt](https://github.com/NCRCounterpointAPI/APIGuide/files/980682/apicall.txt)

Any idea what I might be doing wrong?  Also attached are the log files from the day this was tried.
[CPAPI_2017-05-05.0.txt](https://github.com/NCRCounterpointAPI/APIGuide/files/980685/CPAPI_2017-05-05.0.txt)

Thanks in advance,
Brian

**Comment by MikeRitchie** [comment]
It looks like all the endpoints that are working are system/API server level endpoints, while the ones that are failing are company level endpoints. My guess would be that you're using API administrator credentials to make company level calls. Make sure you're using a company level user credential with the format <company>.<user>:<password in your authorization header.

**Comment by BrianRoyal** [comment]
Thanks Mike - I think you're right.  I'll let you know how making that change turns out.

**Comment by BrianRoyal** [comment]
Different message when changing to company level credentials.  We're using a company level credential with all roles enabled EXCEPT [DELETE] /AdminUser/{UserID}

Now, we're getting this error:

Array
(
    [ResponseStatus] => Array
        (
            [ErrorCode] => UnauthorizedAccessException
            [Message] => The registration file is not valid.
            [StackTrace] =>    at CPAPI.Common.RegIniAttribute.Execute(IRequest req, IResponse res, Object requestDto)
   at ServiceStack.RequestFilterAttribute.RequestFilter(IRequest req, IResponse res, Object requestDto)
   at ServiceStack.ServiceStackHost.ApplyRequestFiltersSingle(IRequest req, IResponse res, Object requestDto)
   at ServiceStack.ServiceStackHost.ApplyRequestFilters(IRequest req, IResponse res, Object requestDto)
   at ServiceStack.Host.RestHandler.ProcessRequestAsync(IRequest httpReq, IResponse httpRes, String operationName)
        )

)

I've verified that we're using the registration.ini file with NCR CounterPoint API=1.  The serial # is 810598.  Any thoughts here?

**Comment by MikeRitchie** [comment]
Brian,
Could you directly email me your registration.ini as well as the API Logfile (frome the logfiles folder) that covers the issue?

**Comment by MikeRitchie** [comment]
Working with Brian, he deleted and re-added the company and the error went away. Not sure what the issue was at this point unfortunately. Closing.
