### ISSUE TITLE
Get Document (by DocID) produces SQL Exception

### ISSUE THREAD

**Issue by tobegold** [NCRCounterpointAPI/APIGuide#25]
GET https://domainname:port/Document/999999999999 
(where 999999999999 is a docID value)

produces this error 
ErrorCode":"SqlException","Message":"Invalid column name 'PROCESSOR_RCPT'.","StackTrace"....

Anyone know what this means and how to fix it?

thx
Tobe

**Comment by MikeRitchie** [comment]
Please see this issue, that was mistakenly entered in the APITests forum rather than this one. It has a workaround for the issue:

https://github.com/NCRCounterpointAPI/APITests/issues/4
