### ISSUE TITLE
How to create item with API?

### ISSUE THREAD

**Issue by rajeshcorcrm** [NCRCounterpointAPI/APIGuide#27]
Hello everyone, I have installed the NCR counterpoint software and setup the API on the system. Everything is working fine and i'm able to get the APi keys, Items, Orders from the system from the follwing url http://php70:52000/ with postman hits. 
Can anybody please let me know how can i generate an item or create product? 
What is the API endpoint url for creating the Items in counterpoint system?
So i can make an order with created items through API. Instead of creating the items manually from the counterpoint system.
Thanks in advance!!
Rajesh

**Comment by MikeRitchie** [comment]
There is not an endpoint in place yet to allow creation of items or inventory records through the API, so they will need to be created through Counterpoint. I've noted the request for use in prioritizing future enhancements. 

You can create orders for existing items via the API using the POST /Document endpoint, the DOC_TYP and LIN_TYP fields denote if the item is an order vs. a sale.
