### ISSUE TITLE
Cant insert or update customers

### ISSUE THREAD

**Issue by Bflatt** [NCRCounterpointAPI/APIGuide#31]
We are unable to insert or update a customer.   Api call returns success but customer is not inserted.

**Comment by MikeRitchie** [comment]
Please post the API call information (remove any sensitive, non-test data). Ideally, if you are using Postman, hit the "Code" link in the top right, then in the code snippet dialog select "HTTP", then "Copy to Clipboard" and paste the information in this thread. That will share all the headers and other relevant information on your API call. Be aware that that includes the authorization header, so please mangle or delete it before posting.

**Comment by Bflatt** [comment]
resolved.
