### ISSUE TITLE
Filter by LST_MAINT_DT

### ISSUE THREAD

**Issue by wwbs** [NCRCounterpointAPI/APIGuide#33]
Is there a way currently or future plan to implement a param filter for LST_MAINT_DT on customers, items, inventory, documents, etc? Looking for the best way to get recently modified objects but can't seem to find any docs on it.

**Comment by MikeRitchie** [comment]
The API 1.1 release will be adding a filter on customers, items, and inventory for the RS_UTC_DT. Field RS_UTC_DT is preferable to LST_MAINT_DT because it's indexed, time zone aware, and more reliably updated (due to triggers).
