### ISSUE TITLE
Cannot populate fields on order and customer insert

### ISSUE THREAD

**Issue by Bflatt** [NCRCounterpointAPI/APIGuide#34]
Populate BILL_NAM, SHIP_NAM and BILL_NAM_UPR or ORD_TAX_AMT  
for the names.  We do not see where to insert.   We are attempting to put the ord_tax_amt into PS_DOC_TAX but this appears to be the incorrect table as the value is not in this table.

**Comment by MikeRitchie** [comment]
The second example on the POST document page shows how to pass in the name for billing contact and shipping contact, via the "BILL_TO_CONTACT" and "SHIP_TO_CONTACT" structures. the *_UPR versions of the FST_NAM and LST_NAM values passed into these structures are created automatically.
https://github.com/NCRCounterpointAPI/APIGuide/blob/master/Endpoints/POST_Document.md

In the same example you can see a "PS_TAX" structure at the end of the POST data that allows you to pass the ORD_TAX_AMT.

**Comment by Bflatt** [comment]
Mike,  that’s the problem.  The Billing   NAM is not being created automatically.  
![capture](https://user-images.githubusercontent.com/28633209/28532926-576b3068-7069-11e7-91e4-ff0916b5acf8.JPG)

**Comment by MikeRitchie** [comment]
Is your screenshot pulling from a view or a table, could you share the query you posted the screenshot from?

**Comment by MikeRitchie** [comment]
After a quick look it looks like you are getting those fields from a view, and that view is pulling from PS_DOC_CONTACT.NAM. I'd try explicitly filling in the NAM field as part of the BILL_TO_CONTACT and SHIP_TO_CONTACT structures when posting to /Document. Here's a partial excerpt:

`{
 "PS_DOC_HDR": {
   "STR_ID": "MAIN",
   "STA_ID": "1",
   "DRW_ID": "1",
   "TKT_TYP": "T",
   "DOC_TYP": "O",
   "USR_ID": "MGR",
   "TAX_COD": "1",
   "NORM_TAX_COD": "1",
   "BILL_TO_CONTACT": {
     "FST_NAM": "John",
     "LST_NAM": "Do",
     "NAM": "John Do",
     "ADRS_1": "100 Main St",
     "CITY": "Memphis",
     "ZIP_COD": "38119",
     "STATE": "TN",
     "PHONE_1": "(901) 555-2222",
     "NAM_TYP": "P"
   },
   "SHIP_TO_CONTACT": {
     "FST_NAM": "John",
     "LST_NAM": "Do",
     "NAM": "John Do",
     "ADRS_1": "100 Main St",
     "CITY": "Memphis",
     "ZIP_COD": "38119",
     "STATE": "TN",
     "PHONE_1": "(901) 555-2222",
     "NAM_TYP": "P"
   },`
..etc.

I'd definitely say we should improve the API to fill in the NAM field by concatenating FST_NAM & LST_NAM is it's not explicitly passed in.

**Comment by Bflatt** [comment]
Have you attempted to fill NAM and works because I think we have and it did not.  We will test now.

[cid:image001.jpg@01D2DEDA.41EDDC70]

Bill Flatt
Mainspring, LLC
6060 S American Plaza St E | Suite 300 | Tulsa, OK | 74135
Phone: 800.865.1427 x2827 | Local: 918.317.0707 | Direct: 918.960.2827
bflatt@mainspring.net<mailto:bflatt@mainspring.net> | www.mainspring.net<http://www.mainspring.net> | Need Help?<mailto:support@mainspring.net>
[cid:image002.png@01D2DEDA.41EDDC70]<https://www.facebook.com/MainSpringRetailSolutions/>[cid:image003.png@01D2DEDA.41EDDC70]<https://twitter.com/MainspringPOS> [cid:image004.png@01D2DEDA.41EDDC70] <http://www.linkedin.com/company/576462>  [cid:image005.png@01D2DEDA.41EDDC70] <mailto:support@mainspring.net>

**Comment by Bflatt** [comment]
[problem insert.xlsx](https://github.com/NCRCounterpointAPI/APIGuide/files/1170664/problem.insert.xlsx)

**Comment by Bflatt** [comment]
I believe we have attempted to fill nam and it does not accept the field.   we will test again.   The problem only expresses itself on inserted orders as the BILL_NAM SHIP_NAM is the stock field on counterpoint pos form address blocks.

**Comment by MikeRitchie** [comment]
I just tested and successfully inserted the NAM field. I verified that PS_DOC_CONTACT.NAM was populated for both bill to and ship to records, and then checked VI_PS_DOC_HDR to verify BILL_NAM, BILL_NAM_UPR, and SHIP_NAM are all populated.

**Comment by Bflatt** [comment]
Thanks a bunch.

[cid:image001.jpg@01D2DEDA.41EDDC70]

Bill Flatt
Mainspring, LLC
6060 S American Plaza St E | Suite 300 | Tulsa, OK | 74135
Phone: 800.865.1427 x2827 | Local: 918.317.0707 | Direct: 918.960.2827
bflatt@mainspring.net<mailto:bflatt@mainspring.net> | www.mainspring.net<http://www.mainspring.net> | Need Help?<mailto:support@mainspring.net>
[cid:image002.png@01D2DEDA.41EDDC70]<https://www.facebook.com/MainSpringRetailSolutions/>[cid:image003.png@01D2DEDA.41EDDC70]<https://twitter.com/MainspringPOS> [cid:image004.png@01D2DEDA.41EDDC70] <http://www.linkedin.com/company/576462>  [cid:image005.png@01D2DEDA.41EDDC70] <mailto:support@mainspring.net>
