### ISSUE TITLE
Error Code 66:: Failed to connect to <Server>: Connection timed out

### ISSUE THREAD

**Issue by sazary33** [NCRCounterpointAPI/APIGuide#35]
Hello,

I am not able to make a successful API call through cURL from a linux web server to a Windows Server with NCR API. I can make successful calls through Postman. 

I keep seeing error code 66: CURLE_SSL_ENGINE_INITFAILED. The error message is Failed to connect to <Server>: Connection timed out.

I'm guessing this is related to the SSL certificate verification which I disabled through postman.

Can you provide an example of how to make a successful API call through cURL? 

I tried disabling SSL certificate verification through cURL but was unsuccessful. Any thoughts would be appreciated. Thanks.

**Comment by MikeRitchie** [comment]
It sounds like this is a cURL linux issue since the API by default uses a self signed SSL certificate. You could buy and use a signed certificate, or rather than disabling SSL you may be able to add the self signed certificate to the linux system as a trusted root authority. I don't know specifically how to do that in linux, but once you tell linux the self signed cert can be trusted, I'd guess any SSL access to the API from that machine should work fine.

**Comment by sazary33** [comment]
Thanks for your reply. As a follow up, I am wondering if this is a routing issue. Counterpoint with the API key is running on one IP address. Internally on that network I can access the NCR API login page. I setup port forwarding 52000 on the router so I can access the API externally. From a different external location, I can't access the login page. Are you aware of any special routing settings that need to be applied for the API? The strange thing is that with the current settings I can make all the API calls through postman from an external network (with SSL disabled only).

**Comment by MikeRitchie** [comment]
The API operates just like a web server, so nothing special from that standpoint. If you're accessing from outside the network, you need to make sure you are hitting your external IP address, which will be different from the one used internally on the network. Are you using your routers public IP address when trying to hit the API externally?

**Comment by sazary33** [comment]
Yes I am. I can't ping <external ip>:52000 either. I can provide you details of my external ip privately if you would like to try and access the API login page?
