### ISSUE TITLE
Gridded item inventory using api?

### ISSUE THREAD

**Issue by baljeetbhardwaj** [NCRCounterpointAPI/APIGuide#37]
Hi,
I have a product with multiple variations(Color, Size). I need each item's stock details individually through API. Is their any endpoint to get these details?

As shown in the screenshot.
![aa](https://user-images.githubusercontent.com/30104271/28167944-129af2f0-67fb-11e7-8c20-0c086bacd174.png)

**Comment by MikeRitchie** [comment]
The GET Item/{ItemNo}/Inventory/{locID} endpoint will give inventory values for both gridded and non-gridded items: https://github.com/NCRCounterpointAPI/APIGuide/blob/master/Endpoints/GET_Item_Inventory.md

I noticed 8.5.3 in your screenshot above. Note that 8.5.3 is not yet supported for the API. An API 1.1 release is due out late August that will support 8.5.3. In the meantime, I'd recommend developing against an 8.5.2 DB, which should be the same from an API perspective, so your code will work with 8.5.3 without changes.

**Comment by baljeetbhardwaj** [comment]
Thanks for quick reply!!
