### ISSUE TITLE
SqlException for /Inventory/EC and /Items

### ISSUE THREAD

**Issue by sazary33** [NCRCounterpointAPI/APIGuide#38]
Hello, I know this issue has already been created for the exception below. I just wanted to create this issue because I didn't see both /Inventory/EC and /Items marked as having the sql exception when NCR items exceeds 2100 items. If both are planned to be fixed in the next release please go ahead and mark this issue as closed. Thanks

Error:
The incoming tabular data stream (TDS) remote procedure call (RPC) protocol stream is incorrect. Too many parameters were provided in this RPC request. The maximum is 2100.

**Comment by sazary33** [comment]
As a follow up, I read a patch can be made available to fix this issue. Is it possible to get a patch for this issue?

**Comment by MikeRitchie** [comment]
Yes, all instances of this error should be fixed in the next release, including /Inventory/EC and /Items. Currently, no patch is available for this issue.
