### ISSUE TITLE
Getting promotional sale information

### ISSUE THREAD

**Issue by sazary33** [NCRCounterpointAPI/APIGuide#39]
Hello, I can't seem to find how to access promotional sale information for items. If an item is on sale like 20% off or even BOGO, is there a way to get such information from any of the current endpoints? Much appreciated.

**Comment by MikeRitchie** [comment]
Typically, many of these sorts of promos, such as BOGO, are implemented as price rules, which we don't support retreiving via the API currently. 

Can you describe a bit more about what you're trying to accomplish? Price rules are very open ended and can be triggered by any number of attributes, such as a customer or other item/category being on the ticket.

Counterpoint does support up to 6 prices being defined for an item, and price rules can also trigger any of those prices to be used, but again the user decides what they are used for (Price-2 may be a loyalty price, a wholesale price, etc.). You can get price-1 through price-6 via the  GET /Items call (default company level prices) or by  GET /Items/{LocId} (for location specific prices)

**Comment by sazary33** [comment]
Hi Mike, than you for your response. Today we apply promotions such as a percent discount through Promotions in NCR. For example, we have a group of items under a specific category that we specified to have a 50% discount using a group code for all items under a specific category. I know through NRO today these sales are automatically showing when set from NCR. Is there any way to support getting such information outside of a custom price attribute or can I request that such information be made available as an endpoint through the API? I'm not sure if there's a way to reflect the promotional price automatically on one of the price attributes but that could work too.

**Comment by MikeRitchie** [comment]
If you're looking to just get information on the configured price rules through the API, I think that's something that's doable (but I don't have a time frame for it at the moment, as this is the first request for it).

**Comment by sazary33** [comment]
Thank you for considering this feature request and thank you for all your help so far.
