### ISSUE TITLE
API Key Request URL returning "404 - File or directory not found."?

### ISSUE THREAD

**Issue by EtherMan01** [NCRCounterpointAPI/APIGuide#4]
https://retailchannel.radiantsystems.com/api_request

**Comment by EtherMan01** [comment]
https://retailchannel.radiantsystems.com/api_request

**Comment by MikeRitchie** [comment]
Should be https://retailchannel.radiantsystems.com/api_request.htm. What page did the above link come from?

**Comment by EtherMan01** [comment]
Ok...that works.  It was a screen shot on a 2 part video series from NCR on the upcoming API.

**Comment by MikeRitchie** [comment]
Glad it worked! Closing.
