### ISSUE TITLE
ERROR_UNKNOWN on post document

### ISSUE THREAD

**Issue by aaijtm** [NCRCounterpointAPI/APIGuide#40]
Hi,

We have tried some basic document post tests (imported from your automated test collections) on our API and are getting errors. I have tried many posts and confirmed that our data is valid. All the error responses are code "ERROR_UNKNOWN". Please assist with this.

ERROR
{

"Documents": [],

"ErrorCode": "ERROR_UNKNOWN",

"Message": "An error occurred during AddDocument POST: Object reference not set to an instance of an object., at CPAPI.Business_846.DocumentBusiness_846.PopulateDefaults(PS_DOC_HDR documentHeader, String workgroupId)\r\n at CPAPI.Business_846.DocumentBusiness_846.AddDocument(PS_DOC_HDR_POST documentPost, PS_TAX_VIEW taxView, String workgroup)"
}

{

"PS_DOC_HDR": {

"STR_ID": "7",

"STA_ID": "7-1",

"DRW_ID": "7-1",

"TKT_TYP": "T",

"DOC_TYP": "T",

"USR_ID": "{USR}",

"TAX_COD": "NOTAX}",

"PS_DOC_NOTE": [

{

"NOTE_ID": "A1",

"NOTE": "This is a note!"

}

],

"PS_DOC_LIN": [

{

"LIN_TYP": "S",

"ITEM_NO": "M-112862",

"QTY_SOLD": "1.0",

}

],

"PS_DOC_PMT": [

{

"AMT": "1.64",

"PAY_COD": "CASH",

"DESC": "Cash",

"FINAL_PMT": "Y",

"CURNCY_COD": "HOME",

"PS_DOC_PMT_APPLY": {

"AMT": "1.64",

"HOME_CURNCY_AMT": "1.64",

},

}

],

"PS_DOC_TAX": [

{

"AUTH_COD": "NOTAX",

"RUL_COD": "NOTAX",

"TAX_DOC_PART": "S",

"LIN_AMT": "0.00",

"TXBL_LIN_AMT": "0.00",

"TXBL_QTY": "0.00",

"TAX_AMT": "0.00",

"TOT_TXBL_AMT": "0.00"

},

]

}
}

**Comment by MikeRitchie** [comment]
The JSON above had some syntax errors in it (specifically some errant commas). Try this:
{
  "PS_DOC_HDR": {
    "STR_ID": "7",
    "STA_ID": "7-1",
    "DRW_ID": "7-1",
    "TKT_TYP": "T",
    "DOC_TYP": "T",
    "USR_ID": "{USR}",
    "TAX_COD": "NOTAX}",
    "PS_DOC_NOTE": [
      {
        "NOTE_ID": "A1",
        "NOTE": "This is a note!"
      }
    ],
    "PS_DOC_LIN": [
      {
        "LIN_TYP": "S",
        "ITEM_NO": "M-112862",
        "QTY_SOLD": "1.0"
      }
    ],
    "PS_DOC_PMT": [
      {
        "AMT": "1.64",
        "PAY_COD": "CASH",
        "DESC": "Cash",
        "FINAL_PMT": "Y",
        "CURNCY_COD": "HOME",
        "PS_DOC_PMT_APPLY": {
          "AMT": "1.64",
          "HOME_CURNCY_AMT": "1.64"
        }
      }
    ],
    "PS_DOC_TAX": [
      {
        "AUTH_COD": "NOTAX",
        "RUL_COD": "NOTAX",
        "TAX_DOC_PART": "S",
        "LIN_AMT": "0.00",
        "TXBL_LIN_AMT": "0.00",
        "TXBL_QTY": "0.00",
        "TAX_AMT": "0.00",
        "TOT_TXBL_AMT": "0.00"
      }
    ]
  }
}

**Comment by aaijtm** [comment]
I tried editing my request as you suggested and using your request and the result is
{
    "Documents": [],
    "ErrorCode": "ERROR_UNKNOWN",
    "Message": "An error occurred during AddDocument POST: Ticket not fully paid,    at CPAPI.Business_846.DocumentBusiness_846.PrepareAndSaveTicket(PS_DOC_HDR document, PS_TAX tax, DocumentKey TicketKey, DocumentKey OrderKey, DocumentKey LayawayKey, Boolean MultipleDocs, PS_STR_CFG_PS storeconfig)\r\n   at CPAPI.Business_846.DocumentBusiness_846.SplitMixedDocumentAndSave(PS_DOC_HDR document, PS_TAX tax, IM_CTL itemControl)\r\n   at CPAPI.Business_846.DocumentBusiness_846.SaveMixedDocument(PS_DOC_HDR document, PS_TAX tax)\r\n   at CPAPI.Business_846.DocumentBusiness_846.AddDocument(PS_DOC_HDR_POST documentPost, PS_TAX_VIEW taxView, String workgroup)"
}

**Comment by MikeRitchie** [comment]
Since you aren't providing a price on your item, the API will use PRC_1 for the item, which is probably more than the $1.64 that you are submitting as payment. Try below, which explicitly sets the price of the item you're including on the ticket to $1.64:

{
"PS_DOC_HDR": {
"STR_ID": "7",
"STA_ID": "7-1",
"DRW_ID": "7-1",
"TKT_TYP": "T",
"DOC_TYP": "T",
"USR_ID": "{USR}",
"TAX_COD": "{NOTAX}",
"PS_DOC_NOTE": [
{
"NOTE_ID": "A1",
"NOTE": "This is a note!"
}
],
"PS_DOC_LIN": [
{
"LIN_TYP": "S",
"ITEM_NO": "M-112862",
"PRC":"1.64",
"QTY_SOLD": "1.0"
}
],
"PS_DOC_PMT": [
{
"AMT": "1.64",
"PAY_COD": "CASH",
"DESC": "Cash",
"CURNCY_COD": "HOME",
"PS_DOC_PMT_APPLY": {
"AMT": "1.64",
"HOME_CURNCY_AMT": "1.64"
}
}
],
"PS_DOC_TAX": [
{
"AUTH_COD": "NOTAX",
"RUL_COD": "NOTAX",
"TAX_DOC_PART": "S",
"LIN_AMT": "0.00",
"TXBL_LIN_AMT": "0.00",
"TXBL_QTY": "0.00",
"TAX_AMT": "0.00",
"TOT_TXBL_AMT": "0.00"
}
]
}
}

**Comment by aaijtm** [comment]
BINGO!  thank you.

**Comment by mwalkway** [comment]
Is there a place that lists required fields for posting new Documents? I'm having a similar problem with the following error:  
"ErrorCode": "ERROR_UNKNOWN",
    "Message": "An error occurred during AddDocument POST: Object reference not set to an instance of an object.,    at CPAPI.Business_85.DocumentBusiness_85.PopulateDefaults(PS_DOC_HDR documentHeader, String workgroupId)\r\n   at CPAPI.Business_85.DocumentBusiness_85.AddDocument(PS_DOC_HDR_POST documentPost, PS_TAX_VIEW taxView, String workgroup)"

Here is my JSON:

{
	"PS_DOC_HDR": {
		"STR_ID": "902",
		"STA_ID": "902-1",
		"DRW_ID": "902-1",
		"TKT_TYP": "T",
		"DOC_TYP": "T",
		"USR_ID": "{USRID}",
		"TAX_COD": "NOTAX",
		"PS_DOC_NOTE": [
			{
				"NOTE_ID": "A1",
				"NOTE": "A note will go here"
			}
		],
		"PS_DOC_LIN": [
			{
				"LIN_TYP": "O",
				"ITEM_NO": "PS001822",
				"PRC" : "19.99",
				"USR_ENTD_PRC":"Y",
				"QTY_SOLD": "1.0"
			}
		],
		"PS_DOC_PMT": [
			{
				"AMT": "19.99",
				"PAY_COD": "CASH",
				"FINAL_PMT": "N"
			}
		],
		"PS_DOC_TAX": [
			{
				"AUTH_COD": "NOTAX",
				"RUL_COD": "NOTAX",
				"TAX_DOC_PART": "S",
				"LIN_AMT": "0.00",
				"TXBL_LIN_AMT": "0.00",
				"TXBL_QTY": "0.00",
				"TAX_AMT": "0.00",
				"TOT_TXBL_AMT": "0.00"
			}
		]
	},
	"PS_TAX": {
		"ORD_NORM_TAX_AMT": "0",
		"ORD_TAX_AMT": "0"
	}
}
