### ISSUE TITLE
Getting items with special characters and image time stamps

### ISSUE THREAD

**Issue by sazary33** [NCRCounterpointAPI/APIGuide#41]
Hello,

We have items in Counterpoint with forward slashes in the item number (ie:  "ITEM_NO": "FN73239/40/41"). When I call ECCategories I can see items with forward slashes in the name.  However, I cannot query those items (ie: {{protocol}}://{{server}}:{{port}}/Item/FN73239/40/41). I've tried replacing the special character with underscores, spaces and removing the special characters but none seem to work. Is there a way to access items with forward slashes and other special characters through the Item endpoint?

Also, is there a way to get the time stamp or last modified field of the item images? I'd like to determine from the current item image if it has been updated so I can replace it in my application rather than always replace all item images. 

Thank you.

**Comment by MikeRitchie** [comment]
For the forward slashes, I'd try encoding the Hex ASCII value:

{{protocol}}://{{server}}:{{port}}/Item/FN73239%2F40%2F41

https://www.w3schools.com/tags/ref_urlencode.asp

**Comment by MikeRitchie** [comment]
Closing. If the URL encoding above doesn't work as expected, please post back.

**Comment by sazary33** [comment]
Hello the encoding did not work. I get the following 404 error when calling {{protocol}}://{{server}}:{{port}}/Item/FN73239%2F40%2F41

Handler for Request not found (404):
  Request.HttpMethod: GET
  Request.PathInfo: /Item/FN73239/40/41
  Request.QueryString: 
  Request.RawUrl: /Item/FN73239%2F40%2F41

**Comment by MikeRitchie** [comment]
I've not yet found a way to support this. I'd recommend avoiding the slashes if possible, and we'll research to try to find a way to make this work, but in general it appears that, whether encoded or not, this will be interpreted as part of the URL path, rather than part of the ITEM_NO.

**Comment by MikeRitchie** [comment]
Closing. There's currently no known way to accomodate this without changing the item_no. Hopefully this is a rare occurrence. In the future we may look for some alternate ways to handle this through some manual escaping or a similar approach.
