### ISSUE TITLE
Request for endpoint to get category image

### ISSUE THREAD

**Issue by sazary33** [NCRCounterpointAPI/APIGuide#42]
Hello, thank you for your patience as I evaluate and utilize the NCR Counterpoint API. There is no end point available to get the category images like we have for the product images. Can I place a feature request to support getting category images? Thank you.

**Comment by MikeRitchie** [comment]
While Counterpoint itself doesn't support category images, it does suppor the definition of eCommerce category images (Setup>eCommerce>Categories) in Counterpoint. 

You can use the GET /ECCategories endpoint to retrieve eCommerce category information, including image filenames (IMG_FILE).

Once you have the image filename, the GET /Item/Images/{filename} endpoint will retrieve the image file, as the eCommerce category images live in the "ItemImages" folder in the TLD, just as item images do. This endpoint will retrieve any image type file by filename from that folder.
