### ISSUE TITLE
when inserting a document with paycode set as final_pmt='Y' this error is returned

### ISSUE THREAD

**Issue by Bflatt** [NCRCounterpointAPI/APIGuide#43]
Array
(
    [Documents] => Array
        (
        )

    [ErrorCode] => ERROR_UNKNOWN
    [Message] => An error occurred during AddDocument POST: Object reference not set to an instance of an object.,    at CPAPI.Business_85.DocumentExtensions_85.HandleFinalPayments(PS_DOC_HDR document)
   at CPAPI.Business_85.DocumentBusiness_85.SplitMixedDocumentAndSave(PS_DOC_HDR document, PS_TAX tax, IM_CTL itemControl)
   at CPAPI.Business_85.DocumentBusiness_85.SaveMixedDocument(PS_DOC_HDR document, PS_TAX tax)
   at CPAPI.Business_85.DocumentBusiness_85.AddDocument(PS_DOC_HDR_POST documentPost, PS_TAX_VIEW taxView, String workgroup)
)

**Comment by MikeRitchie** [comment]
Could you provide the data that you're posting to API?

My recollection is that final payment only works with credit type pay codes, and the amount for the payment must be less than the total amount due (the amount included with the payment will be charged immediately, as a deposit. There must be a balance due remaining that Counterpoint will charge when the order is released).

**Comment by Bflatt** [comment]
[
[Failed insert because of Y on final payment.txt](https://github.com/NCRCounterpointAPI/APIGuide/files/1180026/Failed.insert.because.of.Y.on.final.payment.txt)
](url)

**Comment by Bflatt** [comment]
Mike.   Paul has had issued with other mods and inserting without 'Y' for final payment.  Earlier this month this was working for us and we could post the inserted orders.  Now when we insert and order we can release but they will not post due to payment application problems.  I am gathering a sample insert with 'N' for final payment with resulting table values.   We are having issues with the header totals reporting an negative amount due and the tickets will not post.

**Comment by MikeRitchie** [comment]
Is your intent to just provide payment information to Counterpoint, and let Counterpoint charge the full amount of the order upon release, or is the intent to have the API charge a deposit against the card immediately (when the API call is made), and also save the card for Counterpoint to use as final payment when the order is released?

**Comment by Bflatt** [comment]
The intent is to apply payment to order as fully paid and apply deposit on release to lines released all at once on multiple releases of one line at a time. These will be authorize.net or paypal payments.

[cid:image001.jpg@01D2DEDA.41EDDC70]

Bill Flatt
Mainspring, LLC
6060 S American Plaza St E | Suite 300 | Tulsa, OK | 74135
Phone: 800.865.1427 x2827 | Local: 918.317.0707 | Direct: 918.960.2827
bflatt@mainspring.net<mailto:bflatt@mainspring.net> | www.mainspring.net<http://www.mainspring.net> | Need Help?<mailto:support@mainspring.net>
[cid:image002.png@01D2DEDA.41EDDC70]<https://www.facebook.com/MainSpringRetailSolutions/>[cid:image003.png@01D2DEDA.41EDDC70]<https://twitter.com/MainspringPOS> [cid:image004.png@01D2DEDA.41EDDC70] <http://www.linkedin.com/company/576462>  [cid:image005.png@01D2DEDA.41EDDC70] <mailto:support@mainspring.net>

**Comment by MikeRitchie** [comment]
If you've charged the full order amount to the customer prior to calling the API (via authorize.net or paypal), then you would not want to mark final pmt ="Y". Final payment is meant as a credit card that  should be used by Counterpoint to charge the final outstanding order balance due when releasing the order in Counterpoint. If you've already charged the full amount outside of Counterpoint, then I'd ensure:

- FINAL_PMT is set to "N" or omitted from the payment record
- The paycode you are passing into Counterpoint is not a credit card type paycode
- Make sure that everything you pass in balances. The API is going to sum the PRC of each line (or use PRICE-1 for the item if PRC is not provided, which I wouldn't recommend in this case), and sum the total tax passed into the API. The total sum AMT of the payment(s) passed in should match the sum of the lines and taxes. 

If all the above are true, then the order in Counterpoint should be fully paid and balanced, and can be released however the user chooses.

**Comment by Bflatt** [comment]
Mike we have backed our insert down to no taxes or freight and this is the resulting table queries.  This order will not post the payment line or the subsequent release.   The distribution are out of balance.  I have attached out developers insert

Mike this is a query from ps_doc_hdr_tot  doc id 202108350449 and 202108350448 are the result of an matching order placed in CounterPoint.  107474108436680 and 107474108265480  is the result of order inserted from woo.   You see the amount due on the tot_typ S for the inverted order is -24.00


Ps_doc_hdr_tot

[cid:image001.png@01D306BE.11A4EB10]

Vi_ps_doc_hdr  sal_amt_due and amt_due are incorrect.   Doc_id 107474108265480 - TKT 104247 is the resulting deposit ticket which is created by CounterPoint.  We are not inserting this. It is automatically created.

[cid:image012.png@01D306BF.04E84F10]



[cid:image001.jpg@01D2DEDA.41EDDC70]

Bill Flatt
Mainspring, LLC
6060 S American Plaza St E | Suite 300 | Tulsa, OK | 74135
Phone: 800.865.1427 x2827 | Local: 918.317.0707 | Direct: 918.960.2827
bflatt@mainspring.net<mailto:bflatt@mainspring.net> | www.mainspring.net<http://www.mainspring.net> | Need Help?<mailto:support@mainspring.net>
[cid:image002.png@01D2DEDA.41EDDC70]<https://www.facebook.com/MainSpringRetailSolutions/>[cid:image003.png@01D2DEDA.41EDDC70]<https://twitter.com/MainspringPOS> [cid:image004.png@01D2DEDA.41EDDC70] <http://www.linkedin.com/company/576462>  [cid:image005.png@01D2DEDA.41EDDC70] <mailto:support@mainspring.net>

**Comment by Bflatt** [comment]
This is the whole picture of resulting tables with cp order insert doc id’s as 202* and developer doc insert as doc_id’s 107474*    deposit tickets start with 104*  order docs are 700*

[cid:image011.png@01D306C0.56ED34F0]

[cid:image001.jpg@01D2DEDA.41EDDC70]

Bill Flatt
Mainspring, LLC
6060 S American Plaza St E | Suite 300 | Tulsa, OK | 74135
Phone: 800.865.1427 x2827 | Local: 918.317.0707 | Direct: 918.960.2827
bflatt@mainspring.net<mailto:bflatt@mainspring.net> | www.mainspring.net<http://www.mainspring.net> | Need Help?<mailto:support@mainspring.net>
[cid:image002.png@01D2DEDA.41EDDC70]<https://www.facebook.com/MainSpringRetailSolutions/>[cid:image003.png@01D2DEDA.41EDDC70]<https://twitter.com/MainspringPOS> [cid:image004.png@01D2DEDA.41EDDC70] <http://www.linkedin.com/company/576462>  [cid:image005.png@01D2DEDA.41EDDC70] <mailto:support@mainspring.net>

**Comment by Bflatt** [comment]
We have gone back to basic and are attempting to insert a document exactly matching the sample 
[test insert.txt](https://github.com/NCRCounterpointAPI/APIGuide/files/1180627/test.insert.txt)  

THis is our  response.  These fields are in the insert usr_id and doc_typ  
{
    "ResponseStatus": {
        "ErrorCode": "NotNull",
        "Message": "'P S_ D O C_ H D R. D O C_ T Y P' must not be empty.",
        "Errors": [
            {
                "ErrorCode": "NotNull",
                "FieldName": "PS_DOC_HDR.DOC_TYP",
                "Message": "'P S_ D O C_ H D R. D O C_ T Y P' must not be empty.",
                "Meta": {
                    "PropertyName": "P S_ D O C_ H D R. D O C_ T Y P"
                }
            },
            {
                "ErrorCode": "NotNull",
                "FieldName": "PS_DOC_HDR.USR_ID",
                "Message": "'P S_ D O C_ H D R. U S R_ I D' must not be empty.",
                "Meta": {
                    "PropertyName": "P S_ D O C_ H D R. U S R_ I D"
                }
            }
        ]
    }
}

**Comment by Bflatt** [comment]
I removed cust_no from my insert and the document will insert.  the result is the same.  the deposit payment line will post but creates out of balance distributions by the amount of the deposit.  and How are we supposed to insert to the correct customer is we can't include the cust_no in the doc_hdr section?

**Comment by Bflatt** [comment]
Mike,   This was working a week ago and now it it not.   Something changed on the API

**Comment by Bflatt** [comment]
Mike,

I have created an manual insert of a test order EXACTLY matching the sample in the api documentation and the issue posting a deposit ticket still persists.  The inserted document will post the deposit ticket created on insert but with out of balance distributions.  The inserted order will release and post correctly.   Our only remaining issue is the automatically created deposit ticket.

I have attached sheet detailing the sample from the api documentation and our sample insert which produces the results below. If you could please review the insert for any errors on our part.   Our example does not include tax or misc charge but when included it produces the same results.

VI_PS_DOC_LIN ROWS  match exactly between CounterPoint and Insert order

From vi_ps_doc_hdr

[cid:image012.jpg@01D306F8.72AA8430]
Highlighted fields are from the resulting payment line created on insert of the test document.
202308489600 is from a document entered in Counterpoint.
107474108884216 is from our test insert.
The other two documents are the resulting orders and they match exactly on every other field in the table.

PS_DOC_HDR_ORIG_DOC  Which is generated automatically on insert

[cid:image013.jpg@01D306F8.72AA8430]
Every other field matches exactly


PS_DOC_HDR_TOT Which is not a part of the api doc as a required insert so we are not including any insert fields.

[cid:image014.jpg@01D306F8.72AA8430]

AMT_DUE is a negative in the amount of the payment applied.

Initial posting of the drawer after order insert.  This posting would include the Order deposit received.
[cid:image016.jpg@01D306F8.72AA8430]


Resulting distributions -  No deposit is listed in the summary and no liability side distribution is created.

[cid:image024.png@01D306F2.357FB310]
[cid:image028.png@01D306F2.357FB310]



Expected result

[cid:image026.jpg@01D306F8.72AA8430]







[cid:image001.jpg@01D2DEDA.41EDDC70]

Bill Flatt
Mainspring, LLC
6060 S American Plaza St E | Suite 300 | Tulsa, OK | 74135
Phone: 800.865.1427 x2827 | Local: 918.317.0707 | Direct: 918.960.2827
bflatt@mainspring.net<mailto:bflatt@mainspring.net> | www.mainspring.net<http://www.mainspring.net> | Need Help?<mailto:support@mainspring.net>
[cid:image002.png@01D2DEDA.41EDDC70]<https://www.facebook.com/MainSpringRetailSolutions/>[cid:image003.png@01D2DEDA.41EDDC70]<https://twitter.com/MainspringPOS> [cid:image004.png@01D2DEDA.41EDDC70] <http://www.linkedin.com/company/576462>  [cid:image005.png@01D2DEDA.41EDDC70] <mailto:support@mainspring.net>

**Comment by Bflatt** [comment]
This issue is NOT corrected with the 2.0 API.   Payment inserts with FInal_PMT='N' and AMT included still result in an improperly formed Payment ticket.

**Comment by MikeRitchie** [comment]
This will be addressed in an upcoming 2.1 release coming very soon. Date will be shared as soon as it is available.
