### ISSUE TITLE
Cannot insert or see any ship to addresses

### ISSUE THREAD

**Issue by Bflatt** [NCRCounterpointAPI/APIGuide#44]
We are attempting a patch and post to any ship to address.  
We cannot get any ship-to  to return in a get or  post/patch to work .  

Array
(
    [AR_CUST] => Array
        (
            [NAM] => Bill Flatt
            [FST_NAM] => Bill
            [LST_NAM] => Flatt
            [EMAIL_ADRS_1] => bflatt@anydomain.com
            [ADRS_1] => 102 ct
            [ADRS_2] => 
            [CITY] => okc
            [STATE] => GA
            [ZIP_COD] => 11111
            [CNTRY] => US
            [PHONE_1] => 
            [AR_SHIP_ADRS] => Array
                (
                    [SHIP_ADRS_ID] => (DEFAULT)
                    [NAM] => Bill Flatt
                    [SHIP_NAM_TYP] => B
                    [FST_NAM] => Bill
                    [LST_NAM] => Flatt
                    [EMAIL_ADRS_1] => bflatt@anydomain.com
                    [ADRS_1] => 102
                    [ADRS_2] => 
                    [CITY] => OKC
                    [STATE] => GA
                    [ZIP_COD] => 11111
                    [CNTRY] => US
                )

        )

    [ErrorCode] => SUCCESS
)

**Comment by Bflatt** [comment]
After further review,  customer notes are also not returned with the Get Customers  this is the return for the insert above.  We can insert and patch primary address or note.  We can't post get or patch ship-to address ,or get note.
![image](https://user-images.githubusercontent.com/28633209/28783557-b5735292-75de-11e7-87f8-59aa3ebed5f4.png)

**Comment by Bflatt** [comment]
This issues IS corrected with the 2.0 API

**Comment by MikeRitchie** [comment]
Closing as corrected in API 2.0
