### ISSUE TITLE
 404 error after installation.

### ISSUE THREAD

**Issue by khomenkodima** [NCRCounterpointAPI/APIGuide#45]
Hello, 
I've installed API server server as explained in guide, but I get 404 error when login page is opened in browser.
![screenshot_1 1](https://user-images.githubusercontent.com/11499492/28831070-51504618-76e1-11e7-8eb8-602161d8a061.png)

how to debug such problem ?

**Comment by MikeRitchie** [comment]
Please see Issue #2:

https://github.com/NCRCounterpointAPI/APIGuide/issues/2

I believe this is what you're experiencing and it includes a workaround.

**Comment by khomenkodima** [comment]
Yes, it helped, thanks.
