### ISSUE TITLE
Magento Integration 

### ISSUE THREAD

**Issue by khomenkodima** [NCRCounterpointAPI/APIGuide#46]
Hello,
I’m going implement payments functionality for online store based on Magento using NCR API. I see a lot of API methods https://github.com/NCRCounterpointAPI/APIGuide/tree/master/Endpoints , do you have any diagram that explains flow to make payment using Credit Card using NCR API.

**Comment by MikeRitchie** [comment]
Are you interested in the API processing the payment, or is the payment being processed outside of the API, and you're trying to insert the payment information into Counterpoint (without Counterpoint processing the payment)?

**Comment by khomenkodima** [comment]
Hello,
Ideally I need to implement payment using  API processing. Is it possible ?

**Comment by khomenkodima** [comment]
Thanks for help. Could you confirm my vision, that we will need to setup Windows server with NCR API for processing payments?
Our store is running on Linux, is there NCR API server for linux as well ?

**Comment by MikeRitchie** [comment]
Correct, currently the API server only runs on windows.
