### ISSUE TITLE
API returning ArgumentException for all requests

### ISSUE THREAD

**Issue by aaijtm** [NCRCounterpointAPI/APIGuide#47]
I am trying some testing this evening and all requests, including ones that have worked previously are returning
{
    "ResponseStatus": {
        "ErrorCode": "ArgumentException",
        "Message": "An item with the same key has already been added.",
        "StackTrace": "   at System.ThrowHelper.ThrowArgumentException(ExceptionResource resource)\r\n   at System.Collections.Generic.Dictionary`2.Insert(TKey key, TValue value, Boolean add)\r\n   at CPAPI.Common.RegistrationIniBusiness.ValidateRegistrationFile(String dbName)\r\n   at CPAPI.Common.RegIniAttribute.Execute(IRequest req, IResponse res, Object requestDto)\r\n   at ServiceStack.RequestFilterAttribute.RequestFilter(IRequest req, IResponse res, Object requestDto)\r\n   at ServiceStack.ServiceStackHost.ApplyRequestFiltersSingle(IRequest req, IResponse res, Object requestDto)\r\n   at ServiceStack.ServiceStackHost.ApplyRequestFilters(IRequest req, IResponse res, Object requestDto)\r\n   at ServiceStack.Host.RestHandler.ProcessRequestAsync(IRequest httpReq, IResponse httpRes, String operationName)"
    }
}

**Comment by MikeRitchie** [comment]
I can think of two possibilities to check:
1. Maybe your registration.ini file (In the Top Level Directory) has gotten corrupt.
2. Maybe you somehow have registered the same company name twice with the API (Login as API administrator and check companies)

**Comment by MikeRitchie** [comment]
Have you been able to verify the above suggestions? I've not heard reports of this from others so I suspect this may be something specific to your environment or config. The error you're getting is thrown from code that checks your registration.ini file, so it's likely related to that.

**Comment by MikeRitchie** [comment]
Closing. Please advise if you need to reopen.

**Comment by blueoceanyyc** [comment]
Hello Mike - Can you reopen this issue? We have a client using the API and they rebooted their sever last night and now all our API requests are getting this exact exception/error message. The API has been working for the past year and no changes were made to the api registration files. We double checked and the api license files do not expire until Aug 30, 2019. In our setup, we have our main company and our test/practice company but the names are different. Please advise. Thanks!
