### ISSUE TITLE
Insert document with Credit card as paycode

### ISSUE THREAD

**Issue by Bflatt** [NCRCounterpointAPI/APIGuide#48]
We are attempting to insert a document with a credit card as  paycode.  Our target store has a Active Securepay account and will process  local transactions in CP.   I have attached my insert test with the cc # redacted.   

[Test CC insert.txt](https://github.com/NCRCounterpointAPI/APIGuide/files/1235321/Test.CC.insert.txt)

Any assistance is greatly appreciated. 

{
    "Documents": [],
    "ErrorCode": "ERROR_UNKNOWN",
    "Message": "An error occurred during AddDocument POST: Could not load type 'NCR.Counterpoint.Payments.EdcProcessors.EdcMethodResult' from assembly 'NCR.Counterpoint.Payments.EdcProcessors, Version=1.0.0.0, Culture=neutral, PublicKeyToken=72771d0b7fd3788a'.,    at CPAPI.Business_85.DocumentBusiness_85.ProcessCreditPayment(PS_DOC_PMT payment, PS_STR store)\r\n   at CPAPI.Business_85.DocumentBusiness_85.AuthorizeFinalPayments(PS_DOC_HDR document)\r\n   at CPAPI.Business_85.DocumentBusiness_85.PrepareAndSaveOrder(PS_DOC_HDR document, PS_TAX tax, DocumentKey OrderKey, DocumentKey TicketKey, Boolean MultipleDocs)\r\n   at CPAPI.Business_85.DocumentBusiness_85.SplitMixedDocumentAndSave(PS_DOC_HDR document, PS_TAX tax, IM_CTL itemControl)\r\n   at CPAPI.Business_85.DocumentBusiness_85.SaveMixedDocument(PS_DOC_HDR document, PS_TAX tax)\r\n   at CPAPI.Business_85.DocumentBusiness_85.AddDocument(PS_DOC_HDR_POST documentPost, PS_TAX_VIEW taxView, String workgroup)"
}

**Comment by Bflatt** [comment]
this issue is NOT corrected with the 2.0 api

**Comment by Bflatt** [comment]
Mike,  Good news is we can insert a credit card payment with api 2.0 and 8.5.2.x  Bad news is we cannot insert same payment into 8.5.3.x we receive the attached error  {
    "Documents": [],
    "ErrorCode": "ERROR_UNKNOWN",
    "Message": "An error occurred during AddDocument POST: Cannot insert the value NULL into column 'TRANS_TYP', table 'ECOMM853.dbo.PS_DOC_PMT_RCPT'; column does not allow nulls. INSERT fails.\r\nThe statement has been terminated.,    at System.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)\r\n   at System.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose)\r\n   at System.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady)\r\n   at System.Data.SqlClient.SqlCommand.FinishExecuteReader(SqlDataReader ds, RunBehavior runBehavior, String resetOptionsString, Boolean isInternal, Boolean forDescribeParameterEncryption)\r\n   at System.Data.SqlClient.SqlCommand.RunExecuteReaderTds(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, Boolean async, Int32 timeout, Task& task, Boolean asyncWrite, Boolean inRetry, SqlDataReader ds, Boolean describeParameterEncryptionRequest)\r\n   at System.Data.SqlClient.SqlCommand.RunExecuteReader(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, String method, TaskCompletionSource`1 completion, Int32 timeout, Task& task, Boolean& usedCache, Boolean asyncWrite, Boolean inRetry)\r\n   at System.Data.SqlClient.SqlCommand.InternalExecuteNonQuery(TaskCompletionSource`1 completion, String methodName, Boolean sendToPipe, Int32 timeout, Boolean& usedCache, Boolean asyncWrite, Boolean inRetry)\r\n   at System.Data.SqlClient.SqlCommand.ExecuteNonQuery()\r\n   at ServiceStack.OrmLite.OrmLiteWriteCommandExtensions.Insert[T](IDbCommand dbCmd, T obj, Boolean selectIdentity)\r\n   at ServiceStack.OrmLite.OrmLiteExecFilter.Exec[T](IDbConnection dbConn, Func`2 filter)\r\n   at CPAPI.V853.DocumentRepository_853.CPAPI.V853.IDocumentRepository.AddDocument(PS_DOC_HDR document)\r\n   at CPAPI.V853.DocumentBusiness_853.PrepareAndSaveOrder(PS_DOC_HDR document, PS_TAX tax, DocumentKey OrderKey, DocumentKey TicketKey, Boolean MultipleDocs)\r\n   at CPAPI.V853.DocumentBusiness_853.SplitMixedDocumentAndSave(PS_DOC_HDR document, PS_TAX tax, IM_CTL itemControl)\r\n   at CPAPI.V853.DocumentBusiness_853.SaveMixedDocument(PS_DOC_HDR document, PS_TAX tax)\r\n   at CPAPI.V853.DocumentBusiness_853.AddDocument(PS_DOC_HDR_POST documentPost, PS_TAX_VIEW taxView, String workgroup)"
}

**Comment by MikeRitchie** [comment]
Bill can you send me your API logfile that contains an instance of this?

**Comment by Bflatt** [comment]
Where 8.5.3 will not take the doc insert for a cc?

[cid:image001.jpg@01D2DEDA.41EDDC70]

Bill Flatt
Mainspring, LLC
6060 S American Plaza St E | Suite 300 | Tulsa, OK | 74135
Phone: 800.865.1427 x2827 | Local: 918.317.0707 | Direct: 918.960.2827
bflatt@mainspring.net<mailto:bflatt@mainspring.net> | www.mainspring.net<http://www.mainspring.net> | Need Help?<mailto:support@mainspring.net>
[cid:image002.png@01D2DEDA.41EDDC70]<https://www.facebook.com/MainSpringRetailSolutions/>[cid:image003.png@01D2DEDA.41EDDC70]<https://twitter.com/MainspringPOS> [cid:image004.png@01D2DEDA.41EDDC70] <http://www.linkedin.com/company/576462>  [cid:image005.png@01D2DEDA.41EDDC70] <mailto:support@mainspring.net>

**Comment by Bflatt** [comment]
Mike,

I stopped the api to move the current log files so I could have a clean log set.  I restarted and proceed the charge again on 8.5.3 and the charge payment processed correctly.


I will do more testes over the weekend but it appears I was mistaken.  8.5.3 will take an api credit card payment.

Thanks for all your assistance.

Bill


[cid:image001.jpg@01D2DEDA.41EDDC70]

Bill Flatt
Mainspring, LLC
6060 S American Plaza St E | Suite 300 | Tulsa, OK | 74135
Phone: 800.865.1427 x2827 | Local: 918.317.0707 | Direct: 918.960.2827
bflatt@mainspring.net<mailto:bflatt@mainspring.net> | www.mainspring.net<http://www.mainspring.net> | Need Help?<mailto:support@mainspring.net>
[cid:image002.png@01D2DEDA.41EDDC70]<https://www.facebook.com/MainSpringRetailSolutions/>[cid:image003.png@01D2DEDA.41EDDC70]<https://twitter.com/MainspringPOS> [cid:image004.png@01D2DEDA.41EDDC70] <http://www.linkedin.com/company/576462>  [cid:image005.png@01D2DEDA.41EDDC70] <mailto:support@mainspring.net>

**Comment by MikeRitchie** [comment]
Thanks, Please let us know what you find. I reproduced the exact error you were seeing with a debug build, but that looks like it was due to my debug build missing some dlls. The production 2.0 install I used seemed to work against all supported versions of Counterpoint.

**Comment by Bflatt** [comment]
Yes.   THis is working now.
