### ISSUE TITLE
Error 404 when accessing the Web admin login

### ISSUE THREAD

**Issue by cyrusbaratt** [NCRCounterpointAPI/APIGuide#5]
https://xyz:52000/app/index.htm#/login  

Service is running....

Any help will be appreciated.

**Comment by MikeRitchie** [comment]
Please see issue #2, it looks like the same issue: https://github.com/NCRCounterpointAPI/APIGuide/issues/2
There's a workaround given in the thread there, a permanent fix will come in the next release.

Please let me know if the workaround addresses your issue.

**Comment by cyrusbaratt** [comment]
Thank you!  Now I am prompted for user and password.    I did not set a password before.  Service is running under local system.

**Comment by cyrusbaratt** [comment]
Greetings,

I followed your recommendations.  Now, I get prompted for user and password.  It does not accept the windows password I am using.  The CounterPoint API service is running as localsystem.

I would appreciate any assistance.

Thank you
Cyrus Baratt
(972) 991-8162  Ext 104

**Comment by MikeRitchie** [comment]
Hello,
You do not login to the API admin console with windows credentials. The initial admin user and password are documented in the "Creating System Administrators" section on this page:

https://github.com/NCRCounterpointAPI/APIGuide/blob/master/InstallationAndConfiguration/Configuring.md

On initial login, you'll be required to change your password.

**Comment by MikeRitchie** [comment]
Hello,
Did the above post help resolve the issue? Please let me know if it's OK to close this.

**Comment by cyrusbaratt** [comment]
Yes, it did.

Appreciated
Cyrus Baratt
(972) 991-8162  Ext 104

**Comment by MikeRitchie** [comment]
Closing.
