### ISSUE TITLE
ErrorCode ERROR_UNKNOWN

### ISSUE THREAD

**Issue by bsweitzer** [NCRCounterpointAPI/APIGuide#50]
Receiving error even on basic JSON (shown at bottom).

Customer POST error:
POST https://96.65.91.107:52001/Customer
{
    "ErrorCode": "ERROR_UNKNOWN",
    "Message": "An error occurred during AddCustomer: Object reference not set to an instance of an object.,    at System.Object.GetType()\r\n   at ServiceStack.OrmLite.OrmLiteReadCommandExtensions.SetFilter[T](IDbCommand dbCmd, String name, Object value)\r\n   at ServiceStack.OrmLite.OrmLiteReadCommandExtensions.SingleById[T](IDbCommand dbCmd, Object value)\r\n   at ServiceStack.OrmLite.OrmLiteExecFilter.Exec[T](IDbConnection dbConn, Func`2 filter)\r\n   at CPAPI.Repositories_85.CustomerRepository_85.CPAPI.Repositories_85.ICustomerRepository.GetCustomerById(String custNo)\r\n   at CPAPI.Business_85.CustomerBusiness_85.AddCustomer(AR_CUST_POST customerEdit, String workgroupId)"
}
 
Document POST error:
POST https://96.65.91.107:52001/Document
{
    "Documents": [],
    "ErrorCode": "ERROR_UNKNOWN",
    "Message": "An error occurred during AddDocument POST: Object reference not set to an instance of an object.,    at CPAPI.Business_85.DocumentBusiness_85.PopulateDefaults(PS_DOC_HDR documentHeader, String workgroupId)\r\n   at CPAPI.Business_85.DocumentBusiness_85.AddDocument(PS_DOC_HDR_POST documentPost, PS_TAX_VIEW taxView, String workgroup)"
}

JSON:

{
  "AR_CUST": {
    "NAM": "Clark Kent",
    "FST_NAM": "Clark",
    "LST_NAM": "Kent",
    "CUST_TYP": "C",
    "STR_ID" : "101",
    "SLS_REP": "9998",
    "CUST_NAM_TYP" : "P",
    "AR_CUST_NOTE": [
      {
        "Note_ID": "ADDED_85",
        "NOTE_TXT": "Be careful, Clark Kent is Superman."
      }
    ],
    "AR_SHIP_ADRS": [
      {
        "SHIP_ADRS_ID": "ADDRESS_1",
        "NAM": "HOME",
        "SHIP_NAM_TYP": "B"
      },
      {
        "SHIP_ADRS_ID": "ADDRESS_2",
        "NAM": "WORK",
        "SHIP_NAM_TYP": "B"
      }
    ]
  }
}

Even just using a basic request with the only two required fields (according to the API docs) is giving the same error.
{
  "AR_CUST": {
    "FST_NAM": "Clark",
    "LST_NAM": "Kent"
  }
}

**Comment by Bflatt** [comment]
BSWeitzer.  I think you should review your doc insert as ar_cust is not a part of a dOc insert.  See partial SAMPLE below.  You should create the customer first if the customer is new and insert a doc with Bill contact and Ship contact as below with the customer on the doc insert as the existing customer. 

{
 "PS_DOC_HDR":{
   "STR_ID":"2",
   "STA_ID":"ECOMM",
   "DRW_ID":"ECOMM",
   "TKT_TYP":"T",
   "CUST_NO":"123456",
   "DOC_TYP":"O",
   "USR_ID":"MGR",
   "TAX_COD":"WEBOK",
   "NORM_TAX_COD":"WEBOK",
   "SHIP_VIA_COD":"C",
   "BILL_TO_CONTACT":{
     "FST_NAM":"bob",
     "LST_NAM":"barker",
     "NAM":"BOB BARKER",
     "NAM_UPR":"BOB BARKER",
     "ADRS_1":"111 ADDRESS 1",
     "CITY":"SOME CITY",
     "ZIP_COD":"11111",
     "STATE":"ok",
     "PHONE_1":"(800) 5554-7710",
     "NAM_TYP":"P"
   },
   "SHIP_TO_CONTACT":{
   "FST_NAM":"bob",
     "LST_NAM":"barker",
     "NAM":"BOB BARKER",
     "NAM_UPR":"BOB BARKER",
     "ADRS_1":"111 ADDRESS 1",
     "CITY":"SOME CITY",
     "ZIP_COD":"11111",
     "STATE":"ok",
     "PHONE_1":"(800) 5554-7710",
     "NAM_TYP":"P"
   },
   "PS_DOC_NOTE":[
     {
       "NOTE_ID":"CPSHOP",
       "NOTE":"ORDER NOTES"
     }

..ETC...
