### ISSUE TITLE
Attempt to pull a known document id fails with error  invalid Column name OFFLINE_GUID

### ISSUE THREAD

**Issue by Bflatt** [NCRCounterpointAPI/APIGuide#52]
All other end points for getting data are working. 

{
    "ResponseStatus": {
        "ErrorCode": "SqlException",
        "Message": "Invalid column name 'OFFLINE_GUID'.",
        "StackTrace": "[DocumentRequest: 8/31/2017 6:01:01 PM]:\n[REQUEST: {DocID:101143425428}]\nSystem.Data.SqlClient.SqlException (0x80131904): Invalid column name 'OFFLINE_GUID'.\r\n   at System.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)\r\n   at System.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose)\r\n   at System.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady)\r\n   at System.Data.SqlClient.SqlDataReader.TryConsumeMetaData()\r\n   at System.Data.SqlClient.SqlDataReader.get_MetaData()\r\n   at System.Data.SqlClient.SqlCommand.FinishExecuteReader(SqlDataReader ds, RunBehavior runBehavior, String resetOptionsString, Boolean isInternal, Boolean forDescribeParameterEncryption)\r\n   at System.Data.SqlClient.SqlCommand.RunExecuteReaderTds(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, Boolean async, Int32 timeout, Task& task, Boolean asyncWrite, Boolean inRetry, SqlDataReader ds, Boolean describeParameterEncryptionRequest)\r\n   at System.Data.SqlClient.SqlCommand.RunExecuteReader(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, String method, TaskCompletionSource`1 completion, Int32 timeout, Task& task, Boolean& usedCache, Boolean asyncWrite, Boolean inRetry)\r\n   at System.Data.SqlClient.SqlCommand.RunExecuteReader(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, String method)\r\n   at System.Data.SqlClient.SqlCommand.ExecuteReader(CommandBehavior behavior, String method)\r\n   at ServiceStack.OrmLite.OrmLiteResultsFilterExtensions.ExprConvertToList[T](IDbCommand dbCmd, String sql, IEnumerable`1 sqlParams, HashSet`1 onlyFields)\r\n   at ServiceStack.OrmLite.ReadExpressionCommandExtensions.Select[T](IDbCommand dbCmd, Expression`1 predicate)\r\n   at ServiceStack.OrmLite.OrmLiteExecFilter.Exec[T](IDbConnection dbConn, Func`2 filter)\r\n   at CPAPI.Repositories_85.DocumentRepository_85.CPAPI.Repositories_85.IDocumentRepository.GetDocumentById(Int64 DocId)\r\n   at CPAPI.Business_85.DocumentBusiness_85.GetDocumentById(Int64 documentId)\r\n   at CPAPI.Services.DocumentService.Get(DocumentRequest request)\r\n   at ServiceStack.Host.ServiceRunner`1.Execute(IRequest request, Object instance, TRequest requestDto)\r\nClientConnectionId:36e58c56-e9f1-424e-8361-544e0efef8bb\r\nError Number:207,State:1,Class:16",
        "Errors": []
    }
}

**Comment by Bflatt** [comment]
Has the api been tested against a system supporting offline stations as this appears to be a problem with a offline column?

**Comment by MikeRitchie** [comment]
Just to clarify are you referring to the API being installed on the offline workstation itself, or on the server side connecting to the server DB? The API is not currently designed to be installed and connected to an offline DB

**Comment by Bflatt** [comment]
I am attempting to get a particular document on the main data not the offline station.  i can insert documents and get any other end point but this one as far as I have tested.

**Comment by Bflatt** [comment]
I am attempting to get a particular document on the main data not the offline station. I can insert documents and get any other end point but this one as far as I have tested.

[cid:image001.jpg@01D2DEDA.41EDDC70]

Bill Flatt
Mainspring, LLC
6060 S American Plaza St E | Suite 300 | Tulsa, OK | 74135
Phone: 800.865.1427 x2827 | Local: 918.317.0707 | Direct: 918.960.2827
bflatt@mainspring.net<mailto:bflatt@mainspring.net> | www.mainspring.net<http://www.mainspring.net> | Need Help?<mailto:support@mainspring.net>
[cid:image002.png@01D2DEDA.41EDDC70]<https://www.facebook.com/MainSpringRetailSolutions/>[cid:image003.png@01D2DEDA.41EDDC70]<https://twitter.com/MainspringPOS> [cid:image004.png@01D2DEDA.41EDDC70] <http://www.linkedin.com/company/576462>  [cid:image005.png@01D2DEDA.41EDDC70] <mailto:support@mainspring.net>

**Comment by Bflatt** [comment]
this is on an 8.5.0.0 install.  I just verified.  I believe an update will correct.

**Comment by mbantug** [comment]
We have coded and tested a fix for this which will be in the next API release.
