### ISSUE TITLE
403 Forbidden

### ISSUE THREAD

**Issue by khomenkodima** [NCRCounterpointAPI/APIGuide#53]
Hello,
I've installed NCR API, added key, added company and assigned company admin as described in guide. I can login to web intrface using company admin credentials, but when try to make API call

wget --no-check-certificate --user=COMPANY.ADMIN --password=PASSWORD https://vcounterpoint:52000/Customers

I got such error:

--2017-09-01 22:48:16--  https://vcounterpoint:52000/Customers
Resolving vcounterpoint... 209.150.86.11
Connecting to vcounterpoint|209.150.86.11|:52000... connected.
WARNING: cannot verify vcounterpoint's certificate, issued by 'CN=VCOUNTERPOINT':
  Self-signed certificate encountered.
HTTP request sent, awaiting response... 401 Unauthorized
Authentication selected: basic realm="/auth/basic"
Reusing existing connection to vcounterpoint:52000.
HTTP request sent, awaiting response... 403 Forbidden
2017-09-01 22:48:17 ERROR 403: Forbidden.

Could you advise how to solve this problem ?

**Comment by MikeRitchie** [comment]
By default, the API installs and uses a self signed certificate used for SSL/TLS. Many client applications will warn or prevent access to a server using a self-signed certificate, as they can't be trusted to verify the identify of the server. Some more information is on this page:
https://github.com/NCRCounterpointAPI/APIGuide/blob/master/InstallationAndConfiguration/Installing.md

You do have the option of purchasing a signed certificate from a trusted certificate issuing authority and replacing the self-signed certificate.

You may also be able to move the certificate to the Trusted certificate authorities certificate store on the client machine (which may or may not also be the server)

Finally, you may be able to configure your client application to allow connections to servers with self-signed certificates. That is specific to your wget tool so you would need to consult documentation on that tool to see if that's an option.

**Comment by MikeRitchie** [comment]
Closing. Please advise if you need to reopen
