### ISSUE TITLE
Reset API admin password. 

### ISSUE THREAD

**Issue by Bflatt** [NCRCounterpointAPI/APIGuide#54]
Is there a way to reset the API admin password in the event we do not know the password?

**Comment by MikeRitchie** [comment]
Not at the moment, as the API has no access to means such as email required to securely reset the password.

The best way to do this currently is to delete the sysadmin.sqlite file from the "App_Data" folder. This will effectively take you back as if you're a first time login, you can then use the default password and re-establish your admin account.  However, you'll need to re-establish your connection to Counterpoint companies (company setup). The information stored within each Counterpoint DB, such as roles, will be retained, however.
