### ISSUE TITLE
API key request

### ISSUE THREAD

**Issue by bsweitzer** [NCRCounterpointAPI/APIGuide#55]
A client put in a request for the API keys two days ago.  How long does it usually take to get the keys emailed back?

**Comment by MikeRitchie** [comment]
All key requests we're seeing have been handled at this time. If you still don't have your key, can you provide some information to help me identify the proper request?

**Comment by bsweitzer** [comment]
The client received it later the same day I sent this request.  Thank you.


Beverli Sweitzer
Software Support Specialist
Phone  800-944-0917 ext 209
Fax 330-830-9146

[logo_llc_Email]
