### ISSUE TITLE
SqlDateTime overflow.

### ISSUE THREAD

**Issue by khomenkodima** [NCRCounterpointAPI/APIGuide#56]
Hello,
when I try to insert document I'm getting such error:

An error occurred during AddDocument POST: SqlDateTime overflow. Must be between 1/1/1753 12:00:00 AM and 12/31/9999 11:59:59 PM.

Looks like I can't manage that with API call parameters - there are nothing related to time. Please advise how debug such problem ? thanks.

**Comment by khomenkodima** [comment]
All stack trace:

{"Documents":[],"ErrorCode":"ERROR_UNKNOWN","Message":"An error occurred during AddDocument POST: SqlDateTime overflow. Must be between 1/1/1753 12:00:00 AM and 12/31/9999 11:59:59 PM.,    at System.Data.SqlClient.TdsParser.TdsExecuteRPC(SqlCommand cmd, _SqlRPC[] rpcArray, Int32 timeout, Boolean inSchema, SqlNotificationRequest notificationRequest, TdsParserStateObject stateObj, Boolean isCommandProc, Boolean sync, TaskCompletionSource`1 completion, Int32 startRpc, Int32 startParam)\r\n   at System.Data.SqlClient.SqlCommand.RunExecuteReaderTds(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, Boolean async, Int32 timeout, Task& task, Boolean asyncWrite, SqlDataReader ds, Boolean describeParameterEncryptionRequest)\r\n   at System.Data.SqlClient.SqlCommand.RunExecuteReader(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, String method, TaskCompletionSource`1 completion, Int32 timeout, Task& task, Boolean asyncWrite)\r\n   at System.Data.SqlClient.SqlCommand.InternalExecuteNonQuery(TaskCompletionSource`1 completion, String methodName, Boolean sendToPipe, Int32 timeout, Boolean asyncWrite)\r\n   at System.Data.SqlClient.SqlCommand.ExecuteNonQuery()\r\n   at ServiceStack.OrmLite.OrmLiteWriteCommandExtensions.Insert[T](IDbCommand dbCmd, T obj, Boolean selectIdentity)\r\n   at ServiceStack.OrmLite.OrmLiteExecFilter.Exec[T](IDbConnection dbConn, Func`2 filter)\r\n   at CPAPI.Repositories_846.DocumentRepository_846.CPAPI.Repositories_846.IDocumentRepository.AddDocument(PS_DOC_HDR document)\r\n   at CPAPI.Business_846.DocumentBusiness_846.PrepareAndSaveOrder(PS_DOC_HDR document, PS_TAX tax, DocumentKey OrderKey, DocumentKey TicketKey, Boolean MultipleDocs)\r\n   at CPAPI.Business_846.DocumentBusiness_846.SplitMixedDocumentAndSave(PS_DOC_HDR document, PS_TAX tax, IM_CTL itemControl)\r\n   at CPAPI.Business_846.DocumentBusiness_846.SaveMixedDocument(PS_DOC_HDR document, PS_TAX tax)\r\n   at CPAPI.Business_846.DocumentBusiness_846.AddDocument(PS_DOC_HDR_POST documentPost, PS_TAX_VIEW taxView, String workgroup)"}

**Comment by MikeRitchie** [comment]
Can you provide the JSON you are posting to the call? Please be sure to remove/genericize any sensitive data before posting.

**Comment by khomenkodima** [comment]
I used JSON from
https://github.com/NCRCounterpointAPI/APIGuide/blob/master/Endpoints/POST_Document.md

I've found reason of problem, it was caused by
"CR_CARD_EXP_DAT": "12/2018"
it should be 
CR_CARD_EXP_DAT": "2018-01-01T00:00:00.0000000"
now it works for me.

**Comment by khomenkodima** [comment]
resolved, thanks.
