### ISSUE TITLE
Feature Request: YAML or JSON API Definitions

### ISSUE THREAD

**Issue by langillerr** [NCRCounterpointAPI/APIGuide#57]
It would be quite helpful to have definitions for things like Swagger, API Blueprint, APIMatic, or other such formats.

Seeing as the Postman test client is already created, many of the definitions for these can be generated (for the most part) from the Postman 2.0 collection files.  The main hiccups seem to be around model definition descriptions and tags for segmenting test cases from proper endpoints.

This would allow generation of API clients to jump start projects using many of the widely supported libraries such as swagger-codegen and APIMatic Gen and let users leverage clients like Uni-REST.

This also lends to the possibility of testing endpoints efficiently through CI/CD systems to ensure code stability.

**Comment by MikeRitchie** [comment]
There are a few endpoints that can help with metadata:
* /metadata: As noted, this provides basic metadata in multiple formats
* /postman: This endpoint can be used to import API definitions into the postman client
* /swagger-ui: This is a swagger based page for viewing and consuming metadata

Not all calls are annotated as much as we'd like but the basic data is all there.

**Comment by langillerr** [comment]
Thanks! I didn't realize some of this was there already.

Since the swagger-ui is already there, is it safe to assume there are already swagger definition files as well?

I'd just look myself but we're in the process of setting up our server to install the API. (working off of documentation and setting up libraries in the meantime).

**Comment by MikeRitchie** [comment]
I believe the /resources endpoint has the raw swagger definition.

**Comment by langillerr** [comment]
Just got in, and it does appear to give the definitions in swagger 1.2 and that should work for us for the time being.

Any roadmap for swagger2.0 or swaggerYAML support?

**Comment by MikeRitchie** [comment]
This capability is provided by the ServiceStack framework, which we use to build the API. We'll generally updated to the latest version of ServiceStack at each release, so the next release will likley include swagger 2.0 support. No ETA for that release at the moment.
