### ISSUE TITLE
Cannot insert new customer to 8.4.6.18 with 2.0 api

### ISSUE THREAD

**Issue by Bflatt** [NCRCounterpointAPI/APIGuide#60]
Exact same script works with  8.5.x

{
    "ResponseStatus": {
        "ErrorCode": "NullReferenceException",
        "Message": "An error occurred while trying to access an object of type: UserRoles, Object value is null,    at CPAPI.Common.RepositoryCompanyBase.GetCacheKeyName(Object[] cacheKeyId)",
        "StackTrace": "   at CPAPI.Common.RepositoryCompanyBase.GetCacheKeyName(Object[] cacheKeyId)\r\n   at CPAPI.Common.KeyValueDataRepository.GetValueByName[T](String key)\r\n   at CPAPI.Common.UserRoleBusiness.CheckPermissions(String userId, String path, String verb)\r\n   at CPAPI.Common.RoleAttribute.Execute(IRequest req, IResponse res, Object requestDto)\r\n   at ServiceStack.RequestFilterAttribute.RequestFilter(IRequest req, IResponse res, Object requestDto)\r\n   at ServiceStack.ServiceStackHost.ApplyRequestFiltersSingle(IRequest req, IResponse res, Object requestDto)\r\n   at ServiceStack.ServiceStackHost.ApplyRequestFilters(IRequest req, IResponse res, Object requestDto)\r\n   at ServiceStack.Host.RestHandler.ProcessRequestAsync(IRequest httpReq, IResponse httpRes, String operationName)"
    }
}

insert script 
{
  "AR_CUST": {
    "NAM": "Superman",
    "FST_NAM": "Clark",
    "LST_NAM": "Kent",
    "STR_ID": "CPONLINE",
    "AR_CUST_NOTE": [
      {
        "Note_ID": "ADDED_85",
        "NOTE_TXT": "Be careful, Clark Kent is Superman."
      }
    ],
    "AR_SHIP_ADRS": [
      {
        "SHIP_ADRS_ID": "ADDRESS_1",
        "NAM": "HOME",
        "SHIP_NAM_TYP": "B"
      },
      {
        "SHIP_ADRS_ID": "ADDRESS_2",
        "NAM": "WORK",
        "SHIP_NAM_TYP": "B"
      }
    ]
  }
}

**Comment by Bflatt** [comment]
Verified same basic behavior on second site 8.4.6.18   slightly different error. 
{
    "ErrorCode": "ERROR_UNKNOWN",
    "Message": "An error occurred during AddCustomer: Object reference not set to an instance of an object.,    at ServiceStack.OrmLite.OrmLiteReadCommandExtensions.SetFilter[T](IDbCommand dbCmd, String name, Object value)\r\n   at ServiceStack.OrmLite.OrmLiteReadCommandExtensions.SingleById[T](IDbCommand dbCmd, Object value)\r\n   at ServiceStack.OrmLite.OrmLiteReadApi.<>c__DisplayClass19_0`1.<SingleById>b__0(IDbCommand dbCmd)\r\n   at ServiceStack.OrmLite.OrmLiteExecFilter.Exec[T](IDbConnection dbConn, Func`2 filter)\r\n   at ServiceStack.OrmLite.OrmLiteReadExpressionsApi.Exec[T](IDbConnection dbConn, Func`2 filter)\r\n   at ServiceStack.OrmLite.OrmLiteReadApi.SingleById[T](IDbConnection dbConn, Object idValue)\r\n   at CPAPI.Repositories_846.CustomerRepository_846.CPAPI.Repositories_846.ICustomerRepository.GetCustomerById(String custNo)\r\n   at CPAPI.Business_846.CustomerBusiness_846.CPAPI.Common.ICustomerBusiness.AddCustomer(AR_CUST_POST customerEdit, String workgroupId)"
}

**Comment by MikeRitchie** [comment]
In one of the DB's that isn't working, can you try inserting an explicit workgroup as the first element like this:

{
  "Workgroup": "1",
  "AR_CUST": {
    "NAM": "Superman",
    "FST_NAM": "Clark",
    "LST_NAM": "Kent",
    "STR_ID": "CPONLINE",
    "AR_CUST_NOTE": [
      {
        "Note_ID": "ADDED_85",
        "NOTE_TXT": "Be careful, Clark Kent is Superman."
      }
    ],
    "AR_SHIP_ADRS": [
      {
        "SHIP_ADRS_ID": "ADDRESS_1",
        "NAM": "HOME",
        "SHIP_NAM_TYP": "B"
      },
      {
        "SHIP_ADRS_ID": "ADDRESS_2",
        "NAM": "WORK",
        "SHIP_NAM_TYP": "B"
      }
    ]
  }
}

Make sure that the Workgroup is valid for your DB, and make sure that the SY_WRKGRP record for the workgroup has a valid TMPLT_CUST_NO record in it. For POST /Customer, values that aren't included in the posted JSON come from the template customer.

**Comment by Bflatt** [comment]
Mike, The error returned is the same.

    "ErrorCode": "ERROR_UNKNOWN",
    "Message": "An error occurred during AddCustomer: Object reference not set to an instance of an object.,    at System.Xml.XmlReader.CalcBufferSize(Stream input)\r\n   at System.Xml.XmlTextReaderImpl.InitStreamInput(Uri baseUri, String baseUriStr, Stream stream, Byte[] bytes, Int32 byteCount, Encoding encoding)\r\n   at System.Xml.XmlTextReaderImpl..ctor(String url, Stream input, XmlNameTable nt)\r\n   at System.Xml.XmlDocument.Load(Stream inStream)\r\n   at CPAPI.Model_846.DTOMetadata.GetTableMetadata(String name)\r\n   at CPAPI.Business_846.CustomerExtensions_846.PopulateDefaults(AR_CUST customer, SY_WRKGRP workgroup, AR_CUST templateCustomer)\r\n   at CPAPI.Business_846.CustomerBusiness_846.CPAPI.Common.ICustomerBusiness.AddCustomer(AR_CUST_POST customerEdit, String workgroupId)"

[cid:image001.jpg@01D2DEDA.41EDDC70]

Bill Flatt
Mainspring, LLC
6060 S American Plaza St E | Suite 300 | Tulsa, OK | 74135
Phone: 800.865.1427 x2827 | Local: 918.317.0707 | Direct: 918.960.2827
bflatt@mainspring.net<mailto:bflatt@mainspring.net> | www.mainspring.net<http://www.mainspring.net> | Need Help?<mailto:support@mainspring.net>
[cid:image002.png@01D2DEDA.41EDDC70]<https://www.facebook.com/MainSpringRetailSolutions/>[cid:image003.png@01D2DEDA.41EDDC70]<https://twitter.com/MainspringPOS> [cid:image004.png@01D2DEDA.41EDDC70] <http://www.linkedin.com/company/576462>  [cid:image005.png@01D2DEDA.41EDDC70] <mailto:support@mainspring.net>

**Comment by mbantug** [comment]
We have coded and tested a fix for this which will be in the next API release.
