### ISSUE TITLE
Cannot add new customer

### ISSUE THREAD

**Issue by sazary33** [NCRCounterpointAPI/APIGuide#62]
Hello, I also cannot add a new customer using the newest API. I have a customer template set in my workgroup and I've tried passing in all the arguments mentioned in other open and closed issues such as "Workgroup", etc. Here is the error I am seeing:

{"ErrorCode":"ERROR_UNKNOWN","Message":"An error occurred during AddCustomer: Object reference not set to an instance of an object.,    at System.Object.GetType()\\r\\n   at ServiceStack.OrmLite.OrmLiteReadCommandExtensions.SetFilter[T](IDbCommand dbCmd, String name, Object value)\\r\\n   at ServiceStack.OrmLite.OrmLiteReadCommandExtensions.SingleById[T](IDbCommand dbCmd, Object value)\\r\\n   at ServiceStack.OrmLite.OrmLiteExecFilter.Exec[T](IDbConnection dbConn, Func`2 filter)\\r\\n   at NCR.CP.CPAPI.Base.Repositories.CustomerRepository.NCR.CP.CPAPI.Base.Repositories.ICustomerRepository.GetCustomerById(String custNo)\\r\\n   at NCR.CP.CPAPI.Base.Business.CustomerBusiness.CPAPI.Common.ICustomerBusiness.AddCustomer(AR_CUST_POST customerEdit, String workgroupId)"}

Please let me know of your thoughts on this.

**Comment by MikeRitchie** [comment]
Please reproduce in postman, then use the "code" button in postman to copy & paste information on your API call to this thread (be sure to replace any sensitive customer information with generic information).

![image](https://user-images.githubusercontent.com/12415329/30877758-af447e8e-a2c8-11e7-8c9c-41cab0138290.png)

**Comment by sazary33** [comment]
Hello Mike, I don't know how to explain it I was checking my logs this morning and the add customer code is working. I used STR_ID without the Workgroup and I also used the required fields (First name, last name). Sorry for the inconvenience.
