### ISSUE TITLE
How to get item prices using API?

### ISSUE THREAD

**Issue by baljeetbhardwaj** [NCRCounterpointAPI/APIGuide#64]
Hi,
I want to know how to get item prices using API?
Thanks

**Comment by MikeRitchie** [comment]
If you are adding an item to a line (when using POST /Document), The PRC value you pass in will be honored as the price. If you don't pass in a PRC value, the API will assign the default price (PRC_1) automatically for you (with any location specific price taking precedence over the item level price).

If you just want to retrieve the price, you can get the PRC_1 value from these calls:
GET /Item/{ItemNo}
GET /Items
GET /Items/{locationId} (This is a location specific price, that would override a default item level price)

The API does not currently evaluate price rules (such as BOGO, contract pricing, etc.)

**Comment by baljeetbhardwaj** [comment]
ok thanks Mike.
