### ISSUE TITLE
Inserting quotes to 8.5.2.x

### ISSUE THREAD

**Issue by Bflatt** [NCRCounterpointAPI/APIGuide#68]
On testing inserting a quote document to an 8.5.2.1 data set the error below is returned.  THe same document will correctly insert into a 8.5.3 data set.  This look s exactly like the error on inserting customers to 8.4.6.18 data sets.  

{
    "Documents": [],
    "ErrorCode": "ERROR_UNKNOWN",
    "Message": "An error occurred during AddDocument POST: Object reference not set to an instance of an object.,    at NCR.CP.CPAPI.Base.Business.DocumentExtensions.AddAuditLog(PS_DOC_HDR header, String Activity, String LogEntry, DocumentKey linkedkey)\r\n   at NCR.CP.CPAPI.Base.Business.DocumentBusiness.SaveMixedDocument(PS_DOC_HDR document, PS_TAX tax)\r\n   at NCR.CP.CPAPI.Base.Business.DocumentBusiness.AddDocument(PS_DOC_HDR_POST documentPost, PS_TAX_VIEW taxView, String workgroup)"
}

Insert text  

{
 "PS_DOC_HDR":{
   "STR_ID":"2",
   "STA_ID":"ECOMM",
   "DRW_ID":"ECOMM",
   "TKT_TYP":"T",
   "CUST_NO":"6785447710",
   "DOC_TYP":"Q",
   "USR_ID":"MGR",
   "TAX_COD":"WEBOK",
   "NORM_TAX_COD":"WEBOK",
   "SHIP_VIA_COD":"C",
   "BILL_TO_CONTACT":{
     "FST_NAM":"ALEKSANDAR",
     "LST_NAM":"MILICEVIC",
     "NAM":"Aleksandar Milicevic",
     "NAM_UPR":"ALEKSANDAR MILICEVIC",
     "ADRS_1":"Obilicev veca",
     "ADRS_2":"92130",
     "CITY":"NEW YORK",
     "ZIP_COD":"19000",
     "STATE":"OH",
     "PHONE_1":"(901) 555-2222",
     "NAM_TYP":"P"
   },
   "SHIP_TO_CONTACT":{
     "FST_NAM":"Aleksandar",
     "LST_NAM":"Milicevic",
     "NAM":"Aleksandar Milicevic",
     "ADRS_1":"Obilicev veca",
     "ADRS_2":"92130",
     "CITY":"NEW YORK",
     "ZIP_COD":"19000",
     "STATE":"OH",
     "PHONE_1":"(901) 555-2222",
     "NAM_TYP":"P"
   },
   "PS_DOC_NOTE":[
     {
       "NOTE_ID":"CPSHOP",
       "NOTE":"ORDER NOTES"
     }
   ],
   "PS_DOC_HDR_PROF":{
     "PROF_ALPHA_1":"USPS"
   },
   "PS_DOC_LIN":[
     {
     "LIN_TYP":"S",
     "ITEM_NO":"31770003",
     "PRC":"24.00",
     "USR_ENTD_PRC":"Y",
     "QTY_SOLD":"1"
     },
     {
     "LIN_TYP":"S",
     "ITEM_NO":"31770005",
     "PRC":"24.00",
     "USR_ENTD_PRC":"Y",
     "QTY_SOLD":"1"
     }

     
   ],

    "PS_DOC_HDR_EC":{
    "EC_STR_ID":"0",
    "EC_IMP_DT":"2017-07-26T00:00:00.0000000",
    "EC_IMP_HAD_SPECL_MSGS":"N",
   
    "EC_ORD_TAX_AMT_TOT_EXPECTD":"0",
    "EC_ORD_NO":"9181",
    "EC_CUST_NO":"1",
    "EC_ORD_TOT":"48.00",
    "NXT_EC_SEQ_NO_OFFSET":"1" 
    },
   "PS_DOC_PKG_TRK_NO":[],

  
   "PS_DOC_TAX":[
     {
     "AUTH_COD":"WEBGA",
     "RUL_COD":"WEBGA",
     "TAX_DOC_PART":"O",
     "TAX_AMT":"0",
     "TOT_TXBL_AMT":"48.00"
     }
   ]
 },
 "PS_TAX": {
     "ORD_NORM_TAX_AMT": "0",
     "ORD_TAX_AMT": "0"
 }
}

**Comment by Bflatt** [comment]
Error on 8.4.6.18 data set  attempting to insert same order
{
    "Documents": [],
    "ErrorCode": "ERROR_UNKNOWN",
    "Message": "An error occurred during AddDocument POST: Value does not exist: 2\r\nParameter name: STR_ID,    at CPAPI.Business_846.DocumentBusiness_846.PopulateDefaults(PS_DOC_HDR documentHeader, String workgroupId)\r\n   at CPAPI.Business_846.DocumentBusiness_846.AddDocument(PS_DOC_HDR_POST documentPost, PS_TAX_VIEW taxView, String workgroup)"
}

**Comment by MikeRitchie** [comment]
This will be addressed in an upcoming 2.1 release coming very soon. Date will be shared as soon as it is available.
