### ISSUE TITLE
Out of Balance Distribution 

### ISSUE THREAD

**Issue by brtcali** [NCRCounterpointAPI/APIGuide#69]
We are having an issue when the deposit ticket posts where an Out of Balance distribtuion is reported. After researching this a bit, I have found that the PS_DOC_HDR_ORIG_DOC.ORIG_AMT_DUE is being populated with the amount. When in actuality it should be populating the PS_DOC_HDR_ORIG_DOC.DEP_AMT_RECEIVED. My understanding is that we do not have direct access to this table with the API, so how can we correct this?

Thank you in advance,
Brad Tyler 
Datatech Corporation

**Comment by MikeRitchie** [comment]
Thank you. Could you post the JSON that creates the bad distribution (be sure to remove/replace any sensitive info), as well as an indication of the distribution you expect to see that is missing? You are correct as if this is a defect it will need to be corrected in a future release/patch for the API.

**Comment by Bflatt** [comment]
this is the same as issue 43...

**Comment by brtcali** [comment]
Reading through that and it appears it is still a known issue, is that accurate? So what are we to do?

 

 

Brad Tyler  

Support Manager

15545 Devonshire Street, Suite 202 Mission Hills, CA 91345

Tel: 818-830-2600 ext. 101, Fax: 818-830-2610



 <http://www.datatechcorp.com/> www.datatechcorp.com

**Comment by Bflatt** [comment]
I know that Mike is working on this.    I have started not sending a an AMT and just setting as Final payment “y”.  The problem with this is the ticket will increase and not require additional payment on changes.  It will behave like a credit card marked as “y” and no amt.

[cid:image001.jpg@01D2DEDA.41EDDC70]

Bill Flatt
Mainspring, LLC
6060 S American Plaza St E | Suite 300 | Tulsa, OK | 74135
Phone: 800.865.1427 x2827 | Local: 918.317.0707 | Direct: 918.960.2827
bflatt@mainspring.net<mailto:bflatt@mainspring.net> | www.mainspring.net<http://www.mainspring.net> | Need Help?<mailto:support@mainspring.net>
[cid:image002.png@01D2DEDA.41EDDC70]<https://www.facebook.com/MainSpringRetailSolutions/>[cid:image003.png@01D2DEDA.41EDDC70]<https://twitter.com/MainspringPOS> [cid:image004.png@01D2DEDA.41EDDC70] <http://www.linkedin.com/company/576462>  [cid:image005.png@01D2DEDA.41EDDC70] <mailto:support@mainspring.net>

**Comment by brtcali** [comment]
Thanks Bill……I will give that a shot and see what happens.

 

 

Brad Tyler  

Support Manager

15545 Devonshire Street, Suite 202 Mission Hills, CA 91345

Tel: 818-830-2600 ext. 101, Fax: 818-830-2610



 <http://www.datatechcorp.com/> www.datatechcorp.com

**Comment by brtcali** [comment]
Hi Bill,

I appreciate your help.

I am not developing the API, but another vendor is. I don’t even have access to the API side. We tried to set this, but when it comes in, the ticket posts, but there is no amount on it and no credit card information on the ticket to be able to release the order. What are we missing?

 

 

Brad Tyler  

Support Manager

15545 Devonshire Street, Suite 202 Mission Hills, CA 91345

Tel: 818-830-2600 ext. 101, Fax: 818-830-2610



 <http://www.datatechcorp.com/> www.datatechcorp.com

**Comment by Bflatt** [comment]
"PS_DOC_PMT": [
     {

      "PAY_COD": "VISA",
        "FINAL_PMT": "Y",
        "PS_DOC_PMT_CR_CARD": {
        "CR_CARD_NO": "411111111111111",
        "CR_CARD_NAM": "name",
          "AVS_ZIP_COD": "30224",
          "CR_CARD_EXP_DAT": "02/2021"
       }      }
    ],

[cid:image001.jpg@01D2DEDA.41EDDC70]

Bill Flatt
Mainspring, LLC
6060 S American Plaza St E | Suite 300 | Tulsa, OK | 74135
Phone: 800.865.1427 x2827 | Local: 918.317.0707 | Direct: 918.960.2827
bflatt@mainspring.net<mailto:bflatt@mainspring.net> | www.mainspring.net<http://www.mainspring.net> | Need Help?<mailto:support@mainspring.net>
[cid:image002.png@01D2DEDA.41EDDC70]<https://www.facebook.com/MainSpringRetailSolutions/>[cid:image003.png@01D2DEDA.41EDDC70]<https://twitter.com/MainspringPOS> [cid:image004.png@01D2DEDA.41EDDC70] <http://www.linkedin.com/company/576462>  [cid:image005.png@01D2DEDA.41EDDC70] <mailto:support@mainspring.net>

**Comment by Bflatt** [comment]
Look at the deposit on the ticket.  It is there and on release the full amount of the ticket is applied.

**Comment by Bflatt** [comment]
HAve we made any progress on this issues. You requested a sample insert.   Just use the on in example YOU provided.  Post the drawer after insert you will see the out of balance distributions.  I have provided multiple examples of the misapplied deposit.   THis is a MAJOR hole in the api and has been on the books for over year.

**Comment by MikeRitchie** [comment]
This will be addressed in an upcoming 2.1 release coming very soon. Date will be shared as soon as it is available.
