### ISSUE TITLE
/Items endpoint responses error 500

### ISSUE THREAD

**Issue by Nepherhotep** [NCRCounterpointAPI/APIGuide#7]
Trying to call /Items endpoint responses error 500. Probably it's due to large results set:

Message:

{'ResponseStatus': {'ErrorCode': 'SqlException',
                    'Errors': [],
                    'Message': 'The incoming tabular data stream (TDS) remote '
                               'procedure call (RPC) protocol stream is '
                               'incorrect. Too many parameters were provided '
                               'in this RPC request. The maximum is 2100.',
                    'StackTrace': '[ItemsRequest: 3/2/2017 4:08:39 PM]:\n'
                                  '[REQUEST: {}]\n'
                                  'System.Data.SqlClient.SqlException '
                                  '(0x80131904): The incoming tabular data '
                                  'stream (TDS) remote procedure call (RPC) '
                                  'protocol stream is incorrect. Too many '
                                  'parameters were provided in this RPC '
                                  'request. The maximum is 2100.\r\n'
                                  '   at '
                                  'System.Data.SqlClient.SqlConnection.OnError(SqlException '
                                  'exception, Boolean breakConnection, '
                                  'Action`1 wrapCloseInAction)\r\n'
                                  '   at '
                                  'System.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject '
                                  'stateObj, Boolean callerHasConnectionLock, '
                                  'Boolean asyncClose)\r\n'
                                  '   at '
                                  'System.Data.SqlClient.TdsParser.TryRun(RunBehavior '
                                  'runBehavior, SqlCommand cmdHandler, '
                                  'SqlDataReader dataStream, '
                                  'BulkCopySimpleResultSet bulkCopyHandler, '
                                  'TdsParserStateObject stateObj, Boolean& '
                                  'dataReady)\r\n'
                                  '   at '
                                  'System.Data.SqlClient.SqlDataReader.TryConsumeMetaData()\r\n'
                                  '   at '
                                  'System.Data.SqlClient.SqlDataReader.get_MetaData()\r\n'
                                  '   at '
                                  'System.Data.SqlClient.SqlCommand.FinishExecuteReader(SqlDataReader '
                                  'ds, RunBehavior runBehavior, String '
                                  'resetOptionsString)\r\n'
                                  '   at '
                                  'System.Data.SqlClient.SqlCommand.RunExecuteReaderTds(CommandBehavior '
                                  'cmdBehavior, RunBehavior runBehavior, '
                                  'Boolean returnStream, Boolean async, Int32 '
                                  'timeout, Task& task, Boolean asyncWrite, '
                                  'SqlDataReader ds)\r\n'
                                  '   at '
                                  'System.Data.SqlClient.SqlCommand.RunExecuteReader(CommandBehavior '
                                  'cmdBehavior, RunBehavior runBehavior, '
                                  'Boolean returnStream, String method, '
                                  'TaskCompletionSource`1 completion, Int32 '
                                  'timeout, Task& task, Boolean asyncWrite)\r\n'
                                  '   at '
                                  'System.Data.SqlClient.SqlCommand.RunExecuteReader(CommandBehavior '
                                  'cmdBehavior, RunBehavior runBehavior, '
                                  'Boolean returnStream, String method)\r\n'
                                  '   at '
                                  'System.Data.SqlClient.SqlCommand.ExecuteReader(CommandBehavior '
                                  'behavior, String method)\r\n'
                                  '   at '
                                  'System.Data.SqlClient.SqlCommand.ExecuteDbDataReader(CommandBehavior '
                                  'behavior)\r\n'
                                  '   at '
                                  'System.Data.Common.DbCommand.System.Data.IDbCommand.ExecuteReader()\r\n'
                                  '   at '
                                  'ServiceStack.OrmLite.OrmLiteResultsFilterExtensions.ExprConvertToList[T](IDbCommand '
                                  'dbCmd, String sql, IEnumerable`1 sqlParams, '
                                  'HashSet`1 onlyFields)\r\n'
                                  '   at '
                                  'ServiceStack.OrmLite.ReadExpressionCommandExtensions.Select[T](IDbCommand '
                                  'dbCmd, Expression`1 predicate)\r\n'
                                  '   at '
                                  'ServiceStack.OrmLite.OrmLiteExecFilter.Exec[T](IDbConnection '
                                  'dbConn, Func`2 filter)\r\n'
                                  '   at '
                                  'CPAPI.Repositories_846.ItemRepository_846.CPAPI.Repositories_846.IItemRepository.GetItems(String '
                                  'categCod, String subcatCod)\r\n'
                                  '   at '
                                  'CPAPI.Business_846.ItemBusiness_846.GetItems(String '
                                  'categCod, String subcatCod)\r\n'
                                  '   at '
                                  'CPAPI.Services.ItemsService.Get(ItemsRequest '
                                  'request)\r\n'
                                  '   at '
                                  'ServiceStack.Host.ServiceRunner`1.Execute(IRequest '
                                  'request, Object instance, TRequest '
                                  'requestDto)\r\n'
                                  'ClientConnectionId:f4e2cac1-97a0-40d9-8ab6-9b46962dd337\r\n'
                                  'Error Number:8003,State:1,Class:16'}}

**Comment by MikeRitchie** [comment]
The error is created when we're getting child data of the items needed to build the heirarchy. In this case it's item notes. Under the covers we're doing a select to get all item notes where the "ITEM_NO" is IN a passed set of ITEM_NO values. However, due to the large number of items we're running into a SQL error. I think this will be an easy fix, but it will require a code change that will have to be planned for the next release or patch. In the meantime, you may be able to workaround it by filtering by the CategCod or SubcatCod like this:

GET /Items?CategCode=SHIRTS

A list of user defined categories & subcategories can be found in counterpoint under Setup > Inventory, or in the SQL DB directly in the IM_CATEG_COD or IM_SUBCAT_COD tables

**Comment by Nepherhotep** [comment]
Can you provide ETA for that release/patch?
Thanks.

**Comment by MikeRitchie** [comment]
It will likely be early Q2, given a big Counterpoint release we're wrapping up now. Will the workaround work for you in the interim? You can use GET /ItemCategories to get a list of Categories and subcategories, then cycle through them and call GET /Items?CategCode=<categ> for each category to grab the items in smaller chunks.

If that logic is encapsulated it should be fairly easy to convert to a single GET /Items call when the next release is out.

**Comment by MikeRitchie** [comment]
This will be fixed in the API 1.1 release, targeting late August. More details on the release will be posted soon.
