### ISSUE TITLE
Error in AddDocument POST: Missing type map configuration or unsupported mapping

### ISSUE THREAD

**Issue by baljeetbhardwaj** [NCRCounterpointAPI/APIGuide#70]
Hi, 

I am getting following error in addDocument

{"Documents":[],"ErrorCode":"ERROR_UNKNOWN","Message":"An error occurred during AddDocument POST: Missing type map configuration or unsupported mapping.\r\n\r\nMapping types:\r\nPO_VEND_ITEM -> PO_VEND_ITEM\r\nCPAPI.Model_846.PO_VEND_ITEM -> NCR.CP.CPAPI.Base.Model.PO_VEND_ITEM\r\n\r\nDestination path:\r\nPO_VEND_ITEM\r\n\r\nSource value:\r\nCPAPI.Model_846.PO_VEND_ITEM,    at CPAPI.V853.DocumentBusiness_853.PopulateDefaults(PS_DOC_HDR documentHeader, String workgroupId)\r\n   at CPAPI.V853.DocumentBusiness_853.AddDocument(PS_DOC_HDR_POST documentPost, PS_TAX_VIEW taxView, String workgroup)"}

please find an attached file for json.

[AddDocument.txt](https://github.com/NCRCounterpointAPI/APIGuide/files/1414178/AddDocument.txt)

**Comment by baljeetbhardwaj** [comment]
@MikeRitchie Please help!!

**Comment by Bflatt** [comment]
do you have a workaround?

**Comment by baljeetbhardwaj** [comment]
Not yet.

**Comment by Bflatt** [comment]
see my response to issue 82.  I found a workaround which indicates this is a data issue and potentially not an api issue.

**Comment by MikeRitchie** [comment]
This will be addressed in an upcoming 2.1 release coming very soon. Date will be shared as soon as it is available.
