### ISSUE TITLE
Document POST not taking TKT_NO

### ISSUE THREAD

**Issue by jharmas** [NCRCounterpointAPI/APIGuide#71]
When creating a document type T the ticket created doesn't have the TKT_NO sent in the json, rather is using the sequential in the Station settings. Note: the station settings does not have checked "Always auto assign"

[Json sent](https://drive.google.com/open?id=0BzHk9R2QjPN8R1lVSFgtV2xfcTg)

[Result in Database](https://drive.google.com/open?id=0BzHk9R2QjPN8VndjWlUzc2xEdkU)

**Comment by MikeRitchie** [comment]
This will be addressed in an upcoming 2.1 release coming very soon. Date will be shared as soon as it is available.
