### ISSUE TITLE
Sales Contract Data

### ISSUE THREAD

**Issue by langillerr** [NCRCounterpointAPI/APIGuide#74]
We use Sale Contracts to create sales within CounterPoint and are wondering how to get this information from the API.

For example an item, vendor, or even the entire store we might put on sale using sale contracts in CounterPoint.  If we put a vendor on sale for 20% off using contracts is there a way for the API to know that and to obtain that sales price?  

Another example would be when we put the entire store on sale for 20% for Day After Thanksgiving.  (Like everyone we do have exclusions.  We simply add those items to a separate sale file with no discount and move it to the top of the group order.)  

BOGO we have not done a lot of and we also do a lot of fixed price sales.

Any help would be appreciated.

**Comment by caribgit** [comment]
We would like to have this information also, and would appreciate a reply.

**Comment by langillerr** [comment]
@caribgit We've come up with a workaround in the meantime using the "Items on Sale" report's methodology to push data to a separate database on a periodic basis, and then serve it via a custom endpoint.  Not sure if that will help you.  

It doesn't help with items that have discounts based on customer role, but it does assist with things like general vendor or item specific sales.

**Comment by caribgit** [comment]
@langillerr thanks. Have you had any response from NCR otherwise? I'm not sure we are in a position to do the same as you at the moment.

**Comment by MikeRitchie** [comment]
Retrieving price rules (used to define contract prices) or pricing using price rules currently isn't supported in the API. 

You can get standard price (price-1) values through the API if needed. We'll look at feasibility of this for a future release, we're also investigating ways to allow API developers to execute custom SQL, provided we have a design that has adequate security measures to prevent malicious SQL attacks.

**Comment by langillerr** [comment]
@MikeRitchie Thank you for the timely reply.  Is there a "known limitations/issues" document somewhere we can look to for information like this?

**Comment by langillerr** [comment]
Thank you Mike. Would you prefer I close the issue, or leave it open for others with similar questions to stumble upon?

**Comment by caribgit** [comment]
Thank you @MikeRitchie - the custom SQL option would also very useful.

**Comment by MikeRitchie** [comment]
I will close the issue, it's still available to view and search on when closed. Thank you.
