### ISSUE TITLE
ArgumentException on all valid calls  "An item with the same key..."

### ISSUE THREAD

**Issue by aaijtm** [NCRCounterpointAPI/APIGuide#76]
On every call I try I am getting the following message
This particular one was generated from a get item request
{
    "ResponseStatus": {
        "ErrorCode": "ArgumentException",
        "Message": "An item with the same key has already been added.",
        "StackTrace": "   at System.ThrowHelper.ThrowArgumentException(ExceptionResource resource)\r\n   at System.Collections.Generic.Dictionary`2.Insert(TKey key, TValue value, Boolean add)\r\n   at CPAPI.Common.RegistrationIniBusiness.ValidateRegistrationFile(String dbName)\r\n   at CPAPI.Common.RegIniAttribute.Execute(IRequest req, IResponse res, Object requestDto)\r\n   at ServiceStack.RequestFilterAttribute.RequestFilter(IRequest req, IResponse res, Object requestDto)\r\n   at ServiceStack.ServiceStackHost.ApplyRequestFiltersSingle(IRequest req, IResponse res, Object requestDto)\r\n   at ServiceStack.ServiceStackHost.ApplyRequestFilters(IRequest req, IResponse res, Object requestDto)\r\n   at ServiceStack.Host.RestHandler.ProcessRequestAsync(IRequest httpReq, IResponse httpRes, String operationName)"
    }
}

**Comment by mbantug** [comment]
Do you either have:

1. 2 companies with the same name in the API?
2. Duplicate key lines in your Registration.ini file?

**Comment by aaijtm** [comment]
You are correct.  Sorry for the duplication.
