### ISSUE TITLE
Glossary questions

### ISSUE THREAD

**Issue by Nepherhotep** [NCRCounterpointAPI/APIGuide#8]
I'm a bit confused with definitions used in API, for example: 

* What is the difference between inventory and item?
* What is Location in calls like /Items/LocId
* Where can I get LocId?

**Comment by MikeRitchie** [comment]
Item: Refers to core information about an item, regardless of if/where it's stocked. Item name, number, catgetory, grid dimensions (size, color, etc) are all accessible. 

Location: Location is a place where items are stocked, and thus, where inventory exists. For instance, if you have an item in each of two stores (A & B), and a warehouse, a Counterpoint user would define 3 locations (in Counterpoint at Setup > Inventory > Locations). The location ID can be found from Counterpoint.

Inventory: Inventory is the amount of an item stored in a given location. There are several inventory fields you should be aware of:
* QTY_ON_HND: The amount of inventory that is physically in that location
* QTY_COMMIT: The amount of inventory that is already "spoken for". For instance, if an order is already entered and slated to be filled with some of the QTY_ON_HAND, that quantity would show up here.
* QTY_AVAIL: The amount of inventory available for use (it's not spoken for). This is typically the field that is used to see if an item is in stock and available for someone to order/purchase.

Locations (LocID) aren't curreently available in the API. For eCommerce applications often there's a single location used for fulfillment, so LocID can be hardcoded, but it would be good to add an endpoint to retreive all locations via the API.

**Comment by Nepherhotep** [comment]
Now it's much clearer, thanks.
