### ISSUE TITLE
Tax code and Rule insert

### ISSUE THREAD

**Issue by Bflatt** [NCRCounterpointAPI/APIGuide#81]
The api documents inserting a rule with a tax code.  This is problematic because may tax code have multiple rules.  With CPonline and NRO the tax was calculated online and inserted as an amount and SINGLE TAX CODE.  It was irrelevant that the tax code may have 2 or 3 authorities and rules.   With the api we can only have one ruled per tax code as inserting the rule is required.  It would be better if we could just include the tax code and amount, and let counterpoint work as it always has and provide the rules.   Is this something we can work around or am I missing a feature?

**Comment by Intramix** [comment]
Bflatt,

When you define your URI parameter for the API call have you tried to use an empty string "" for the value or * for the value?

I am assuming that the empty string will probably return no value as no tax authority was defined. However I am also curious if using "*" will return all tax authority values. 

Let me know if you test this and what the result is, also how are you making these API requests? Did you develop a program to make these calls or are you making these call through the browser?

**Comment by Bflatt** [comment]
That works.  Leaving the Rul_cod:”” lets counterpoint assign the correct rules associated with the tax code without naming the individual rules.   As long as the correct tax amt is passed in the doc insert, counterpoint puts the correct amount in the correct authority and rule buckets.

Many Thanks,

[cid:image001.jpg@01D2DEDA.41EDDC70]

Bill Flatt
Mainspring, LLC
6060 S American Plaza St E | Suite 300 | Tulsa, OK | 74135
Phone: 800.865.1427 x2827 | Local: 918.317.0707
bflatt@mainspring.net<mailto:bflatt@mainspring.net> | www.mainspring.net<http://www.mainspring.net/> | Need Help?<mailto:support@mainspring.net>
[cid:image002.png@01D2DEDA.41EDDC70]<https://www.facebook.com/MainSpringRetailSolutions/>[cid:image003.png@01D2DEDA.41EDDC70]<https://twitter.com/MainspringPOS> [cid:image004.png@01D2DEDA.41EDDC70] <http://www.linkedin.com/company/576462>  [cid:image005.png@01D2DEDA.41EDDC70] <mailto:support@mainspring.net>

**Comment by Intramix** [comment]
Bflatt,

Hey awesome man! I am glad we could come to a resolution for you.

**Comment by Bflatt** [comment]
this issue can be closed.  It is not a bug.
