### ISSUE TITLE
Error_Unknown - An error occurred during ADDDocument POST: Object reference not set to a n instance of an object

### ISSUE THREAD

**Issue by KMGREENE** [NCRCounterpointAPI/APIGuide#91]
Error below received after posting a document. The document is created in the database but I am receiving the following error after I issue a POST. Looking for guidance.
Thanks
Michelle

Error:
{
    "Documents": [],
    "ErrorCode": "ERROR_UNKNOWN",
    "Message": "An error occurred during AddDocument POST: Object reference not set to an instance of an object.,    at NCR.CP.CPAPI.Base.Business.DocumentExtensions.AddAuditLog(PS_DOC_HDR header, String Activity, String LogEntry, DocumentKey linkedkey)\r\n   at NCR.CP.CPAPI.Base.Business.DocumentBusiness.SaveMixedDocument(PS_DOC_HDR document, PS_TAX tax)\r\n   at NCR.CP.CPAPI.Base.Business.DocumentBusiness.AddDocument(PS_DOC_HDR_POST documentPost, PS_TAX_VIEW taxView, String workgroup)"
}

Here is my JSON:
{
  "PS_DOC_HDR": {
    "STR_ID": "895-FOXP",
    "STA_ID": "895-01",
    "DRW_ID": "895-01",
    "TKT_TYP": "T",
    "DOC_TYP": "H",
    "TKT_NO": "2RMA_0123456789",
    "DESCR": "2RMA-0123456789-36.57",
    "CUST_PO_NO": "2RMA_0123456789",
    "USR_ID": "LEHORIZON",
    "PS_DOC_NOTE": [
      {
        "NOTE_ID": "TEST",
        "NOTE": "RMA Testing. Creating a Hold Ticket!"
      }
    ],
    "PS_DOC_LIN": [
      {
        "LIN_TYP": "S",
        "ITEM_NO": "120-MANUAL-NOTAX",
        "PRC":"0.00",
        "USR_ENTD_PRC":"N",
        "QTY_SOLD": "1.0",
        "TKT_NO": "2RMA_0123456789",
        "BARCOD": "2RMA_0123456789",
        "TARE_WEIGHT": "36.57"
      }
    ],
   "PS_DOC_PMT": [
 {
 "AMT": "0.01",
 "PAY_COD": "CASH",
 "FINAL_PMT": "N"
 }
 ],
 "PS_DOC_TAX": [
 {
 "AUTH_COD": "NOTAX",
 "RUL_COD": "NOTAX",
 "TAX_DOC_PART": "S",
 "LIN_AMT": "0.00",
 "TXBL_LIN_AMT": "0.00",
 "TXBL_QTY": "0.0000",
 "TAX_AMT": "0.00",
 "TOT_TXBL_AMT": "0.00"
 }
 ]
 }
 }

**Comment by pheslop** [comment]
I don't know about the error but I noticed a couple of things:

DESCR doesn't exist on the HDR
Hold tickets don't have payment
I don't think you need to specify a TKT_NO on the HDR or LIN

**Comment by KMGREENE** [comment]
Thanks you for the help! I moved DESCR to PS_DOC_LINS and removed Payment but when I remove TKT_NO - I get an error right away saying that it is required in the HDR. 

I am still receiving the same message above even with the changes I incorporated. 
{
  "PS_DOC_HDR": {
    "STR_ID": "895-FOXP",
    "STA_ID": "895-01",
    "DRW_ID": "895-01",
    "TKT_TYP": "T",
    "DOC_TYP": "H",
    "TKT_NO": "7RMA_0123456789",
    "CUST_PO_NO": "7RMA_0123456789",
    "TAX_COD": "EXEMPT",
    "SHIP_TO_CONTACT_ID": = "2",
    "NORM_TAX_COD": "EXEMPT",
    "LST_FRM_GRP_PRTD": "HOLD",
    "LST_FRM_PRTD": "Receipt1.rdlc",
    "USR_ID": "LEHORIZON"
   "PS_DOC_LIN": [
      {
        "LIN_TYP": "S",
        "ITEM_NO": "120-MANUAL-NOTAX",
        "DESCR": "7RMA0123456789 36.57",
        "PRC":"0.00",
        "USR_ENTD_PRC":"N",
        "QTY_SOLD": "1.0",
        "TAX_CATEG":"89999",
        "NORM_TAX_CATEG": "89999",
        "HAS_PRC_OVRD": "Y",
        "QTY_ENTD": "0.0000",
        "BARCOD": "7RMA_0123456789",
        "TARE_WEIGHT": "36.57"
      }
    ],
   "PS_DOC_TAX": [
      {
        "AUTH_COD": "EXEMPT",
        "RUL_COD": "EXEMPT",
        "TAX_DOC_PART": "S",
        "LIN_AMT": "0.00",
        "TXBL_LIN_AMT": "0.00",
        "TXBL_QTY": "0.0000",
        "TAX_AMT": "0.00",
        "TOT_TXBL_AMT": "0.00"
      }
    ]
    }
 }

**Comment by MikeRitchie** [comment]
Could you execute the call that generates the ERROR_UNKNOWN result, then send me the latest logfile from the \logfiles directory?

**Comment by KMGREENE** [comment]
Hi Mike,
I have attached the log file as well as the code that I executed. I have a need to create a hold ticket. As soon as I change the ps_doc_hdr doc_type from 'H' to 'O', I am able to complete the transaction. However, I am needing the ability to create the ticket as a Hold ticket so I need the 'H' doc_type.  Hoping you can point me in the right direction.
Thanks
Michelle

[CPAPI_2018-01-23.0.log](https://github.com/NCRCounterpointAPI/APIGuide/files/1657757/CPAPI_2018-01-23.0.log)
[CreatingHoldTicket.txt](https://github.com/NCRCounterpointAPI/APIGuide/files/1657758/CreatingHoldTicket.txt)

**Comment by MikeRitchie** [comment]
A couple of things I've found investigating this:
* Your posted "CreatingHoldTicket.txt" file had a errant comma after the "TARE_WEIGHT". Unfortunately with JSON, those errors cause the rest of the JSON after the error to be ignored. When creating ad hoc JSON for testing, I use a Chrome extension called "JSON Editor" that can identify syntax errors and pretty print JSON to help eliminate these problems. 
* You don't need to include empty elements like "PS_DOC_NOTE": [] in your JSON. It's not harmful, but it can also be left out if you'd like to keep the JSON more compact.
* I can reproduce the ERROR_UNKNOWN result and have unfortunately traced it to a bug in the API 2.0 release. We already have a fix identified, but don't have a date yet for the next release. The issue affects HOLD and QUOTE tickets and there is currently no workaround.

**Comment by JasonDSchuster** [comment]
Mike,

One thing of note is that I tested with a basic hold ticket and I get the error response on any hold ticket request in 8.5.4 (but hold ticket is still created), but if I try in 8.5.3 it works without an error for both holds and quotes. Haven't tested any other versions of CounterPoint.

**Comment by KMGREENE** [comment]
Hi Mike, We are on version 8.5.2 and I am getting the same error even after I made the changes that you recommended. The data is writing to the database however.  Do you think we could 'ignore' the error and continue the use the API call or do you recommend another workaround for us? I didn't know if it would be recommended make a direct insert SQL call in lieu of the bug or if there is another potential workaround using the API. Michelle

**Comment by MikeRitchie** [comment]
The error occurs when writing a record to the PS_AUDIT_LOG table, so that record will be missing due to the issue. However, that typically isn't critical and it appears that is the last step in processing the request before sending the result back. So you may be ok to ignore the error if you find that the ticket can be recalled and completed without issue.

**Comment by KMGREENE** [comment]
I am finding I can recall the hold ticket and complete the transaction. We will try to ignore it until the bug is fixed in the next release. Thank you so much!
